/**
 * Created by vietanha34 on 1/6/16.
 */

module.exports =  { an_cac: 1,
  ancac: 1,
  'ăn cặc': 1,
  'ăncặc': 1,
  'bà mày': 1,
  'ba mày': 1,
  'bàmay': 1,
  'bamày': 1,
  'bàmày': 1,
  bamay: 1,
  ban_dam: 1,
  ban_hoa: 1,
  bandam: 1,
  bomay: 1,
  bon_cho: 1,
  bon_khon_nan: 1,
  boncho: 1,
  bonkhonnan: 1,
  bucac: 1,
  cai_buoi: 1,
  cai_chim: 1,
  cai_cu: 1,
  cai_lon: 1,
  caibuoi: 1,
  caichim: 1,
  caicu: 1,
  cailon: 1,
  chim: 1,
  chim_to: 1,
  chimto: 1,
  cho_kin: 1,
  chochet: 1,
  chokin: 1,
  con_cho: 1,
  con_cu_cac: 1,
  con_cu_to_tuong: 1,
  con_di: 1,
  con_diem: 1,
  con_pho: 1,
  concho: 1,
  concu: 1,
  concucac: 1,
  concutotuong: 1,
  condi: 1,
  condiem: 1,
  conghoa: 1,
  conlon: 1,
  conpho: 1,
  'cụ': 1,
  cu_to: 1,
  cuc_cac: 1,
  cucac: 1,
  cuccac: 1,
  cuccut: 1,
  cuho: 1,
  cumay: 1,
  cuong_dam: 1,
  cuong_hiep: 1,
  cuongdam: 1,
  cuonghiep: 1,
  'dịt': 1,
  'đít': 1,
  dit_bo: 1,
  dit_con_cu: 1,
  dit_concu: 1,
  dit_conme: 1,
  dit_cu: 1,
  dit_cu_may: 1,
  dit_ong: 1,
  ditba: 1,
  ditbo: 1,
  ditme: 1,
  ditmemay: 1,
  ditong: 1,
  dume: 1,
  gai_ban_hoa: 1,
  gai_diem: 1,
  gaibanhoa: 1,
  gaidiem: 1,
  ham_hiep: 1,
  hamhiep: 1,
  hanh_kinh: 1,
  hanhkinh: 1,
  hiep_dam: 1,
  hiepdam: 1,
  'hồ_chí_minh': 1,
  ho_chiminh: 1,
  hochiminh: 1,
  'iả': 1,
  'ỉa': 1,
  'khốn': 1,
  khon_nan: 1,
  khonnan: 1,
  kiep: 1,
  'kiép': 1,
  'kiếp': 1,
  lamtinh: 1,
  liem_cac: 1,
  liemcac: 1,
  'lòn': 1,
  'lợn': 1,
  lon_to: 1,
  long_lon: 1,
  longlon: 1,
  lonto: 1,
  mau_kinh: 1,
  maukinh: 1,
  maulon: 1,
  'mẹ': 1,
  mekiep: 1,
  memay: 1,
  mie: 1,
  mohamet: 1,
  muadam: 1,
  mutbuoi: 1,
  mutcac: 1,
  nake: 1,
  nguyenai_quoc: 1,
  nguyenaiquoc: 1,
  pimp: 1,
  sinh_duc: 1,
  sinhduc: 1,
  so_lon: 1,
  solon: 1,
  su_bo_may: 1,
  subomay: 1,
  tosu: 1,
  v_cong: 1,
  vai_dai: 1,
  vai_leu: 1,
  vai_lin: 1,
  vai_lon: 1,
  vaidai: 1,
  vaileu: 1,
  vailin: 1,
  vailon: 1,
  vcong: 1,
  viet_cong: 1,
  '1ồn': 1,
  '10n': 1,
  '10`n': 1,
  '1`0n': 1,
  _bacho_: 1,
  bac_ho: 1,
  'bác hồ': 1,
  'b4c hồ': 1,
  'b\'4c hồ': 1,
  'b4\'c hồ': 1,
  'bac h0': 1,
  buoi: 1,
  'buoi`': 1,
  'buồi': 1,
  'bu0`i': 1,
  congsan: 1,
  'cong san': 1,
  'cộng sản': 1,
  c_a_c: 1,
  c4c: 1,
  'cac.': 1,
  'căc.': 1,
  'cặc': 1,
  cave: 1,
  'cứt': 1,
  d1t: 1,
  'dai\'': 1,
  'dái': 1,
  'đái': 1,
  'dâm': 1,
  damn: 1,
  dcm: 1,
  'đcm': 1,
  'đĩ': 1,
  'đi~': 1,
  'dĩ': 1,
  'di~': 1,
  'di.t': 1,
  'đi.t': 1,
  'địt': 1,
  dis: 1,
  'đis': 1,
  'đit': 1,
  dit: 1,
  'điếm': 1,
  dm: 1,
  'đm': 1,
  dmm: 1,
  'đmm': 1,
  'đcmm': 1,
  dkm: 1,
  'đkm': 1,
  dkmm: 1,
  'đkmm': 1,
  'đụ': 1,
  'đu.': 1,
  fuck: 1,
  f_u_c_k: 1,
  g4memaster: 1,
  g4mem4ster: 1,
  g4me_master: 1,
  'g4me*master': 1,
  gamemaster: 1,
  game_master: 1,
  '[game]master': 1,
  'game*master': 1,
  'game[master]': 1,
  gm: 1,
  '[g]m': 1,
  'g[m]': 1,
  'hồ chí minh': 1,
  ho_chi_minh: 1,
  'ho chi minh': 1,
  'hiếp': 1,
  'lo`n': 1,
  'lon`': 1,
  'lồn': 1,
  'lôn': 1,
  mk: 1,
  'nông đức mạnh': 1,
  nongducmanh: 1,
  penis: 1,
  'phạm văn đồng': 1,
  phamvandong: 1,
  'phò': 1,
  'pho`': 1,
  rape: 1,
  sex: 1,
  sh1t: 1,
  shit: 1,
  'tổng bí thư': 1,
  tongbithu: 1,
  'tong bi thu': 1,
  vietcong: 1,
  'viet cong': 1,
  'việt công': 1,
  'việt cộng': 1,
  'lìn': 1,
  'li`n': 1,
  'thủ dâm': 1,
  '!ồn': 1,
  '£jn`': 1,
  '£ô`n': 1,
  '£ôñ': 1,
  '£ồn': 1,
  '£ồñ': 1,
  '₫éo': 1,
  '₫iṭ': 1,
  '₫yt': 1,
  '=-yt.': 1,
  '¶)¡t': 1,
  '¶)ị†': 1,
  '¶_ơñ': 1,
  '¶ồñ': 1,
  '†¡ñ': 1,
  '†€̀': 1,
  '†ổ': 1,
  '1o`n': 1,
  '1on': 1,
  '1ôn': 1,
  'a(n cac': 1,
  'am vat': 1,
  'an buoi': 1,
  'an kut': 1,
  'an kuz': 1,
  'an loz': 1,
  'an no^n': 1,
  'äñ£0ñ': 1,
  anloz: 1,
  'ăn buoi': 1,
  'bµ́': 1,
  'bµ0m': 1,
  'bµồi': 1,
  'b0 cu': 1,
  'b0 ku': 1,
  'b3`': 1,
  'ba`': 1,
  'bím': 1,
  bitch: 1,
  bkl: 1,
  'bó cu': 1,
  'bo ku': 1,
  'bó ku': 1,
  'bo^\'': 1,
  'bu\'': 1,
  'bu b': 1,
  'bu\' b': 1,
  'bu bu0j': 1,
  'bu buoi': 1,
  'bu buoj': 1,
  'bu lol': 1,
  'bu\' lol': 1,
  'bu loz': 1,
  'bu\' loz': 1,
  'bu0^j': 1,
  'bu0+m': 1,
  bu0i: 1,
  bu0j: 1,
  'bu0j`': 1,
  bu0m: 1,
  'bu0\'m': 1,
  'bu0z`': 1,
  'bubu0¡': 1,
  bubuoj: 1,
  'buo^i': 1,
  'buo^j`': 1,
  'buo^\'m': 1,
  'buo^y`': 1,
  'buoi^': 1,
  buoj: 1,
  'buoj`': 1,
  buom: 1,
  'buo\'m': 1,
  'buôi': 1,
  'buôì': 1,
  'buôj': 1,
  'buồj': 1,
  'buồy': 1,
  'buớm': 1,
  'bướm': 1,
  bvs: 1,
  bym: 1,
  'bým': 1,
  'c0n dy~': 1,
  'c0n f0`': 1,
  'c0n m3': 1,
  'c0n me': 1,
  'c0n mẹ': 1,
  'c0n pho': 1,
  c0nch0: 1,
  'c0ng s4n': 1,
  c4v3: 1,
  c4ve: 1,
  'ca.c': 1,
  cac: 1,
  'cạc': 1,
  'cạ̈c': 1,
  'cai dis': 1,
  'cai\' dis': 1,
  'cái dis': 1,
  'cai dkm': 1,
  'cai\' loz': 1,
  cailoz: 1,
  'caj dis': 1,
  'caj djjt me': 1,
  'caj dkm': 1,
  'caj loz': 1,
  'caj lozl': 1,
  'caj…đị†': 1,
  cak: 1,
  'cam iồn': 1,
  cav3: 1,
  'căc': 1,
  'cặç': 1,
  'çăç': 1,
  'căk': 1,
  'cặk': 1,
  'cec.': 1,
  'çhÿm': 1,
  cl: 1,
  con: 1,
  'çoñ': 1,
  'con cac': 1,
  'çøn çhǿ': 1,
  'con ch0': 1,
  'con di~': 1,
  'con diem': 1,
  'con fò': 1,
  'con fo`': 1,
  'con ion`': 1,
  'con m3': 1,
  'con me': 1,
  'con mẹ': 1,
  'çu+t\'': 1,
  'cu0ng da^m': 1,
  'cuc\'': 1,
  'cuc ga`': 1,
  'çứ†': 1,
  'ch0́': 1,
  'ch0\'\'': 1,
  'ch0\'': 1,
  'ch0 ghe dis': 1,
  'ch0 sua': 1,
  'ch0.': 1,
  'ch0\'a': 1,
  'chém': 1,
  chet: 1,
  chjm: 1,
  'chó': 1,
  'cho\'': 1,
  'cho kon bu\'': 1,
  'cho"': 1,
  chui: 1,
  chuj: 1,
  'chuj?': 1,
  'chuj~': 1,
  chuym: 1,
  'chửi..': 1,
  chym: 1,
  'd!t': 1,
  'd!tl': 1,
  'd¥¶¯': 1,
  'd†cm': 1,
  d0g: 1,
  'd1~': 1,
  'dá¡': 1,
  daj: 1,
  'dáj': 1,
  'daj\'': 1,
  'dang hang': 1,
  'dạng háng': 1,
  de0: 1,
  'de0\'': 1,
  'de0"': 1,
  'de0`': 1,
  'de0~': 1,
  dek: 1,
  'dek\'': 1,
  deo: 1,
  'de\'o': 1,
  'deó': 1,
  'déo': 1,
  '-deo\'': 1,
  'deo\'': 1,
  'deo\' ia?': 1,
  'deo kut\'': 1,
  'deo"': 1,
  'det m3': 1,
  'det. me.': 1,
  'dey the\'': 1,
  'di.s': 1,
  'di.s me.': 1,
  'dï§': 1,
  'di†': 1,
  'dị†': 1,
  'dï†': 1,
  dien: 1,
  'd-iếm': 1,
  diit: 1,
  'dïs': 1,
  'dis\'': 1,
  'dis c0n me': 1,
  'dis c0n mje': 1,
  'dis co0n me': 1,
  'dis cu': 1,
  'dis k0n me': 1,
  'dis ku': 1,
  'dis me': 1,
  'dis me.': 1,
  'dis me…': 1,
  'dis.': 1,
  disd: 1,
  disme: 1,
  'diss m3': 1,
  'diss me': 1,
  disss: 1,
  'di\'t': 1,
  dix: 1,
  diz: 1,
  'dịz': 1,
  dj: 1,
  'dj~': 1,
  'dj†': 1,
  'dje^m\'': 1,
  'dje^\'m': 1,
  djem: 1,
  'djem\'': 1,
  djf: 1,
  djit: 1,
  'djj~': 1,
  djjt: 1,
  djs: 1,
  djx: 1,
  djz: 1,
  dk: 1,
  'dk.': 1,
  dlt: 1,
  'doet.': 1,
  'dú': 1,
  'dụ': 1,
  'du m3': 1,
  'du ma': 1,
  'du má': 1,
  'du me maj`': 1,
  'du.': 1,
  'du. me.': 1,
  'du` moa\' an kut\'': 1,
  'duk.': 1,
  'duong vat': 1,
  duyt: 1,
  'dÿ\u0018 ḿ\u0003': 1,
  'dy.t': 1,
  'dy`n': 1,
  'dy~': 1,
  'dy~ deo\' daj traj': 1,
  dys: 1,
  'dys mje': 1,
  dyt: 1,
  'dyt\'': 1,
  'dyt buoj ': 1,
  'dyt c0n m3': 1,
  'dỵt c0n me': 1,
  'dyt cai i0ng c0ng l0z': 1,
  'dyt dyt': 1,
  'dyt k0an': 1,
  'dyt k0n m3': 1,
  'dyt kon me': 1,
  'dyt kon me kaj\'\' loz`': 1,
  'dyt kon me sock': 1,
  'dyt ku.': 1,
  'dyt l0z': 1,
  'dyt m': 1,
  'dyt m3': 1,
  'dyt m3 an kuz': 1,
  'dyt me': 1,
  'dyt me nung l0zl': 1,
  'dyt me thagfo`': 1,
  'dyt me.': 1,
  'dyt mje': 1,
  'đ!†': 1,
  'đ¡§': 1,
  'đ¡†': 1,
  'đ¡̣†': 1,
  'đ¡•t': 1,
  'đ¡̣t': 1,
  'đ¥†': 1,
  'đ¥̣†': 1,
  'đ¥t': 1,
  'đ¥̣t': 1,
  'đ€́ø': 1,
  'đµ': 1,
  'đµ̣': 1,
  'đµ̣ møª́': 1,
  'đµ́†': 1,
  'đ†çm': 1,
  'đé0': 1,
  'đeó': 1,
  'đéo': 1,
  'đï': 1,
  'đĩ đựç': 1,
  'đị†': 1,
  'đị̈†': 1,
  'đi†': 1,
  'đi†çâñañh': 1,
  'đi†mẹ': 1,
  'điên': 1,
  'điĩ': 1,
  'địs': 1,
  'đis mẹ': 1,
  'đit m3.': 1,
  'đit mẹ': 1,
  'địt me': 1,
  'địt mẹ': 1,
  'địt.': 1,
  'địt. đỳn': 1,
  'địt...': 1,
  'điz': 1,
  'đî†̣': 1,
  'đị̂†': 1,
  'đị̂†…mẹ': 1,
  'đị̂t': 1,
  'đj̃': 1,
  'đj†': 1,
  'đjếm': 1,
  'đjếm ': 1,
  'đjt': 1,
  'đj̣t': 1,
  'đklm': 1,
  'đlt': 1,
  'đu': 1,
  'đụ mẹ': 1,
  'đỹ': 1,
  'đÿ§': 1,
  'đÿ†': 1,
  'đỵ̈†': 1,
  'đy†': 1,
  'đỵ† kụ': 1,
  'đỵ̈† m€̣': 1,
  'đys…': 1,
  'đyt': 1,
  'đỵt': 1,
  'đÿt': 1,
  'đyṭ mẹ': 1,
  'đyt me.': 1,
  'đyt.': 1,
  'đyz': 1,
  'f`o`': 1,
  'ƒµ¢¶«': 1,
  'fµck': 1,
  'ƒµck': 1,
  'ƒµçk': 1,
  f0: 1,
  'ƒ0': 1,
  'ƒ0ƒ': 1,
  'fho`': 1,
  fo: 1,
  'fö̀': 1,
  'fø̀': 1,
  'ƒo': 1,
  'ƒò': 1,
  'ƒø̀': 1,
  'fò': 1,
  'ƒo`': 1,
  'fo`': 1,
  'foo`': 1,
  'ƒuc¶«': 1,
  'ƒuck': 1,
  'ƒüçk': 1,
  fuuck: 1,
  'ghe?': 1,
  'gie? rach\'': 1,
  'ham~ ion': 1,
  'ham~ loz': 1,
  'ham~ lozl': 1,
  'ham~ lozn`': 1,
  hamloz: 1,
  hcm: 1,
  hi3p: 1,
  'hi3\'p': 1,
  'hie\'p': 1,
  'hiep\'': 1,
  'hiêp\'': 1,
  hjep: 1,
  'hl`': 1,
  'i.t': 1,
  'i^0n': 1,
  'i0^k`': 1,
  'i0`n': 1,
  'i0`n`': 1,
  i0n: 1,
  'i0n`': 1,
  i0z: 1,
  'iạ': 1,
  'io^`n': 1,
  'io^-n': 1,
  'io^n': 1,
  'io^n`': 1,
  'io^ng': 1,
  'io`n': 1,
  ion: 1,
  'ion`': 1,
  'ion` me': 1,
  'ion`. dis': 1,
  ioz: 1,
  'ioz`': 1,
  'iôn': 1,
  'iồn': 1,
  'iồñ': 1,
  'iôn`': 1,
  'iông': 1,
  'ịt': 1,
  'ja?': 1,
  k0n: 1,
  'k0n cac': 1,
  'k0n ch0': 1,
  'k0n ch0 an cuc\'': 1,
  'k0n m0e. maj': 1,
  'k0n m3': 1,
  'k0n me': 1,
  'k0n me maj': 1,
  'k3 m3': 1,
  k4v3: 1,
  k4ve: 1,
  'kaj dyt me': 1,
  'kaj\' dyt. me': 1,
  kak: 1,
  'kat ku': 1,
  kav3: 1,
  kave: 1,
  'kăc': 1,
  'kặc': 1,
  'kặç': 1,
  'kit\'': 1,
  klm: 1,
  kon: 1,
  'kon dkm': 1,
  'kon ch0\'': 1,
  'kon cho\'': 1,
  'kon dj?': 1,
  'kon dy~': 1,
  'kon f0': 1,
  'kon kac': 1,
  'kon kak': 1,
  'kon ky~': 1,
  'kon m3': 1,
  'kon me': 1,
  'kon mẹ': 1,
  kotex: 1,
  ku: 1,
  'kụ': 1,
  'ku*\'t': 1,
  'ku+t\'': 1,
  'kuc\'': 1,
  'kuc kut': 1,
  kut: 1,
  'kut\'': 1,
  'kut ch0': 1,
  'kut het': 1,
  'kut nat': 1,
  kuz: 1,
  'kuz\'': 1,
  'kứ†': 1,
  'kứ†…çhó': 1,
  'kưt\'': 1,
  'kưt́': 1,
  'kứt': 1,
  'kynh nguye^t.': 1,
  'khìn': 1,
  'khjn`': 1,
  khoviion: 1,
  'l dog': 1,
  'l to': 1,
  'l`': 1,
  'l0^n`': 1,
  'l0^z`': 1,
  'l0`z': 1,
  l0n: 1,
  l0on: 1,
  l0x: 1,
  l0z: 1,
  'l0z`': 1,
  'l0z` mej': 1,
  l0zl: 1,
  'l0zl`': 1,
  l0zn: 1,
  'l0zn`': 1,
  l0zz: 1,
  'la liem': 1,
  'la pho`': 1,
  'lam` fo`': 1,
  li3m: 1,
  'li3\'m': 1,
  'lie^m: lolz` mek lolz`': 1,
  'lie\'m': 1,
  'liem\'': 1,
  'liem i0n ch0': 1,
  'li\'m': 1,
  'lím': 1,
  'lin`': 1,
  ljn: 1,
  'ljn`': 1,
  lm: 1,
  'lo^`n': 1,
  'lo^lz`': 1,
  'lo^n': 1,
  'lo^n`': 1,
  'lo^z': 1,
  'lo^z`': 1,
  'lo^zn`': 1,
  'lo+i`': 1,
  'lo0^n`': 1,
  'lo0n`': 1,
  loiz: 1,
  lol: 1,
  lolz: 1,
  lon: 1,
  'lön': 1,
  'lon\'': 1,
  loon: 1,
  'loon`': 1,
  loz: 1,
  'löz': 1,
  'loz`': 1,
  lozl: 1,
  'lozl`': 1,
  lozn: 1,
  'lô`n': 1,
  'lôlz': 1,
  'lôñ': 1,
  'lôñ̀': 1,
  'lồñ': 1,
  'lôǹ': 1,
  'lôn`': 1,
  'lồnz': 1,
  'lồz': 1,
  'lu`n': 1,
  'lu~ d0g': 1,
  'lu~ re rack:': 1,
  'lu~dog': 1,
  'lũ…dog húp…máu': 1,
  'lua tinh': 1,
  'lun`': 1,
  'luoj~ tat\' va`o dau` buoj`': 1,
  'lz0`': 1,
  'lz0n`': 1,
  'lzo`': 1,
  'lzo`l': 1,
  lzol: 1,
  'lzol`': 1,
  'lzồn': 1,
  'm€̣ maj`': 1,
  'm0m~': 1,
  m3: 1,
  'm3 mai': 1,
  'ma(t. loz': 1,
  'mau\' io`n': 1,
  'mau\' ion': 1,
  'mau l': 1,
  'mau l0z': 1,
  'mau lol': 1,
  'mau loz': 1,
  'mau non`': 1,
  'may`': 1,
  me: 1,
  'mẹ̈': 1,
  'me chung maj': 1,
  'me mai': 1,
  'me maj': 1,
  'me. maj`': 1,
  'met loz': 1,
  mi: 1,
  'mịe': 1,
  'mie.': 1,
  mje: 1,
  ml: 1,
  'ml`': 1,
  'mo^m loz': 1,
  'mõm': 1,
  'mom~': 1,
  'mom~ dog lu~ ch0': 1,
  'mú†': 1,
  mut: 1,
  'mút': 1,
  'mut\'': 1,
  'mut bi0i': 1,
  'mut bu0j': 1,
  'mut ku': 1,
  'mut\' lz0n`': 1,
  'ñ§ü': 1,
  'ñgậm…ßµồ¡': 1,
  'niém': 1,
  'njn`': 1,
  'no^n`': 1,
  'no`n': 1,
  non: 1,
  'non^`': 1,
  'non`': 1,
  'nôn': 1,
  'nồn': 1,
  'nồñ': 1,
  'ñồñ': 1,
  'ñôǹ': 1,
  'nồz': 1,
  'nu*ng\'': 1,
  'nun`': 1,
  'nung*\' loz`': 1,
  'nứng': 1,
  ngu: 1,
  'nh0n`': 1,
  'nha` may`': 1,
  'nho^n`': 1,
  'nhu cac': 1,
  'nhuc̣…': 1,
  nhuk: 1,
  'p3`': 1,
  'pà': 1,
  'pa`': 1,
  'pa` may`': 1,
  playku: 1,
  'pó cu': 1,
  'po ku': 1,
  'pó ku': 1,
  'po may`': 1,
  'po"': 1,
  'po`': 1,
  'puoi`': 1,
  'puồj': 1,
  'ph`o': 1,
  'ph0`': 1,
  'pha^n': 1,
  'phan^': 1,
  'phân': 1,
  rack: 1,
  'ráçk': 1,
  'rai\'': 1,
  're rack': 1,
  'rẻ racḱ': 1,
  's0ck k0n me': 1,
  selit: 1,
  sip: 1,
  skm: 1,
  sock: 1,
  socl: 1,
  'ßµ́': 1,
  'ßµô¡': 1,
  'ßµồ¡': 1,
  'ßµồ¡¯': 1,
  'ßµồ¿': 1,
  'ßµồi': 1,
  'ßµồï': 1,
  'ßµồi¯': 1,
  'ßµôî': 1,
  'ßµồî': 1,
  'ßố': 1,
  'ßuoi': 1,
  'ßuoj': 1,
  'ßuoj`': 1,
  'ßuom': 1,
  'ßuồi': 1,
  'ßựa': 1,
  'ßướm': 1,
  'sua?': 1,
  'suc vat': 1,
  tbc: 1,
  tbs: 1,
  'tien su': 1,
  'tuoi? io`n': 1,
  'tynh trug`': 1,
  'thang fo': 1,
  'thang pho': 1,
  'thang` fo': 1,
  'thoi ken': 1,
  'thủ zâm': 1,
  'thu? za^m': 1,
  tr1nh: 1,
  trlnh: 1,
  'tro\'': 1,
  'tro"': 1,
  trym: 1,
  trynh: 1,
  'våi': 1,
  vkc: 1,
  vkl: 1,
  vl: 1,
  'vú': 1,
  'vu\'': 1,
  xl: 1,
  'zá¡': 1,
  zaj: 1,
  'záj': 1,
  'zaj\'': 1,
  'zú': 1,
  'an_ca.c': 1,
  'anc.ac': 1,
  'ăn c.ặc': 1,
  'ăn.cặc': 1,
  'ba_ma.y': 1,
  'bà m.ày': 1,
  'ba m.ày': 1,
  'bà.may': 1,
  'ba.mày': 1,
  'bàm.ày': 1,
  'bac_h.o': 1,
  'ba.may': 1,
  'ban_d.am': 1,
  'ban_ho.a': 1,
  'banda.m': 1,
  'ba.nhoa': 1,
  'bán.hoa': 1,
  'bo_ma.y': 1,
  'bo.may': 1,
  'bon_ch.o': 1,
  'bon_kh.on_nan': 1,
  'bonc.ho': 1,
  'bonk.honnan': 1,
  'bre.ast': 1,
  'buc.ac': 1,
  'bu.ồi': 1,
  'buo.m': 1,
  'b.ướm': 1,
  'cạ.c': 1,
  'cặ.c': 1,
  'cai_bu.oi': 1,
  'cai_ch.im': 1,
  'cai_c.u': 1,
  'cai_lo.n': 1,
  'caib.uoi': 1,
  'caic.him': 1,
  'ca.icu': 1,
  'cail.on': 1,
  'ch.im': 1,
  'chi.m_to': 1,
  'chi.mto': 1,
  'cho_ch.et': 1,
  'c.ho_kin': 1,
  'cho.chet': 1,
  'chok.in': 1,
  'con_c.ho': 1,
  'c.on_cu': 1,
  'c.on_cu_cac': 1,
  'con_cu_to_tu.ong': 1,
  'c.on_di': 1,
  'con_die.m': 1,
  'con_ph.o': 1,
  'conc.ho': 1,
  'con.cu': 1,
  'con.cucac': 1,
  'concuto.tuong': 1,
  'co.ndi': 1,
  'condie.m': 1,
  'cong.hoa': 1,
  'cong.san': 1,
  'conl.on': 1,
  'conp.ho': 1,
  'cs.an': 1,
  'c.ụ': 1,
  'cu_ca.c': 1,
  'cu_m.ay': 1,
  'cu_t.o': 1,
  'cuc_ca.c': 1,
  'cuc_c.ut': 1,
  'cu.cac': 1,
  'cucca.c': 1,
  'cuc.cut': 1,
  'cu.ho': 1,
  'cu.may': 1,
  'cu.nt': 1,
  'cuo.ng_dam': 1,
  'cuon.g_hiep': 1,
  'cuon.gdam': 1,
  'cuo.nghiep': 1,
  'cut.o': 1,
  'dâ.m': 1,
  'da.n_chu': 1,
  'dan.chu': 1,
  'da.ng_c_s': 1,
  'da.ng_cong_san': 1,
  'dang_cong.san': 1,
  'da.ng_cs': 1,
  'da.ng_tien_tri': 1,
  'dan.g_tientri': 1,
  'dang.congsan': 1,
  'dang.cs': 1,
  'dang.tien_tri': 1,
  'da.ngtientri': 1,
  'điế.m': 1,
  'di.s_me': 1,
  'di.sme': 1,
  'dị.t': 1,
  'đí.t': 1,
  'd.it_bo': 1,
  'di.t_con_cu': 1,
  'dit_co.n_me': 1,
  'dit_c.oncu': 1,
  'dit_con.me': 1,
  'd.it_cu': 1,
  'dit_cu_m.ay': 1,
  'dit_m.e': 1,
  'dit_o.ng': 1,
  'dit.ba': 1,
  'd.itbo': 1,
  'dit.me': 1,
  'ditm.e': 1,
  'ditm.emay': 1,
  'dito.ng': 1,
  'doco.ncho': 1,
  'do.khon': 1,
  'd.rug': 1,
  'du_m.a': 1,
  'd.ục': 1,
  'du.ma': 1,
  'du.me': 1,
  'gai_b.an_hoa': 1,
  'gai_die.m': 1,
  'gaiban.hoa': 1,
  'gaid.iem': 1,
  'h.am_hiep': 1,
  'hamh.iep': 1,
  'ha.nh_kinh': 1,
  'ha.nhkinh': 1,
  'hiế.p': 1,
  'hiep_da.m': 1,
  'hiepda.m': 1,
  'ho_chi_mi.nh': 1,
  'hồ_chí_m.inh': 1,
  'ho_chim.inh': 1,
  'hochi_m.inh': 1,
  'hochi.minh': 1,
  'i.ả': 1,
  'ỉ.a': 1,
  'k.hốn': 1,
  'kho.n_nan': 1,
  'kho.nnan': 1,
  'khu.ng_bo': 1,
  'kh.ungbo': 1,
  'ki.ep': 1,
  'ki.ép': 1,
  'kiế.p': 1,
  'la.m_tinh': 1,
  'lam.tinh': 1,
  'lie.m_cac': 1,
  'lie.mcac': 1,
  'l.òn': 1,
  'lợ.n': 1,
  'lo.n_to': 1,
  'lo.ng_lon': 1,
  'lo.nglon': 1,
  'lo.nto': 1,
  'lu_ch.o': 1,
  'lu_k.hon': 1,
  'luc.ho': 1,
  'luk.hon': 1,
  'mau_k.inh': 1,
  'm.au_lon': 1,
  'mauki.nh': 1,
  'mau.lon': 1,
  'm.ẹ': 1,
  'm.e_kiep': 1,
  'me_m.ay': 1,
  'me.kiep': 1,
  'me.may': 1,
  'mi.e': 1,
  'moha.met': 1,
  'mua_da.m': 1,
  'mua.dam': 1,
  'mu.t_cac': 1,
  'mu.tbuoi': 1,
  'mut.cac': 1,
  'na.ke': 1,
  'ngu.yen_ai_quoc': 1,
  'nguy.en_aiquoc': 1,
  'nguyen.ai_quoc': 1,
  'nguyen.aiquoc': 1,
  'nguyenaiq.uoc': 1,
  'ong_m.ay': 1,
  'ongm.ay': 1,
  'pim.p': 1,
  'sin.h_duc': 1,
  'sin.hduc': 1,
  'sl.ut': 1,
  'so_lo.n': 1,
  's.olon': 1,
  'su_bo_ma.y': 1,
  'subo.may': 1,
  'th.ang_cho': 1,
  'than.gcho': 1,
  'tie.n_su': 1,
  'tien.su': 1,
  'tinh_du.c': 1,
  'tin.hduc': 1,
  'to_s.u': 1,
  'to.su': 1,
  'v_co.ng': 1,
  'vai_da.i': 1,
  'v.ai_leu': 1,
  'v.ai_lin': 1,
  'va.i_lon': 1,
  'vaida.i': 1,
  'va.ileu': 1,
  'vaili.n': 1,
  'va.ilon': 1,
  'vco.ng': 1,
  'viet_co.ng': 1,
  'cổ l.oa': 1,
  'vạn x.uân': 1,
  'thà.nh hồ': 1,
  'tha.nh ho': 1,
  'vua đi.nh': 1,
  'vu.a lê': 1,
  'h.oa lư': 1,
  'cố .đô huế': 1,
  '1.ồn': 1,
  '1ồ.n': 1,
  '1.0n': 1,
  '1.0`n': 1,
  '1`0.n': 1,
  '_ba.cho_': 1,
  '_bac.ho_': 1,
  '_b.acho_': 1,
  'ba.c_ho': 1,
  'b.ac_ho': 1,
  'b.ác hồ': 1,
  'bá.c hồ': 1,
  'b4.c hồ': 1,
  'b4c h.ồ': 1,
  'b\'.4c hồ': 1,
  'b\'4.c hồ': 1,
  'b4\'.c hồ': 1,
  'ba.c h0': 1,
  'b.ac h0': 1,
  'bac h.0': 1,
  'b.itch': 1,
  'bit.ch': 1,
  'bi.tch': 1,
  'bu.oi': 1,
  'b.uoi`': 1,
  'b.u0`i': 1,
  'bu.0`i': 1,
  'congs.an': 1,
  'co.ng san': 1,
  'cong. san': 1,
  'con.g san': 1,
  'cộn.g sản': 1,
  'co.ng_san': 1,
  'con.gsan': 1,
  'cuh.o': 1,
  'c.uh0': 1,
  'cuh.0': 1,
  'cu.h0': 1,
  'cu_h.o': 1,
  'cu_.ho': 1,
  'c.ụ hồ': 1,
  'cụ h.ồ': 1,
  'c_a._c': 1,
  'c4.c': 1,
  'c.4c': 1,
  'ca.c.': 1,
  'c.ac.': 1,
  'că.c.': 1,
  'c.ăc.': 1,
  'c.ặc': 1,
  'cav.e': 1,
  'ca.ve': 1,
  'c.ave': 1,
  'c.ứt': 1,
  'd.1t': 1,
  'd1.t': 1,
  'da.i\'': 1,
  'd.ai\'': 1,
  'd.ái': 1,
  'đá.i': 1,
  'đ.ái': 1,
  'd.âm': 1,
  'dam.n': 1,
  'dc.m': 1,
  'đc.m': 1,
  'đ.ĩ': 1,
  'đ.i~': 1,
  'd.ĩ': 1,
  'd.i~': 1,
  'd.i.t': 1,
  'đ.i.t': 1,
  'đị.t': 1,
  'đ.ịt': 1,
  'd.is': 1,
  'đi.s': 1,
  'd.it': 1,
  'đi.ếm': 1,
  'd.m': 1,
  'đ.m': 1,
  'dm.m': 1,
  'đm.m': 1,
  'đ.cm': 1,
  'đcm.m': 1,
  'dk.m': 1,
  'đk.m': 1,
  'd.cm': 1,
  'dk.mm': 1,
  'đk.mm': 1,
  'đ.ụ': 1,
  'đ.u.': 1,
  'f.uck': 1,
  'fu.ck': 1,
  'f_u._c_k': 1,
  'f_u_c._k': 1,
  'g4m.emaster': 1,
  'g4me.m4ster': 1,
  'g4me_ma.ster': 1,
  'g4me_m4s.ter': 1,
  'g4.me*master': 1,
  'g4m.e*m4ster': 1,
  'ga.memaster': 1,
  'gam.e_master': 1,
  '[game].master': 1,
  'game*m.aster': 1,
  'game[m.aster]': 1,
  'g.m': 1,
  '[g].m': 1,
  'g.[m]': 1,
  'g_.m': 1,
  'g*.m': 1,
  'hồ chí m.inh': 1,
  'hồ c.hí minh': 1,
  'hồ chí mi.nh': 1,
  'hồ ch.í minh': 1,
  'h.ồ chí minh': 1,
  'hoch.iminh': 1,
  'ho_ch.i_minh': 1,
  'ho c.hi minh': 1,
  'hi.ếp': 1,
  'l.o`n': 1,
  'lo.n`': 1,
  'l.on`': 1,
  'lồ.n': 1,
  'l.ôn': 1,
  'lô.n': 1,
  'l.ồn': 1,
  'm.k': 1,
  'nông đứ.c mạnh': 1,
  'nông .đức mạnh': 1,
  'nongduc.manh': 1,
  'nong.ducmanh': 1,
  'pen.is': 1,
  'pe.nis': 1,
  'phạ.m văn đồng': 1,
  'phạm vă.n đồng': 1,
  'phamvand.ong': 1,
  'pham.vandong': 1,
  'ph.ò': 1,
  'ph.o`': 1,
  'rap.e': 1,
  'ra.pe': 1,
  's.ex': 1,
  'se.x': 1,
  'sh1.t': 1,
  'sh.it': 1,
  'tổ.ng bí thư': 1,
  'tổng b.í thư': 1,
  'tongb.ithu': 1,
  'tong b.i thu': 1,
  'vietc.ong': 1,
  'vietcon.g': 1,
  'viet c.ong': 1,
  'vi.et cong': 1,
  'việt c.ông': 1,
  'việ.t cộng': 1,
  'việt c.ộng': 1,
  'lì.n': 1,
  'l.ìn': 1,
  'li.`n': 1,
  'li`.n': 1,
  'th.ủ dâm': 1,
  'thủ dâ.m': 1,
  'th.ủ dâ.m': 1,
  '!ồ..n': 1,
  '£.j.n`': 1,
  '£.ô`n': 1,
  '£ô.ñ': 1,
  '£.ồn': 1,
  '£.ồñ': 1,
  '₫.éo': 1,
  '₫.iṭ': 1,
  '₫y.t': 1,
  'y.t.': 1,
  '¶).¡t': 1,
  '¶).ị†': 1,
  '¶_ồ.ñ': 1,
  '¶_ơ.ñ': 1,
  '¶.ồñ': 1,
  '†.¡ñ': 1,
  '†.€̀': 1,
  '†.ổ': 1,
  '1.o`n': 1,
  '1o.n': 1,
  '1.ôn': 1,
  'a(n c.ac': 1,
  'a.m vat': 1,
  'an b.uoi': 1,
  'an k.ut': 1,
  'an k.uz': 1,
  'a.n loz': 1,
  'an no.^n': 1,
  'äñ.£0ñ': 1,
  'an.loz': 1,
  'ăn bu.oi': 1,
  'b.µ́': 1,
  'bµ0.m': 1,
  'bµ.ồi': 1,
  'b.0 cu': 1,
  'b.0 ku': 1,
  'b.3`': 1,
  'b.à': 1,
  'b.a`': 1,
  'bí.m': 1,
  'b.kl': 1,
  'bó c.u': 1,
  'bo k.u': 1,
  'b.ó ku': 1,
  'b.o^\'': 1,
  'b.u\'': 1,
  'b.u b': 1,
  'b.u\' b': 1,
  'bu b.u0j': 1,
  'bu b.uoi': 1,
  'bu b.uoj': 1,
  'bu l.ol': 1,
  'bu\' l.ol': 1,
  'bu lo.z': 1,
  'bu\' lo.z': 1,
  'bu.0^j': 1,
  'bu.0+m': 1,
  'b.u0i': 1,
  'bu.0j': 1,
  'bu.0j`': 1,
  'bu0.j`': 1,
  'b.u0m': 1,
  'bu.0\'m': 1,
  'b.u0z`': 1,
  'bu.bu0¡': 1,
  'bub.uoj': 1,
  'bu.o^i': 1,
  'bu.o^j`': 1,
  'bu.o^\'m': 1,
  'bu.o^y`': 1,
  'bu.oi^': 1,
  'bu.oi`': 1,
  'bu.oj': 1,
  'b.uoj`': 1,
  'bu.om': 1,
  'bu.o\'m': 1,
  'bu.ôi': 1,
  'b.uôì': 1,
  'b.uồi': 1,
  'bu.ôj': 1,
  'bu.ồj': 1,
  'bu.ồy': 1,
  'buớ.m': 1,
  'bư.ớm': 1,
  'bư.m': 1,
  'bv.s': 1,
  'by.m': 1,
  'bý.m': 1,
  'c0.n dy~': 1,
  'c0n f.0`': 1,
  'c.0n m3': 1,
  'c0.n me': 1,
  'c0n m.ẹ': 1,
  'c0.n pho': 1,
  'c0nch.0': 1,
  'c0n.g s4n': 1,
  'c4.v3': 1,
  'c4.ve': 1,
  'c.a.c': 1,
  'c.ac': 1,
  'c.ạc': 1,
  'c.ạ̈c': 1,
  'cai d.is': 1,
  'c.ai\' dis': 1,
  'cái d.is': 1,
  'cai dk.m': 1,
  'c.ai\' loz': 1,
  'cailo.z': 1,
  'caj di.s': 1,
  'caj dj.jt me': 1,
  'ca.j dkm': 1,
  'c.aj loz': 1,
  'caj lo.zl': 1,
  'ca.j…đị†': 1,
  'ca.k': 1,
  'ca.m iồn': 1,
  'ca.v3': 1,
  'că.c': 1,
  'cặ.ç': 1,
  'ç.ăç': 1,
  'c.ăk': 1,
  'cặ.k': 1,
  'c.ec.': 1,
  'çh.ÿm': 1,
  'c.l': 1,
  'c.on': 1,
  'ço.ñ': 1,
  'co.n cac': 1,
  'çøn ç.hǿ': 1,
  'c.on ch0': 1,
  'c.on di~': 1,
  'co.n di~': 1,
  'con die.m': 1,
  'co.n fò': 1,
  'co.n fo`': 1,
  'con i.on`': 1,
  'co.n m3': 1,
  'con m.e': 1,
  'co.n mẹ': 1,
  'cong sa.n': 1,
  'çu.+t\'': 1,
  'cu0n.g da^m': 1,
  'c.uc\'': 1,
  'cuc g.a`': 1,
  'ç.ứ†': 1,
  'ch.0́': 1,
  'ch.0\'\'': 1,
  'c.h0\'': 1,
  'ch0 g.he dis': 1,
  'ch0 su.a': 1,
  'ch.0.': 1,
  'ch.0\'a': 1,
  'ch.ém': 1,
  'ch.et': 1,
  'chi.m': 1,
  'chj.m': 1,
  'ch.ó': 1,
  'ch.o\'': 1,
  'cho ko.n bu\'': 1,
  'ch.o"': 1,
  'ch.ui': 1,
  'ch.uj': 1,
  'ch.uj?': 1,
  'ch.uj~': 1,
  'ch.uym': 1,
  'c.hửi..': 1,
  'ch.ym': 1,
  'd.!t': 1,
  'd!.t': 1,
  'd!.tl': 1,
  'd.yt': 1,
  'd.¥¶¯': 1,
  'd†c.m': 1,
  'd.0g': 1,
  'd.1~': 1,
  'dá.¡': 1,
  'd.aj': 1,
  'd.áj': 1,
  'da.j\'': 1,
  'da.mn': 1,
  'dang ha.ng': 1,
  'dạn.g háng': 1,
  'de.0': 1,
  'd.e0\'': 1,
  'de.0"': 1,
  'd.e0`': 1,
  'de.0~': 1,
  'd.ek': 1,
  'de.k\'': 1,
  'de.o': 1,
  'd.e\'o': 1,
  'd.eó': 1,
  'd.éo': 1,
  'de.o\'': 1,
  'd.eo': 1,
  'de.o\' ia?': 1,
  'de.o kut\'': 1,
  'd.eo"': 1,
  'd.et m3': 1,
  'd.et. me.': 1,
  'd.ey the\'': 1,
  'd.-ĩ': 1,
  'd.i.s': 1,
  'di.s m.e.': 1,
  'd.ï§': 1,
  'd.i†': 1,
  'd.ị†': 1,
  'd.ï†': 1,
  'di.en': 1,
  'd-i.ếm': 1,
  'd.iit': 1,
  'd.ïs': 1,
  'd.is\'': 1,
  'dis c0n m.e': 1,
  'dis c.0n mje': 1,
  'dis co.0n me': 1,
  'di.s cu': 1,
  'dis k0.n me': 1,
  'd.is k.u': 1,
  'di.s m.e': 1,
  'd.is m.e…': 1,
  'di.s.': 1,
  'd.is.': 1,
  'di.sd': 1,
  'dis.me': 1,
  'dis.s m3': 1,
  'dis.s me': 1,
  'd.isss': 1,
  'd.i\'t': 1,
  'di.x': 1,
  'di.z': 1,
  'd.z': 1,
  'd.j': 1,
  'd.j~': 1,
  'd.j†': 1,
  'dj.e^m\'': 1,
  'dj.e^\'m': 1,
  'dj.em': 1,
  'dj.em\'': 1,
  'd.jf': 1,
  'd.jit': 1,
  'd.jj~': 1,
  'djj.t': 1,
  'dj.s': 1,
  'd.jx': 1,
  'd.jz': 1,
  'd.k': 1,
  'd.k.': 1,
  'd.lt': 1,
  'do.et.': 1,
  'd.ú': 1,
  'd.ụ': 1,
  'd.u m3': 1,
  'du m.a': 1,
  'du m.á': 1,
  'du m.e maj`': 1,
  'd.u.': 1,
  'd.u. me.': 1,
  'du` mo.a\' an kut\'': 1,
  'du.k.': 1,
  'duon.g vat': 1,
  'd.uyt': 1,
  'du.yt': 1,
  'd.ÿ\u0018 ḿ\u0003': 1,
  'd.y.t': 1,
  'd.y`n': 1,
  'd.y~': 1,
  'dy~ de.o\' daj traj': 1,
  'd.ys': 1,
  'dys m.je': 1,
  'dy.t\'': 1,
  'd.yt\'': 1,
  'dyt b.uoj ': 1,
  'dyt c.0n m3': 1,
  'dỵt c0.n me': 1,
  'dyt cai i0.ng c0ng l0z': 1,
  'dy.t dyt': 1,
  'dyt k0.an': 1,
  'dyt k.0n m3': 1,
  'd.yt kon me': 1,
  'dyt kon m.e kaj\'\' loz`': 1,
  'dyt k.on me sock': 1,
  'dy.t ku.': 1,
  'dyt l0.z': 1,
  'dy.t m': 1,
  'd.yt m3': 1,
  'dyt m.3 an kuz': 1,
  'dyt m.e': 1,
  'd.yt me': 1,
  'dyt m.e nung l0zl': 1,
  'dyt m.e thagfo`': 1,
  'dyt .me.': 1,
  'dy.t mje': 1,
  'đ.!†': 1,
  'đ.¡§': 1,
  'đ.¡†': 1,
  'đ.¡̣†': 1,
  'đ.¡•t': 1,
  'đ.¡̣t': 1,
  'đ¥.†': 1,
  'đ.¥̣†': 1,
  'đ.¥t': 1,
  'đ¥̣.t': 1,
  'đ€́.ø': 1,
  'đ.µ': 1,
  'đ.µ̣': 1,
  'đµ̣. møª́': 1,
  'đµ́.†': 1,
  'đ†ç.m': 1,
  'đả.ng': 1,
  'đ.é0': 1,
  'đe.ó': 1,
  'đ.éo': 1,
  'đ.ï': 1,
  'đĩ đ.ựç': 1,
  'đị̈.†': 1,
  'đ.i†': 1,
  'đ.ị†': 1,
  'đi†çâ.ñañh': 1,
  'đi†m.ẹ': 1,
  'đi.ên': 1,
  'đ.iĩ': 1,
  'đ.is': 1,
  'đị.s': 1,
  'đ.is mẹ': 1,
  'đ.it': 1,
  'đ.it m3.': 1,
  'đi.t mẹ': 1,
  'đ.ịt me': 1,
  'đ.ịt mẹ': 1,
  'đ.ịt.': 1,
  'địt. đ.ỳn': 1,
  'đ.ịt...': 1,
  'đ.iz': 1,
  'đ.î†̣': 1,
  'đị̂.†': 1,
  'đ.ị̂†…mẹ': 1,
  'đ.ị̂t': 1,
  'đ.j̃': 1,
  'đ.j†': 1,
  'đ.jếm': 1,
  'đjế.m ': 1,
  'đj.t': 1,
  'đ.j̣t': 1,
  'đk.lm': 1,
  'đl.t': 1,
  'đ.u': 1,
  'đ.ụ mẹ': 1,
  'đ.ỹ': 1,
  'đ.ÿ§': 1,
  'đy.†': 1,
  'đ.ÿ†': 1,
  'đỵ̈.†': 1,
  'đ.y†': 1,
  'đỵ† k.ụ': 1,
  'đ.ỵ̈† m€̣': 1,
  'đ.ys…': 1,
  'đ.yt': 1,
  'đ.ỵt': 1,
  'đ.ÿt': 1,
  'đ.yṭ mẹ': 1,
  'đ.yt me.': 1,
  'đy.t.': 1,
  'đ.yz': 1,
  'f`.o`': 1,
  'ƒµ¢.¶«': 1,
  'fµ.ck': 1,
  'ƒµ.ck': 1,
  'ƒµ.çk': 1,
  'f.0': 1,
  'ƒ.0': 1,
  'ƒ.0ƒ': 1,
  'f.ho`': 1,
  'f.o': 1,
  'f.ö̀': 1,
  'f.ø̀': 1,
  'ƒ.o': 1,
  'ƒ.ò': 1,
  'ƒ.ø̀': 1,
  'f.ò': 1,
  'ƒ.o`': 1,
  'f.o`': 1,
  'f.oo`': 1,
  'ƒu.c¶«': 1,
  'ƒu.ck': 1,
  'ƒü.çk': 1,
  'fu.uck': 1,
  'gh.e?': 1,
  'gie? ra.ch\'': 1,
  'ha.m~ ion': 1,
  'h.am~ loz': 1,
  'ham~ lo.zl': 1,
  'ha.m~ lozn`': 1,
  'ha.mloz': 1,
  'hc.m': 1,
  'hi.3p': 1,
  'hi.3\'p': 1,
  'hi.e\'p': 1,
  'hie.p\'': 1,
  'h.iếp': 1,
  'hiê.p\'': 1,
  'hj.ep': 1,
  'h.l`': 1,
  'ho ch.i minh': 1,
  'i.tnh.au': 1,
  'i^0.n': 1,
  'i.0^k`': 1,
  'i.0`n': 1,
  'i.0`n`': 1,
  'i0.n': 1,
  'i.0n`': 1,
  'i.0z': 1,
  'i.ạ': 1,
  'i.o^`n': 1,
  'i.o^-n': 1,
  'i.o^n': 1,
  'i.o^n`': 1,
  'io.^n`': 1,
  'i.o^ng': 1,
  'i.o`n': 1,
  'io.`n': 1,
  'i.on': 1,
  'io.n`': 1,
  'io.n` me': 1,
  'io.n`. dis': 1,
  'i.oz': 1,
  'i.oz`': 1,
  'io.z`': 1,
  'iô.n': 1,
  'i.ồn': 1,
  'iồ.ñ': 1,
  'i.ồñ': 1,
  'iô.n`': 1,
  'iô.ng': 1,
  'ị.t': 1,
  'j.a?': 1,
  'k.0n': 1,
  'k0.n cac': 1,
  'k0.n ch0': 1,
  'k0n c.h0 an cuc\'': 1,
  'k0n m.0e. maj': 1,
  'k0n m.3': 1,
  'k0n m.e': 1,
  'k0n m.e maj': 1,
  'k3 m.3': 1,
  'k4.v3': 1,
  'k4.ve': 1,
  'kaj d.yt me': 1,
  'k.aj\' dyt. me': 1,
  'ka.k': 1,
  'k.at ku': 1,
  'ka.v3': 1,
  'ka.ve': 1,
  'k.ăc': 1,
  'k.ặc': 1,
  'k.ặç': 1,
  'k.it\'': 1,
  'k.lm': 1,
  'k.on': 1,
  'ko.n dkm': 1,
  'ko.n ch0\'': 1,
  'k.on cho\'': 1,
  'k.on dj?': 1,
  'ko.n dy~': 1,
  'ko.n f0': 1,
  'k.on kac': 1,
  'kon k.ak': 1,
  'ko.n ky~': 1,
  'k.on m3': 1,
  'kon m.e': 1,
  'ko.n mẹ': 1,
  'kote.x': 1,
  'k.u': 1,
  'k.ụ': 1,
  'k.u*\'t': 1,
  'ku.+t\'': 1,
  'k.uc\'': 1,
  'k.uc kut': 1,
  'k.ut': 1,
  'k.ut\'': 1,
  'ku.t ch0': 1,
  'ku.t het': 1,
  'k.ut nat': 1,
  'k.uz': 1,
  'k.uz\'': 1,
  'k.ứ†': 1,
  'kứ.†…çhó': 1,
  'k.ưt\'': 1,
  'k.ưt́': 1,
  'k.ứt': 1,
  'ky.nh nguye^t.': 1,
  'kh.ìn': 1,
  'kh.jn`': 1,
  'kho.viion': 1,
  'l do.g': 1,
  'l t.o': 1,
  'l.`': 1,
  'l.0^n`': 1,
  'l0.^z`': 1,
  'l.0`z': 1,
  'l0.n': 1,
  'l0o.n': 1,
  'l0.x': 1,
  'l.0z': 1,
  'l0.z`': 1,
  'l0z` me.j': 1,
  'l0.zl': 1,
  'l0.zl`': 1,
  'l0.zn': 1,
  'l0.zn`': 1,
  'l0.zz': 1,
  'la li.em': 1,
  'la ph.o`': 1,
  'la.m` fo`': 1,
  'li3.m': 1,
  'l.i3\'m': 1,
  'lie^m: lolz` m.ek lolz`': 1,
  'li.e\'m': 1,
  'lie.m\'': 1,
  'lie.m i0n ch0': 1,
  'li\'.m': 1,
  'lí.m': 1,
  'li.n`': 1,
  'l.jn': 1,
  'lj.n`': 1,
  'l.m': 1,
  'l.o^`n': 1,
  'l.o^lz`': 1,
  'l.o^n': 1,
  'l.o^n`': 1,
  'l.o^z': 1,
  'l.o^z`': 1,
  'lo^z.n`': 1,
  'lo.`n': 1,
  'l.o+i`': 1,
  'lo.0^n`': 1,
  'lo.0n`': 1,
  'lo.iz': 1,
  'l.ol': 1,
  'lo.lz': 1,
  'lo.n': 1,
  'l.ön': 1,
  'lo.n\'': 1,
  'lo.on': 1,
  'loo.n`': 1,
  'lo.z': 1,
  'l.öz': 1,
  'lo.z`': 1,
  'l.ozl': 1,
  'lo.zl`': 1,
  'lo.zn': 1,
  'l.ô`n': 1,
  'lô.lz': 1,
  'l.ôñ': 1,
  'l.ôñ̀': 1,
  'lồ.ñ': 1,
  'lô.ǹ': 1,
  'lô.n`': 1,
  'l.ồnz': 1,
  'l.ồz': 1,
  'lu.`n': 1,
  'lu~ d.0g': 1,
  'lu~ re ra.ck:': 1,
  'lu~d.og': 1,
  'lũ…dog h.úp…máu': 1,
  'lua ti.nh': 1,
  'lu.n`': 1,
  'luoj~ tat\' va.`o dau` buoj`': 1,
  'lz.0`': 1,
  'lz.0n`': 1,
  'lz.o`': 1,
  'lz.o`l': 1,
  'lz.ol': 1,
  'lz.ol`': 1,
  'lz.ồn': 1,
  'm€̣ m.aj`': 1,
  'm.0m~': 1,
  'm.3': 1,
  'm3 ma.i': 1,
  'm.a(t. loz': 1,
  'ma.u\' io`n': 1,
  'm.au\' ion': 1,
  'ma.u l': 1,
  'm.au l0z': 1,
  'ma.u lol': 1,
  'm.au loz': 1,
  'ma.u non`': 1,
  'm.ay`': 1,
  'm.e': 1,
  'm.ẹ̈': 1,
  'm.e chu.ng maj': 1,
  'm.e m.ai': 1,
  'm.e m.aj': 1,
  'me. ma.j`': 1,
  'me.t loz': 1,
  'm.i': 1,
  'm.ịe': 1,
  'mi.e.': 1,
  'm.je': 1,
  'm.l': 1,
  'm.l`': 1,
  'mo.^m loz': 1,
  'm.õm': 1,
  'mo.m~': 1,
  'mo.m~ dog lu~ ch0': 1,
  'm.ú†': 1,
  'm.ut': 1,
  'mú.t': 1,
  'm.ut\'': 1,
  'm.ut bi0i': 1,
  'mut b.u0j': 1,
  'm.ut ku': 1,
  'm.ut\' lz0n`': 1,
  'ñ.§ü': 1,
  'ñ.gậm…ßµồ¡': 1,
  'ni.ém': 1,
  'nj.n`': 1,
  'n.o^n`': 1,
  'n.o`n': 1,
  'no.n': 1,
  'n.on^`': 1,
  'no.n`': 1,
  'n.ôn': 1,
  'n.ồn': 1,
  'n.ồñ': 1,
  'ñ.ồñ': 1,
  'nồ.n': 1,
  'ñ.ôǹ': 1,
  'nồ.z': 1,
  'n.u*ng\'': 1,
  'nu.n`': 1,
  'nu.ng*\' loz`': 1,
  'nứ.ng': 1,
  'ng.u': 1,
  'n.h0n`': 1,
  'nh.a` may`': 1,
  'n.ho^n`': 1,
  'nh.u cac': 1,
  'n.huc̣…': 1,
  'nh.uk': 1,
  'p.3`': 1,
  'p.à': 1,
  'p.a`': 1,
  'pa` m.ay`': 1,
  'playk.u': 1,
  'pó c.u': 1,
  'po k.u': 1,
  'pó k.u': 1,
  'po ma.y`': 1,
  'p.o"': 1,
  'p.o`': 1,
  'p.uoi`': 1,
  'pu.ồj': 1,
  'ph.`o': 1,
  'p.h0`': 1,
  'ph.a^n': 1,
  'ph.an^': 1,
  'ph.ân': 1,
  'p.ho`': 1,
  'ra.ck': 1,
  'r.áçk': 1,
  'r.ai\'': 1,
  're r.ack': 1,
  'rẻ ra.cḱ': 1,
  's0.ck k0n me': 1,
  's.elit': 1,
  'sh.1t': 1,
  's.ip': 1,
  'sk.m': 1,
  'so.ck': 1,
  'so.cl': 1,
  'ß.µ́': 1,
  'ßµ.ô¡': 1,
  'ßµ.ồ¡': 1,
  'ßµ.ồ¡¯': 1,
  'ßµ.ồ¿': 1,
  'ß.µồi': 1,
  'ß.µồï': 1,
  'ß.µồi¯': 1,
  'ßµ.ôî': 1,
  'ß.µồî': 1,
  'ß.ố': 1,
  'ßu.oi': 1,
  'ßu.oj': 1,
  'ß.uoj`': 1,
  'ßu.om': 1,
  'ß.uồi': 1,
  'ß.ựa': 1,
  'ßư.ớm': 1,
  'su.a?': 1,
  's.uc vat': 1,
  't.bc': 1,
  't.bs': 1,
  'tie.n su': 1,
  'tu.oi? io`n': 1,
  'tynh tru.g`': 1,
  'tha.ng fo': 1,
  'thang p.ho': 1,
  'th.ang` fo': 1,
  'thoi k.en': 1,
  'thủ d.âm': 1,
  'thủ z.âm': 1,
  'thu.? za^m': 1,
  'tr1.nh': 1,
  'tri.nh': 1,
  'trj.nh': 1,
  't.rlnh': 1,
  'tr.o\'': 1,
  'tr.o"': 1,
  't.rym': 1,
  'try.nh': 1,
  'v.åi': 1,
  'v.kc': 1,
  'v.kl': 1,
  'v.l': 1,
  'v.ú': 1,
  'tư b.ản đỏ': 1,
  'tub.ando': 1,
  'tu b.an do': 1,
  'tư.bản': 1,
  'xã hội ch.ũ nghĩa': 1,
  'xahoic.hunghia': 1,
  'xã hoich.unghia': 1,
  'sã hội chũ ng.hĩa': 1,
  'xa hội chu.nghia': 1,
  'xahoi ch.ủ nghia': 1,
  'xahoic.hu nghĩa': 1,
  'tư bản ch.ủ nghĩa': 1,
  'tubanchu.nghia': 1,
  'tu ban ch.u nghia': 1,
  'tưbản.chủnghĩa': 1,
  'sã.hộichũnghĩa': 1,
  'xãhội.chũnghĩa': 1,
  an_ca_c: 1,
  anc_ac: 1,
  'ăn c_ặc': 1,
  'ăn_cặc': 1,
  ba_ma_y: 1,
  'bà m_ày': 1,
  'ba m_ày': 1,
  'bà_may': 1,
  'ba_mày': 1,
  'bàm_ày': 1,
  bac_h_o: 1,
  ba_may: 1,
  ban_d_am: 1,
  ban_ho_a: 1,
  banda_m: 1,
  ba_nhoa: 1,
  'bán_hoa': 1,
  bo_ma_y: 1,
  bo_may: 1,
  bon_ch_o: 1,
  bon_kh_on_nan: 1,
  bonc_ho: 1,
  bonk_honnan: 1,
  bre_ast: 1,
  buc_ac: 1,
  'bu_ồi': 1,
  buo_m: 1,
  'b_ướm': 1,
  c_san: 1,
  'cạ_c': 1,
  'cặ_c': 1,
  cai_bu_oi: 1,
  cai_ch_im: 1,
  cai_c_u: 1,
  cai_lo_n: 1,
  caib_uoi: 1,
  caic_him: 1,
  ca_icu: 1,
  cail_on: 1,
  ch_im: 1,
  chi_m_to: 1,
  chi_mto: 1,
  cho_ch_et: 1,
  c_ho_kin: 1,
  cho_chet: 1,
  chok_in: 1,
  con_c_ho: 1,
  c_on_cu: 1,
  c_on_cu_cac: 1,
  con_cu_to_tu_ong: 1,
  c_on_di: 1,
  con_die_m: 1,
  con_ph_o: 1,
  conc_ho: 1,
  con_cu: 1,
  con_cucac: 1,
  concuto_tuong: 1,
  co_ndi: 1,
  condie_m: 1,
  cong_hoa: 1,
  cong_san: 1,
  conl_on: 1,
  conp_ho: 1,
  cs_an: 1,
  'c_ụ': 1,
  cu_ca_c: 1,
  cu_m_ay: 1,
  cu_t_o: 1,
  cuc_ca_c: 1,
  cuc_c_ut: 1,
  cu_cac: 1,
  cucca_c: 1,
  cuc_cut: 1,
  cu_ho: 1,
  cu_may: 1,
  cu_nt: 1,
  cuo_ng_dam: 1,
  cuon_g_hiep: 1,
  cuon_gdam: 1,
  cuo_nghiep: 1,
  cut_o: 1,
  'dâ_m': 1,
  da_n_chu: 1,
  dan_chu: 1,
  da_ng_c_s: 1,
  da_ng_cong_san: 1,
  dang_cong_san: 1,
  da_ng_cs: 1,
  da_ng_tien_tri: 1,
  dan_g_tientri: 1,
  dang_congsan: 1,
  dang_cs: 1,
  dang_tien_tri: 1,
  da_ngtientri: 1,
  'điế_m': 1,
  di_s_me: 1,
  di_sme: 1,
  'dị_t': 1,
  'đí_t': 1,
  d_it_bo: 1,
  di_t_con_cu: 1,
  dit_co_n_me: 1,
  dit_c_oncu: 1,
  dit_con_me: 1,
  d_it_cu: 1,
  dit_cu_m_ay: 1,
  dit_m_e: 1,
  dit_o_ng: 1,
  dit_ba: 1,
  d_itbo: 1,
  dit_me: 1,
  ditm_e: 1,
  ditm_emay: 1,
  dito_ng: 1,
  doco_ncho: 1,
  do_khon: 1,
  d_rug: 1,
  du_m_a: 1,
  'd_ục': 1,
  du_ma: 1,
  du_me: 1,
  gai_b_an_hoa: 1,
  gai_die_m: 1,
  gaiban_hoa: 1,
  gaid_iem: 1,
  h_am_hiep: 1,
  hamh_iep: 1,
  ha_nh_kinh: 1,
  ha_nhkinh: 1,
  'hiế_p': 1,
  hiep_da_m: 1,
  hiepda_m: 1,
  ho_chi_mi_nh: 1,
  'hồ_chí_m_inh': 1,
  ho_chim_inh: 1,
  hochi_m_inh: 1,
  hochi_minh: 1,
  'i_ả': 1,
  'ỉ_a': 1,
  'k_hốn': 1,
  kho_n_nan: 1,
  kho_nnan: 1,
  khu_ng_bo: 1,
  kh_ungbo: 1,
  ki_ep: 1,
  'ki_ép': 1,
  'kiế_p': 1,
  la_m_tinh: 1,
  lam_tinh: 1,
  lie_m_cac: 1,
  lie_mcac: 1,
  'l_òn': 1,
  'lợ_n': 1,
  lo_n_to: 1,
  lo_ng_lon: 1,
  lo_nglon: 1,
  lo_nto: 1,
  lu_ch_o: 1,
  lu_k_hon: 1,
  luc_ho: 1,
  luk_hon: 1,
  mau_k_inh: 1,
  m_au_lon: 1,
  mauki_nh: 1,
  mau_lon: 1,
  'm_ẹ': 1,
  m_e_kiep: 1,
  me_m_ay: 1,
  me_kiep: 1,
  me_may: 1,
  mi_e: 1,
  moha_met: 1,
  mua_da_m: 1,
  mua_dam: 1,
  mu_t_cac: 1,
  mu_tbuoi: 1,
  mut_cac: 1,
  na_ke: 1,
  ngu_yen_ai_quoc: 1,
  nguy_en_aiquoc: 1,
  nguyen_ai_quoc: 1,
  nguyen_aiquoc: 1,
  nguyenaiq_uoc: 1,
  ong_m_ay: 1,
  ongm_ay: 1,
  pim_p: 1,
  s_h_i_t: 1,
  sin_h_duc: 1,
  sin_hduc: 1,
  sl_ut: 1,
  so_lo_n: 1,
  s_olon: 1,
  su_bo_ma_y: 1,
  subo_may: 1,
  th_ang_cho: 1,
  than_gcho: 1,
  tie_n_su: 1,
  tien_su: 1,
  tinh_du_c: 1,
  tin_hduc: 1,
  to_s_u: 1,
  to_su: 1,
  v_co_ng: 1,
  vai_da_i: 1,
  v_ai_leu: 1,
  v_ai_lin: 1,
  va_i_lon: 1,
  vaida_i: 1,
  va_ileu: 1,
  vaili_n: 1,
  va_ilon: 1,
  vco_ng: 1,
  viet_co_ng: 1,
  'vạn x_uân': 1,
  'thà_nh hồ': 1,
  'tha_nh ho': 1,
  'vua đi_nh': 1,
  'vu_a lê': 1,
  'h_oa lư': 1,
  'cố _đô huế': 1,
  '1_ồn': 1,
  '1ồ_n': 1,
  '1_0n': 1,
  '1_0`n': 1,
  '1`0_n': 1,
  _ba_cho_: 1,
  _bac_ho_: 1,
  _b_acho_: 1,
  ba_c_ho: 1,
  b_ac_ho: 1,
  'b_ác hồ': 1,
  'bá_c hồ': 1,
  'b4_c hồ': 1,
  'b4c h_ồ': 1,
  'b\'_4c hồ': 1,
  'b\'4_c hồ': 1,
  'b4\'_c hồ': 1,
  'ba_c h0': 1,
  'b_ac h0': 1,
  'bac h_0': 1,
  b_itch: 1,
  bit_ch: 1,
  bi_tch: 1,
  bu_oi: 1,
  'b_uoi`': 1,
  'b_u0`i': 1,
  'bu_0`i': 1,
  congs_an: 1,
  'co_ng san': 1,
  'cong_ san': 1,
  'con_g san': 1,
  'cộn_g sản': 1,
  co_ng_san: 1,
  con_gsan: 1,
  cuh_o: 1,
  c_uh0: 1,
  cuh_0: 1,
  cu_h0: 1,
  cu_h_o: 1,
  cu__ho: 1,
  'c_ụ hồ': 1,
  'cụ h_ồ': 1,
  c_a__c: 1,
  c4_c: 1,
  c_4c: 1,
  ca_c_: 1,
  c_ac_: 1,
  'că_c_': 1,
  'c_ăc_': 1,
  'c_ặc': 1,
  cav_e: 1,
  ca_ve: 1,
  c_ave: 1,
  'c_ứt': 1,
  d_1t: 1,
  d1_t: 1,
  'da_i\'': 1,
  'd_ai\'': 1,
  'd_ái': 1,
  'đá_i': 1,
  'đ_ái': 1,
  'd_âm': 1,
  dam_n: 1,
  dc_m: 1,
  'đc_m': 1,
  'đ_ĩ': 1,
  'đ_i~': 1,
  'd_ĩ': 1,
  'd_i~': 1,
  d_i_t: 1,
  'đ_i_t': 1,
  'đị_t': 1,
  'đ_ịt': 1,
  d_is: 1,
  'đi_s': 1,
  'đi_t': 1,
  d_it: 1,
  di_t: 1,
  'đi_ếm': 1,
  d_m: 1,
  'đ_m': 1,
  dm_m: 1,
  'đm_m': 1,
  'đ_cm': 1,
  'đcm_m': 1,
  dk_m: 1,
  'đk_m': 1,
  d_cm: 1,
  dk_mm: 1,
  'đk_mm': 1,
  'đ_ụ': 1,
  'đ_u_': 1,
  f_uck: 1,
  fu_ck: 1,
  f_u__c_k: 1,
  f_u_c__k: 1,
  g4m_emaster: 1,
  g4me_m4ster: 1,
  g4me_ma_ster: 1,
  g4me_m4s_ter: 1,
  'g4_me*master': 1,
  'g4m_e*m4ster': 1,
  ga_memaster: 1,
  gam_e_master: 1,
  '[game]_master': 1,
  'game*m_aster': 1,
  'game[m_aster]': 1,
  g_m: 1,
  '[g]_m': 1,
  'g_[m]': 1,
  g__m: 1,
  'g*_m': 1,
  'hồ chí m_inh': 1,
  'hồ c_hí minh': 1,
  'hồ chí mi_nh': 1,
  'hồ ch_í minh': 1,
  'h_ồ chí minh': 1,
  hoch_iminh: 1,
  ho_ch_i_minh: 1,
  'ho c_hi minh': 1,
  'hi_ếp': 1,
  'l_o`n': 1,
  'lo_n`': 1,
  'l_on`': 1,
  'lồ_n': 1,
  'l_ôn': 1,
  'lô_n': 1,
  'l_ồn': 1,
  m_k: 1,
  'nông đứ_c mạnh': 1,
  'nông _đức mạnh': 1,
  nongduc_manh: 1,
  nong_ducmanh: 1,
  pen_is: 1,
  pe_nis: 1,
  'phạ_m văn đồng': 1,
  'phạm vă_n đồng': 1,
  phamvand_ong: 1,
  pham_vandong: 1,
  'ph_ò': 1,
  'ph_o`': 1,
  rap_e: 1,
  ra_pe: 1,
  s_ex: 1,
  se_x: 1,
  sh1_t: 1,
  sh_it: 1,
  'tổ_ng bí thư': 1,
  'tổng b_í thư': 1,
  tongb_ithu: 1,
  'tong b_i thu': 1,
  vietc_ong: 1,
  vietcon_g: 1,
  'viet c_ong': 1,
  'vi_et cong': 1,
  'việt c_ông': 1,
  'việ_t cộng': 1,
  'việt c_ộng': 1,
  'lì_n': 1,
  'l_ìn': 1,
  'li_`n': 1,
  'li`_n': 1,
  'th_ủ dâm': 1,
  'thủ dâ_m': 1,
  'th_ủ dâ_m': 1,
  '!ồ__n': 1,
  '£_j_n`': 1,
  '£_ô`n': 1,
  '£ô_ñ': 1,
  '£_ồn': 1,
  '£_ồñ': 1,
  '₫_éo': 1,
  '₫_iṭ': 1,
  '₫y_t': 1,
  y_t_: 1,
  '¶)_¡t': 1,
  '¶)_ị†': 1,
  '¶_ồ_ñ': 1,
  '¶_ơ_ñ': 1,
  '¶_ồñ': 1,
  '†_¡ñ': 1,
  '†_€̀': 1,
  '†_ổ': 1,
  '1_o`n': 1,
  '1o_n': 1,
  '1_ôn': 1,
  'a(n c_ac': 1,
  'a_m vat': 1,
  'an b_uoi': 1,
  'an k_ut': 1,
  'an k_uz': 1,
  'a_n loz': 1,
  'an no_^n': 1,
  'äñ_£0ñ': 1,
  an_loz: 1,
  'ăn bu_oi': 1,
  'b_µ́': 1,
  'bµ0_m': 1,
  'bµ_ồi': 1,
  'b_0 cu': 1,
  'b_0 ku': 1,
  'b_3`': 1,
  'b_à': 1,
  'b_a`': 1,
  'bí_m': 1,
  b_kl: 1,
  'bó c_u': 1,
  'bo k_u': 1,
  'b_ó ku': 1,
  'b_o^\'': 1,
  'b_u\'': 1,
  'b_u b': 1,
  'b_u\' b': 1,
  'bu b_u0j': 1,
  'bu b_uoi': 1,
  'bu b_uoj': 1,
  'bu l_ol': 1,
  'bu\' l_ol': 1,
  'bu lo_z': 1,
  'bu\' lo_z': 1,
  'bu_0^j': 1,
  'bu_0+m': 1,
  b_u0i: 1,
  bu_0j: 1,
  'bu_0j`': 1,
  'bu0_j`': 1,
  b_u0m: 1,
  'bu_0\'m': 1,
  'b_u0z`': 1,
  'bu_bu0¡': 1,
  bub_uoj: 1,
  'bu_o^i': 1,
  'bu_o^j`': 1,
  'bu_o^\'m': 1,
  'bu_o^y`': 1,
  'bu_oi^': 1,
  'bu_oi`': 1,
  bu_oj: 1,
  'b_uoj`': 1,
  bu_om: 1,
  'bu_o\'m': 1,
  'bu_ôi': 1,
  'b_uôì': 1,
  'b_uồi': 1,
  'bu_ôj': 1,
  'bu_ồj': 1,
  'bu_ồy': 1,
  'buớ_m': 1,
  'bư_ớm': 1,
  'bư_m': 1,
  bv_s: 1,
  by_m: 1,
  'bý_m': 1,
  'c0_n dy~': 1,
  'c0n f_0`': 1,
  'c_0n m3': 1,
  'c0_n me': 1,
  'c0n m_ẹ': 1,
  'c0_n pho': 1,
  c0nch_0: 1,
  'c0n_g s4n': 1,
  c4_v3: 1,
  c4_ve: 1,
  c_ac: 1,
  'c_ạc': 1,
  'c_ạ̈c': 1,
  'cai d_is': 1,
  'c_ai\' dis': 1,
  'cái d_is': 1,
  'cai dk_m': 1,
  'c_ai\' loz': 1,
  cailo_z: 1,
  'caj di_s': 1,
  'caj dj_jt me': 1,
  'ca_j dkm': 1,
  'c_aj loz': 1,
  'caj lo_zl': 1,
  'ca_j…đị†': 1,
  ca_k: 1,
  'ca_m iồn': 1,
  ca_v3: 1,
  'că_c': 1,
  'cặ_ç': 1,
  'ç_ăç': 1,
  'c_ăk': 1,
  'cặ_k': 1,
  c_ec_: 1,
  'çh_ÿm': 1,
  c_l: 1,
  c_on: 1,
  'ço_ñ': 1,
  'co_n cac': 1,
  'çøn ç_hǿ': 1,
  'c_on ch0': 1,
  'c_on di~': 1,
  'co_n di~': 1,
  'con die_m': 1,
  'co_n fò': 1,
  'co_n fo`': 1,
  'con i_on`': 1,
  'co_n m3': 1,
  'con m_e': 1,
  'co_n mẹ': 1,
  'cong sa_n': 1,
  'çu_+t\'': 1,
  'cu0n_g da^m': 1,
  'c_uc\'': 1,
  'cuc g_a`': 1,
  'ç_ứ†': 1,
  'ch_0́': 1,
  'ch_0\'\'': 1,
  'c_h0\'': 1,
  'ch0 g_he dis': 1,
  'ch0 su_a': 1,
  ch_0_: 1,
  'ch_0\'a': 1,
  'ch_ém': 1,
  ch_et: 1,
  chi_m: 1,
  chj_m: 1,
  'ch_ó': 1,
  'ch_o\'': 1,
  'cho ko_n bu\'': 1,
  'ch_o"': 1,
  ch_ui: 1,
  ch_uj: 1,
  'ch_uj?': 1,
  'ch_uj~': 1,
  ch_uym: 1,
  'c_hửi__': 1,
  ch_ym: 1,
  'd_!t': 1,
  'd!_t': 1,
  'd!_tl': 1,
  d_yt: 1,
  'd_¥¶¯': 1,
  'd†c_m': 1,
  d_0g: 1,
  'd_1~': 1,
  'dá_¡': 1,
  d_aj: 1,
  'd_áj': 1,
  'da_j\'': 1,
  da_mn: 1,
  'dang ha_ng': 1,
  'dạn_g háng': 1,
  de_0: 1,
  'd_e0\'': 1,
  'de_0"': 1,
  'd_e0`': 1,
  'de_0~': 1,
  d_ek: 1,
  'de_k\'': 1,
  de_o: 1,
  'd_e\'o': 1,
  'd_eó': 1,
  'd_éo': 1,
  'de_o\'': 1,
  d_eo: 1,
  'de_o\' ia?': 1,
  'de_o kut\'': 1,
  'd_eo"': 1,
  'd_et m3': 1,
  'd_et_ me_': 1,
  'd_ey the\'': 1,
  'd_-ĩ': 1,
  d_i_s: 1,
  'd_ï§': 1,
  'd_i†': 1,
  'd_ị†': 1,
  'd_ï†': 1,
  di_en: 1,
  'd-i_ếm': 1,
  d_iit: 1,
  di_s: 1,
  'd_ïs': 1,
  'd_is\'': 1,
  'dis c0n m_e': 1,
  'dis c_0n mje': 1,
  'dis co_0n me': 1,
  'di_s cu': 1,
  'dis k0_n me': 1,
  'd_is k_u': 1,
  'di_s m_e': 1,
  'di_s m_e_': 1,
  'd_is m_e…': 1,
  di_s_: 1,
  d_is_: 1,
  di_sd: 1,
  dis_me: 1,
  'dis_s m3': 1,
  'dis_s me': 1,
  d_isss: 1,
  'd_i\'t': 1,
  di_x: 1,
  di_z: 1,
  d_z: 1,
  d_j: 1,
  'd_j~': 1,
  'd_j†': 1,
  'dj_e^m\'': 1,
  'dj_e^\'m': 1,
  dj_em: 1,
  'dj_em\'': 1,
  d_jf: 1,
  d_jit: 1,
  'd_jj~': 1,
  djj_t: 1,
  dj_s: 1,
  d_jx: 1,
  d_jz: 1,
  d_k: 1,
  d_k_: 1,
  d_lt: 1,
  do_et_: 1,
  'd_ú': 1,
  'd_ụ': 1,
  'd_u m3': 1,
  'du m_a': 1,
  'du m_á': 1,
  'du m_e maj`': 1,
  d_u_: 1,
  'd_u_ me_': 1,
  'du` mo_a\' an kut\'': 1,
  du_k_: 1,
  'duon_g vat': 1,
  d_uyt: 1,
  du_yt: 1,
  'd_ÿ\u0018 ḿ\u0003': 1,
  d_y_t: 1,
  'd_y`n': 1,
  'd_y~': 1,
  'dy~ de_o\' daj traj': 1,
  d_ys: 1,
  'dys m_je': 1,
  'dy_t\'': 1,
  dy_t: 1,
  'd_yt\'': 1,
  'dyt b_uoj ': 1,
  'dyt c_0n m3': 1,
  'dỵt c0_n me': 1,
  'dyt cai i0_ng c0ng l0z': 1,
  'dy_t dyt': 1,
  'dyt k0_an': 1,
  'dyt k_0n m3': 1,
  'd_yt kon me': 1,
  'dyt kon m_e kaj\'\' loz`': 1,
  'dyt k_on me sock': 1,
  'dy_t ku_': 1,
  'dyt l0_z': 1,
  'dy_t m': 1,
  'd_yt m3': 1,
  'dyt m_3 an kuz': 1,
  'dyt m_e': 1,
  'd_yt me': 1,
  'dyt m_e nung l0zl': 1,
  'dyt m_e thagfo`': 1,
  'dyt _me_': 1,
  'dy_t mje': 1,
  'đ_!†': 1,
  'đ_¡§': 1,
  'đ_¡†': 1,
  'đ_¡̣†': 1,
  'đ_¡•t': 1,
  'đ_¡̣t': 1,
  'đ¥_†': 1,
  'đ_¥̣†': 1,
  'đ_¥t': 1,
  'đ¥̣_t': 1,
  'đ€́_ø': 1,
  'đ_µ': 1,
  'đ_µ̣': 1,
  'đµ̣_ møª́': 1,
  'đµ́_†': 1,
  'đ†ç_m': 1,
  'đả_ng': 1,
  'đ_é0': 1,
  'đe_ó': 1,
  'đ_éo': 1,
  'đ_ï': 1,
  'đĩ đ_ựç': 1,
  'đ_i†': 1,
  'đ_ị†': 1,
  'đị̈_†': 1,
  'đi†çâ_ñañh': 1,
  'đi†m_ẹ': 1,
  'đi_ên': 1,
  'đ_iĩ': 1,
  'đ_is': 1,
  'đị_s': 1,
  'đ_is mẹ': 1,
  'đ_it': 1,
  'đ_it m3_': 1,
  'đi_t mẹ': 1,
  'đ_ịt me': 1,
  'đ_ịt mẹ': 1,
  'đ_ịt_': 1,
  'địt_ đ_ỳn': 1,
  'đ_ịt___': 1,
  'đ_iz': 1,
  'đ_î†̣': 1,
  'đị̂_†': 1,
  'đ_ị̂†…mẹ': 1,
  'đ_ị̂t': 1,
  'đ_j̃': 1,
  'đ_j†': 1,
  'đ_jếm': 1,
  'đjế_m ': 1,
  'đj_t': 1,
  'đ_j̣t': 1,
  'đk_lm': 1,
  'đl_t': 1,
  'đ_u': 1,
  'đ_ụ mẹ': 1,
  'đ_ỹ': 1,
  'đ_ÿ§': 1,
  'đy_†': 1,
  'đ_ÿ†': 1,
  'đỵ̈_†': 1,
  'đ_y†': 1,
  'đỵ† k_ụ': 1,
  'đ_ỵ̈† m€̣': 1,
  'đ_ys…': 1,
  'đ_yt': 1,
  'đ_ỵt': 1,
  'đ_ÿt': 1,
  'đ_yṭ mẹ': 1,
  'đ_yt me_': 1,
  'đy_t_': 1,
  'đ_yz': 1,
  'f`_o`': 1,
  'ƒµ¢_¶«': 1,
  'fµ_ck': 1,
  'ƒµ_ck': 1,
  'ƒµ_çk': 1,
  f_0: 1,
  'ƒ_0': 1,
  'ƒ_0ƒ': 1,
  'f_ho`': 1,
  f_o: 1,
  'f_ò': 1,
  'f_ö̀': 1,
  'f_ø̀': 1,
  'ƒ_o': 1,
  'ƒ_ò': 1,
  'ƒ_ø̀': 1,
  'f_o`': 1,
  'ƒ_o`': 1,
  'f_oo`': 1,
  'ƒu_c¶«': 1,
  'ƒu_ck': 1,
  'ƒü_çk': 1,
  fu_uck: 1,
  'gh_e?': 1,
  'gie? ra_ch\'': 1,
  'ha_m~ ion': 1,
  'h_am~ loz': 1,
  'ham~ lo_zl': 1,
  'ha_m~ lozn`': 1,
  ha_mloz: 1,
  hc_m: 1,
  hi_3p: 1,
  'hi_3\'p': 1,
  'hi_e\'p': 1,
  'hie_p\'': 1,
  'h_iếp': 1,
  'hiê_p\'': 1,
  hj_ep: 1,
  'h_l`': 1,
  'ho ch_i minh': 1,
  i_tnh_au: 1,
  'i^0_n': 1,
  'i_0^k`': 1,
  'i_0`n': 1,
  'i_0`n`': 1,
  i0_n: 1,
  'i_0n`': 1,
  i_0z: 1,
  'i_ạ': 1,
  'i_o^`n': 1,
  'i_o^n': 1,
  'i_o^-n': 1,
  'i_o^n`': 1,
  'io_^n`': 1,
  'i_o^ng': 1,
  'i_o`n': 1,
  'io_`n': 1,
  i_on: 1,
  'io_n`': 1,
  'io_n` me': 1,
  'io_n`_ dis': 1,
  i_oz: 1,
  'i_oz`': 1,
  'io_z`': 1,
  'iô_n': 1,
  'i_ồn': 1,
  'iồ_ñ': 1,
  'i_ồñ': 1,
  'iô_n`': 1,
  'iô_ng': 1,
  'ị_t': 1,
  'j_a?': 1,
  k_0n: 1,
  'k0_n cac': 1,
  'k0_n ch0': 1,
  'k0n c_h0 an cuc\'': 1,
  'k0n m_0e_ maj': 1,
  'k0n m_3': 1,
  'k0n m_e': 1,
  'k0n m_e maj': 1,
  'k3 m_3': 1,
  k4_v3: 1,
  k4_ve: 1,
  'kaj d_yt me': 1,
  'k_aj\' dyt_ me': 1,
  ka_k: 1,
  'k_at ku': 1,
  ka_v3: 1,
  ka_ve: 1,
  'k_ăc': 1,
  'k_ặc': 1,
  'k_ặç': 1,
  'k_it\'': 1,
  k_lm: 1,
  k_on: 1,
  'ko_n dkm': 1,
  'ko_n ch0\'': 1,
  'k_on cho\'': 1,
  'k_on dj?': 1,
  'ko_n dy~': 1,
  'ko_n f0': 1,
  'k_on kac': 1,
  'kon k_ak': 1,
  'ko_n ky~': 1,
  'k_on m3': 1,
  'kon m_e': 1,
  'ko_n mẹ': 1,
  kote_x: 1,
  k_u: 1,
  'k_ụ': 1,
  'k_u*\'t': 1,
  'ku_+t\'': 1,
  'k_uc\'': 1,
  'k_uc kut': 1,
  k_ut: 1,
  'k_ut\'': 1,
  'ku_t ch0': 1,
  'ku_t het': 1,
  'k_ut nat': 1,
  k_uz: 1,
  'k_uz\'': 1,
  'k_ứ†': 1,
  'kứ_†…çhó': 1,
  'k_ưt\'': 1,
  'k_ưt́': 1,
  'k_ứt': 1,
  'ky_nh nguye^t_': 1,
  'kh_ìn': 1,
  'kh_jn`': 1,
  kho_viion: 1,
  'l do_g': 1,
  'l t_o': 1,
  'l_`': 1,
  'l_0^n`': 1,
  'l0_^z`': 1,
  'l_0`z': 1,
  l0_n: 1,
  l0o_n: 1,
  l0_x: 1,
  l_0z: 1,
  'l0_z`': 1,
  'l0z` me_j': 1,
  l0_zl: 1,
  'l0_zl`': 1,
  l0_zn: 1,
  'l0_zn`': 1,
  l0_zz: 1,
  'la li_em': 1,
  'la ph_o`': 1,
  'la_m` fo`': 1,
  li3_m: 1,
  'l_i3\'m': 1,
  'lie^m: lolz` m_ek lolz`': 1,
  'li_e\'m': 1,
  'lie_m\'': 1,
  'lie_m i0n ch0': 1,
  'li\'_m': 1,
  'lí_m': 1,
  'li_n`': 1,
  l_jn: 1,
  'lj_n`': 1,
  l_m: 1,
  'l_o^`n': 1,
  'l_o^lz`': 1,
  'l_o^n': 1,
  'l_o^n`': 1,
  'l_o^z': 1,
  'l_o^z`': 1,
  'lo^z_n`': 1,
  'lo_`n': 1,
  'l_o+i`': 1,
  'lo_0^n`': 1,
  'lo_0n`': 1,
  lo_iz: 1,
  l_ol: 1,
  lo_lz: 1,
  lo_n: 1,
  'l_ön': 1,
  'lo_n\'': 1,
  lo_on: 1,
  'loo_n`': 1,
  lo_z: 1,
  'l_öz': 1,
  'lo_z`': 1,
  l_ozl: 1,
  'lo_zl`': 1,
  lo_zn: 1,
  'l_ô`n': 1,
  'lô_lz': 1,
  'l_ôñ': 1,
  'l_ôñ̀': 1,
  'lồ_ñ': 1,
  'lô_ǹ': 1,
  'lô_n`': 1,
  'l_ồnz': 1,
  'l_ồz': 1,
  'lu_`n': 1,
  'lu~ d_0g': 1,
  'lu~ re ra_ck:': 1,
  'lu~d_og': 1,
  'lũ…dog h_úp…máu': 1,
  'lua ti_nh': 1,
  'lu_n`': 1,
  'luoj~ tat\' va_`o dau` buoj`': 1,
  'lz_0`': 1,
  'lz_0n`': 1,
  'lz_o`': 1,
  'lz_o`l': 1,
  lz_ol: 1,
  'lz_ol`': 1,
  'lz_ồn': 1,
  'm€̣ m_aj`': 1,
  'm_0m~': 1,
  m_3: 1,
  'm3 ma_i': 1,
  'm_a(t_ loz': 1,
  'ma_u\' io`n': 1,
  'm_au\' ion': 1,
  'ma_u l': 1,
  'm_au l0z': 1,
  'ma_u lol': 1,
  'm_au loz': 1,
  'ma_u non`': 1,
  'm_ay`': 1,
  m_e: 1,
  'm_ẹ̈': 1,
  'm_e chu_ng maj': 1,
  'm_e m_ai': 1,
  'm_e m_aj': 1,
  'me_ ma_j`': 1,
  'me_t loz': 1,
  m_i: 1,
  'm_ịe': 1,
  mi_e_: 1,
  m_je: 1,
  m_l: 1,
  'm_l`': 1,
  'mo_^m loz': 1,
  'm_õm': 1,
  'mo_m~': 1,
  'mo_m~ dog lu~ ch0': 1,
  'm_ú†': 1,
  m_ut: 1,
  'mú_t': 1,
  'm_ut\'': 1,
  'm_ut bi0i': 1,
  'mut b_u0j': 1,
  'm_ut ku': 1,
  'm_ut\' lz0n`': 1,
  'ñ_§ü': 1,
  'ñ_gậm…ßµồ¡': 1,
  'ni_ém': 1,
  'nj_n`': 1,
  'n_o^n`': 1,
  'n_o`n': 1,
  no_n: 1,
  'n_on^`': 1,
  'no_n`': 1,
  'n_ôn': 1,
  'n_ồn': 1,
  'n_ồñ': 1,
  'ñ_ồñ': 1,
  'nồ_n': 1,
  'ñ_ôǹ': 1,
  'nồ_z': 1,
  'n_u*ng\'': 1,
  'nu_n`': 1,
  'nu_ng*\' loz`': 1,
  'nứ_ng': 1,
  ng_u: 1,
  'n_h0n`': 1,
  'nh_a` may`': 1,
  'n_ho^n`': 1,
  'nh_u cac': 1,
  'n_huc̣…': 1,
  nh_uk: 1,
  'p_3`': 1,
  'p_à': 1,
  'p_a`': 1,
  'pa` m_ay`': 1,
  playk_u: 1,
  'pó c_u': 1,
  'po k_u': 1,
  'pó k_u': 1,
  'po ma_y`': 1,
  'p_o"': 1,
  'p_o`': 1,
  'p_uoi`': 1,
  'pu_ồj': 1,
  'ph_`o': 1,
  'p_h0`': 1,
  'ph_a^n': 1,
  'ph_an^': 1,
  'ph_ân': 1,
  'p_ho`': 1,
  ra_ck: 1,
  'r_áçk': 1,
  'r_ai\'': 1,
  're r_ack': 1,
  'rẻ ra_cḱ': 1,
  's0_ck k0n me': 1,
  s_elit: 1,
  sh_1t: 1,
  s_ip: 1,
  sk_m: 1,
  so_ck: 1,
  so_cl: 1,
  'ß_µ́': 1,
  'ßµ_ô¡': 1,
  'ßµ_ồ¡': 1,
  'ßµ_ồ¡¯': 1,
  'ßµ_ồ¿': 1,
  'ß_µồi': 1,
  'ß_µồï': 1,
  'ß_µồi¯': 1,
  'ßµ_ôî': 1,
  'ß_µồî': 1,
  'ß_ố': 1,
  'ßu_oi': 1,
  'ßu_oj': 1,
  'ß_uoj`': 1,
  'ßu_om': 1,
  'ß_uồi': 1,
  'ß_ựa': 1,
  'ßư_ớm': 1,
  'su_a?': 1,
  's_uc vat': 1,
  t_bc: 1,
  t_bs: 1,
  'tie_n su': 1,
  'tu_oi? io`n': 1,
  'tynh tru_g`': 1,
  'tha_ng fo': 1,
  'thang p_ho': 1,
  'th_ang` fo': 1,
  'thoi k_en': 1,
  'thủ d_âm': 1,
  'thủ z_âm': 1,
  'thu_? za^m': 1,
  tr1_nh: 1,
  tri_nh: 1,
  trj_nh: 1,
  t_rlnh: 1,
  'tr_o\'': 1,
  'tr_o"': 1,
  t_rym: 1,
  try_nh: 1,
  'v_åi': 1,
  v_kc: 1,
  v_kl: 1,
  v_l: 1,
  'v_ú': 1,
  'tư b_ản đỏ': 1,
  tub_ando: 1,
  'tu b_an do': 1,
  'tư_bản': 1,
  'xã hội ch_ũ nghĩa': 1,
  xahoic_hunghia: 1,
  'xã hoich_unghia': 1,
  'sã hội chũ ng_hĩa': 1,
  'xa hội chu_nghia': 1,
  'xahoi ch_ủ nghia': 1,
  'xahoic_hu nghĩa': 1,
  'tư bản ch_ủ nghĩa': 1,
  tubanchu_nghia: 1,
  'tu ban ch_u nghia': 1,
  'tưbản_chủnghĩa': 1,
  'sã_hộichũnghĩa': 1,
  'xãhội_chũnghĩa': 1,
  'an-ca-c': 1,
  'anc-ac': 1,
  'ăn c-ặc': 1,
  'ăn-cặc': 1,
  'ba-ma-y': 1,
  'bà m-ày': 1,
  'ba m-ày': 1,
  'bà-may': 1,
  'ba-mày': 1,
  'bàm-ày': 1,
  'bac-h-o': 1,
  'ba-may': 1,
  'ban-d-am': 1,
  'ban-ho-a': 1,
  'banda-m': 1,
  'ba-nhoa': 1,
  'bán-hoa': 1,
  'bit-ch': 1,
  'bo-ma-y': 1,
  'bo-may': 1,
  'bon-ch-o': 1,
  'bon-kh-on-nan': 1,
  'bonc-ho': 1,
  'bonk-honnan': 1,
  'bre-ast': 1,
  'buc-ac': 1,
  'bu-oi': 1,
  'bu-ồi': 1,
  'buo-m': 1,
  'b-ướm': 1,
  'c-san': 1,
  'cạ-c': 1,
  'cặ-c': 1,
  'cai-bu-oi': 1,
  'cai-ch-im': 1,
  'cai-c-u': 1,
  'cai-lo-n': 1,
  'caib-uoi': 1,
  'caic-him': 1,
  'ca-icu': 1,
  'cail-on': 1,
  'ca-ve': 1,
  'ch-im': 1,
  'chi-m-to': 1,
  'chi-mto': 1,
  'ch-ó': 1,
  'cho-ch-et': 1,
  'c-ho-kin': 1,
  'cho-chet': 1,
  'chok-in': 1,
  'con-c-ho': 1,
  'c-on-cu': 1,
  'c-on-cu-cac': 1,
  'con-cu-to-tu-ong': 1,
  'c-on-di': 1,
  'con-die-m': 1,
  'con-ph-o': 1,
  'conc-ho': 1,
  'con-cu': 1,
  'con-cucac': 1,
  'concuto-tuong': 1,
  'co-ndi': 1,
  'condie-m': 1,
  'cong-hoa': 1,
  'co-ng-san': 1,
  'cong-san': 1,
  'conl-on': 1,
  'conp-ho': 1,
  'cs-an': 1,
  'c-ụ': 1,
  'cu-ca-c': 1,
  'cu-h-o': 1,
  'cu-m-ay': 1,
  'cu-t-o': 1,
  'cuc-ca-c': 1,
  'cuc-c-ut': 1,
  'cu-cac': 1,
  'cucca-c': 1,
  'cuc-cut': 1,
  'cu-ho': 1,
  'cu-may': 1,
  'cu-nt': 1,
  'cuo-ng-dam': 1,
  'cuon-g-hiep': 1,
  'cuon-gdam': 1,
  'cuo-nghiep': 1,
  'c-ứt': 1,
  'cut-o': 1,
  'đ-ái': 1,
  'dâ-m': 1,
  'da-n-chu': 1,
  'dan-chu': 1,
  'da-ng-c-s': 1,
  'da-ng-cong-san': 1,
  'dang-cong-san': 1,
  'da-ng-cs': 1,
  'da-ng-tien-tri': 1,
  'dan-g-tientri': 1,
  'dang-congsan': 1,
  'dang-cs': 1,
  'dang-tien-tri': 1,
  'da-ngtientri': 1,
  'dc-m': 1,
  'đc-m': 1,
  'đ-ĩ': 1,
  'điế-m': 1,
  'di-s-me': 1,
  'di-sme': 1,
  'd-it': 1,
  'dị-t': 1,
  'đí-t': 1,
  'đị-t': 1,
  'd-it-bo': 1,
  'di-t-con-cu': 1,
  'dit-co-n-me': 1,
  'dit-c-oncu': 1,
  'dit-con-me': 1,
  'd-it-cu': 1,
  'dit-cu-m-ay': 1,
  'dit-m-e': 1,
  'dit-o-ng': 1,
  'dit-ba': 1,
  'd-itbo': 1,
  'dit-me': 1,
  'ditm-e': 1,
  'ditm-emay': 1,
  'dito-ng': 1,
  'd-m': 1,
  'đ-m': 1,
  'doco-ncho': 1,
  'do-khon': 1,
  'd-rug': 1,
  'd-ụ': 1,
  'đ-ụ': 1,
  'du-m-a': 1,
  'd-ục': 1,
  'du-ma': 1,
  'du-me': 1,
  'fu-ck': 1,
  'gai-b-an-hoa': 1,
  'gai-die-m': 1,
  'gaiban-hoa': 1,
  'gaid-iem': 1,
  'h-am-hiep': 1,
  'hamh-iep': 1,
  'ha-nh-kinh': 1,
  'ha-nhkinh': 1,
  'hiế-p': 1,
  'hiep-da-m': 1,
  'hiepda-m': 1,
  'ho-chi-mi-nh': 1,
  'hồ-chí-m-inh': 1,
  'ho-chim-inh': 1,
  'hochi-m-inh': 1,
  'hochi-minh': 1,
  'i-ả': 1,
  'ỉ-a': 1,
  'k-hốn': 1,
  'kho-n-nan': 1,
  'kho-nnan': 1,
  'khu-ng-bo': 1,
  'kh-ungbo': 1,
  'ki-ep': 1,
  'ki-ép': 1,
  'kiế-p': 1,
  'la-m-tinh': 1,
  'lam-tinh': 1,
  'lie-m-cac': 1,
  'lie-mcac': 1,
  'lì-n': 1,
  'lo-n': 1,
  'l-òn': 1,
  'lồ-n': 1,
  'lợ-n': 1,
  'lo-n-to': 1,
  'lo-ng-lon': 1,
  'lo-nglon': 1,
  'lo-nto': 1,
  'lu-ch-o': 1,
  'lu-k-hon': 1,
  'luc-ho': 1,
  'luk-hon': 1,
  'mau-k-inh': 1,
  'm-au-lon': 1,
  'mauki-nh': 1,
  'mau-lon': 1,
  'm-ẹ': 1,
  'm-e-kiep': 1,
  'me-m-ay': 1,
  'me-kiep': 1,
  'me-may': 1,
  'mi-e': 1,
  'moha-met': 1,
  'mua-da-m': 1,
  'mua-dam': 1,
  'mu-t-cac': 1,
  'mu-tbuoi': 1,
  'mut-cac': 1,
  'na-ke': 1,
  'ngu-yen-ai-quoc': 1,
  'nguy-en-aiquoc': 1,
  'nguyen-ai-quoc': 1,
  'nguyen-aiquoc': 1,
  'nguyenaiq-uoc': 1,
  'ong-m-ay': 1,
  'ongm-ay': 1,
  'pen-is': 1,
  'ph-ò': 1,
  'pim-p': 1,
  'rap-e': 1,
  's-h-i-t': 1,
  'se-x': 1,
  'sh-it': 1,
  'sin-h-duc': 1,
  'sin-hduc': 1,
  'sl-ut': 1,
  'so-lo-n': 1,
  's-olon': 1,
  'su-bo-ma-y': 1,
  'subo-may': 1,
  'th-ang-cho': 1,
  'than-gcho': 1,
  'tie-n-su': 1,
  'tien-su': 1,
  'tinh-du-c': 1,
  'tin-hduc': 1,
  'to-s-u': 1,
  'to-su': 1,
  'v-co-ng': 1,
  'vai-da-i': 1,
  'v-ai-leu': 1,
  'v-ai-lin': 1,
  'va-i-lon': 1,
  'vaida-i': 1,
  'va-ileu': 1,
  'vaili-n': 1,
  'va-ilon': 1,
  'vco-ng': 1,
  'viet-co-ng': 1,
  '1-ồn': 1,
  '1ồ-n': 1,
  '1-0n': 1,
  '1-0`n': 1,
  '1`0-n': 1,
  '1-o`n': 1,
  '-ba-cho-': 1,
  '-bac-ho-': 1,
  '-b-acho-': 1,
  'ba-c-ho': 1,
  'b-ac-ho': 1,
  'b-ác hồ': 1,
  'bá-c hồ': 1,
  'b4-c hồ': 1,
  'b4c h-ồ': 1,
  'b\'-4c hồ': 1,
  'b\'4-c hồ': 1,
  'b4\'-c hồ': 1,
  'ba-c h0': 1,
  'b-ac h0': 1,
  'bac h-0': 1,
  'b-itch': 1,
  'bi-tch': 1,
  'bu-oi`': 1,
  'b-uoi`': 1,
  'b-uồi': 1,
  'b-u0`i': 1,
  'bu-0`i': 1,
  'congs-an': 1,
  'co-ng san': 1,
  'cong- san': 1,
  'con-g san': 1,
  'cộn-g sản': 1,
  'con-gsan': 1,
  'cuh-o': 1,
  'c-uh0': 1,
  'cuh-0': 1,
  'cu-h0': 1,
  'cu--ho': 1,
  'c-ụ hồ': 1,
  'cụ h-ồ': 1,
  'c-a--c': 1,
  'c4-c': 1,
  'c-4c': 1,
  'ca-c-': 1,
  'c-ac-': 1,
  'că-c-': 1,
  'c-ăc-': 1,
  'c-ặc': 1,
  'cav-e': 1,
  'c-ave': 1,
  'd-1t': 1,
  'd1-t': 1,
  'd-ai\'': 1,
  'da-i\'': 1,
  'd-ái': 1,
  'đá-i': 1,
  'd-âm': 1,
  'dam-n': 1,
  'đ-i~': 1,
  'd-i~': 1,
  'd-ĩ': 1,
  'd-i-t': 1,
  'đ-i-t': 1,
  'đ-ịt': 1,
  'd-is': 1,
  'đi-s': 1,
  'đ-is': 1,
  'đi-t': 1,
  'đ-it': 1,
  'di-t': 1,
  'đi-ếm': 1,
  'dm-m': 1,
  'đm-m': 1,
  'đ-cm': 1,
  'đcm-m': 1,
  'dk-m': 1,
  'đk-m': 1,
  'd-cm': 1,
  'dk-mm': 1,
  'đk-mm': 1,
  'đ-u-': 1,
  'f-uck': 1,
  'f-u--c-k': 1,
  'f-u-c--k': 1,
  'g4m-emaster': 1,
  'g4me-m4ster': 1,
  'g4me-ma-ster': 1,
  'g4me-m4s-ter': 1,
  'g4-me*master': 1,
  'g4m-e*m4ster': 1,
  'ga-memaster': 1,
  'gam-e-master': 1,
  '[game]-master': 1,
  'game*m-aster': 1,
  'game[m-aster]': 1,
  'g-m': 1,
  '[g]-m': 1,
  'g-[m]': 1,
  'g--m': 1,
  'g*-m': 1,
  'hồ chí m-inh': 1,
  'hồ c-hí minh': 1,
  'hồ chí mi-nh': 1,
  'hồ ch-í minh': 1,
  'h-ồ chí minh': 1,
  'hoch-iminh': 1,
  'ho-ch-i-minh': 1,
  'ho ch-i minh': 1,
  'ho c-hi minh': 1,
  'hi-ếp': 1,
  'lo-`n': 1,
  'l-o`n': 1,
  'lo-n`': 1,
  'l-on`': 1,
  'lô-n': 1,
  'l-ôn': 1,
  'l-ồn': 1,
  'm-k': 1,
  'nông đứ-c mạnh': 1,
  'nông -đức mạnh': 1,
  'nongduc-manh': 1,
  'nong-ducmanh': 1,
  'pe-nis': 1,
  'phạ-m văn đồng': 1,
  'phạm vă-n đồng': 1,
  'phamvand-ong': 1,
  'pham-vandong': 1,
  'p-ho`': 1,
  'ph-o`': 1,
  'ra-pe': 1,
  's-ex': 1,
  'sh-1t': 1,
  'sh1-t': 1,
  'tổ-ng bí thư': 1,
  'tổng b-í thư': 1,
  'tongb-ithu': 1,
  'tong b-i thu': 1,
  'vietcon-g': 1,
  'vietc-ong': 1,
  'viet c-ong': 1,
  'vi-et cong': 1,
  'việt c-ông': 1,
  'việ-t cộng': 1,
  'việt c-ộng': 1,
  'l-ìn': 1,
  'li-`n': 1,
  'li`-n': 1,
  'th-ủ dâm': 1,
  'thủ dâ-m': 1,
  'th-ủ dâ-m': 1,
  '!ồ--n': 1,
  '£-j-n`': 1,
  '£-ô`n': 1,
  '£ô-ñ': 1,
  '£-ồn': 1,
  '£-ồñ': 1,
  '₫-éo': 1,
  '₫-iṭ': 1,
  '₫y-t': 1,
  'y-t-': 1,
  '¶)-¡t': 1,
  '¶)-ị†': 1,
  '¶-ồ-ñ': 1,
  '¶-ơ-ñ': 1,
  '¶-ồñ': 1,
  '†-¡ñ': 1,
  '†-€̀': 1,
  '†-ổ': 1,
  '1o-n': 1,
  '1-ôn': 1,
  'a(n c-ac': 1,
  'a-m vat': 1,
  'an b-uoi': 1,
  'an k-ut': 1,
  'an k-uz': 1,
  'a-n loz': 1,
  'an no-^n': 1,
  'äñ-£0ñ': 1,
  'an-loz': 1,
  'ăn bu-oi': 1,
  'b-µ́': 1,
  'bµ0-m': 1,
  'bµ-ồi': 1,
  'b-0 cu': 1,
  'b-0 ku': 1,
  'b-3`': 1,
  'b-à': 1,
  'b-a`': 1,
  'bí-m': 1,
  'b-kl': 1,
  'bó c-u': 1,
  'bo k-u': 1,
  'b-ó ku': 1,
  'b-o^\'': 1,
  'b-u\'': 1,
  'b-u b': 1,
  'b-u\' b': 1,
  'bu b-u0j': 1,
  'bu b-uoi': 1,
  'bu b-uoj': 1,
  'bu l-ol': 1,
  'bu\' l-ol': 1,
  'bu lo-z': 1,
  'bu\' lo-z': 1,
  'bu-0^j': 1,
  'bu-0+m': 1,
  'b-u0i': 1,
  'bu-0j': 1,
  'bu-0j`': 1,
  'bu0-j`': 1,
  'b-u0m': 1,
  'bu-0\'m': 1,
  'b-u0z`': 1,
  'bu-bu0¡': 1,
  'bub-uoj': 1,
  'bu-o^i': 1,
  'bu-o^j`': 1,
  'bu-o^\'m': 1,
  'bu-o^y`': 1,
  'bu-oi^': 1,
  'bu-oj': 1,
  'b-uoj`': 1,
  'bu-om': 1,
  'bu-o\'m': 1,
  'bu-ôi': 1,
  'b-uôì': 1,
  'bu-ôj': 1,
  'bu-ồj': 1,
  'bu-ồy': 1,
  'buớ-m': 1,
  'bư-ớm': 1,
  'bư-m': 1,
  'bv-s': 1,
  'by-m': 1,
  'bý-m': 1,
  'c0-n dy~': 1,
  'c0n f-0`': 1,
  'c-0n m3': 1,
  'c0-n me': 1,
  'c0n m-ẹ': 1,
  'c0-n pho': 1,
  'c0nch-0': 1,
  'c0n-g s4n': 1,
  'c4-v3': 1,
  'c4-ve': 1,
  'c-a-c': 1,
  'c-ac': 1,
  'c-ạc': 1,
  'c-ạ̈c': 1,
  'cai d-is': 1,
  'c-ai\' dis': 1,
  'cái d-is': 1,
  'cai dk-m': 1,
  'c-ai\' loz': 1,
  'cailo-z': 1,
  'caj di-s': 1,
  'caj dj-jt me': 1,
  'ca-j dkm': 1,
  'c-aj loz': 1,
  'caj lo-zl': 1,
  'ca-j…đị†': 1,
  'ca-k': 1,
  'ca-m iồn': 1,
  'ca-v3': 1,
  'că-c': 1,
  'cặ-ç': 1,
  'ç-ăç': 1,
  'c-ăk': 1,
  'cặ-k': 1,
  'c-ec-': 1,
  'çh-ÿm': 1,
  'c-l': 1,
  'c-on': 1,
  'ço-ñ': 1,
  'co-n cac': 1,
  'çøn ç-hǿ': 1,
  'c-on ch0': 1,
  'c-on di~': 1,
  'co-n di~': 1,
  'con die-m': 1,
  'co-n fò': 1,
  'co-n fo`': 1,
  'con i-on`': 1,
  'co-n m3': 1,
  'con m-e': 1,
  'co-n mẹ': 1,
  'cong sa-n': 1,
  'çu-+t\'': 1,
  'cu0n-g da^m': 1,
  'c-uc\'': 1,
  'cuc g-a`': 1,
  'ç-ứ†': 1,
  'c-h0\'': 1,
  'ch-0́': 1,
  'ch-0\'\'': 1,
  'ch0 g-he dis': 1,
  'ch0 su-a': 1,
  'ch-0-': 1,
  'ch-0\'a': 1,
  'ch-ém': 1,
  'ch-et': 1,
  'chi-m': 1,
  'chj-m': 1,
  'ch-o\'': 1,
  'cho ko-n bu\'': 1,
  'ch-o"': 1,
  'ch-ui': 1,
  'ch-uj': 1,
  'ch-uj?': 1,
  'ch-uj~': 1,
  'ch-uym': 1,
  'c-hửi--': 1,
  'ch-ym': 1,
  'd-!t': 1,
  'd!-t': 1,
  'd!-tl': 1,
  'd-yt': 1,
  'd-¥¶¯': 1,
  'd†c-m': 1,
  'd-0g': 1,
  'd-1~': 1,
  'dá-¡': 1,
  'd-aj': 1,
  'd-áj': 1,
  'da-j\'': 1,
  'da-mn': 1,
  'dang ha-ng': 1,
  'dạn-g háng': 1,
  'de-0': 1,
  'd-e0\'': 1,
  'de-0"': 1,
  'd-e0`': 1,
  'de-0~': 1,
  'd-ek': 1,
  'de-k\'': 1,
  'de-o': 1,
  'd-e\'o': 1,
  'd-eó': 1,
  'd-éo': 1,
  'de-o\'': 1,
  'd-eo': 1,
  'de-o\' ia?': 1,
  'de-o kut\'': 1,
  'd-eo"': 1,
  'd-et m3': 1,
  'd-et- me-': 1,
  'd-ey the\'': 1,
  'd--ĩ': 1,
  'd-i-s': 1,
  'di-s m-e-': 1,
  'd-ï§': 1,
  'd-i†': 1,
  'd-ị†': 1,
  'd-ï†': 1,
  'di-en': 1,
  'd-i-ếm': 1,
  'd-iit': 1,
  'di-s': 1,
  'd-ïs': 1,
  'd-is\'': 1,
  'dis c0n m-e': 1,
  'dis c-0n mje': 1,
  'dis co-0n me': 1,
  'di-s cu': 1,
  'dis k0-n me': 1,
  'd-is k-u': 1,
  'di-s m-e': 1,
  'd-is m-e…': 1,
  'di-s-': 1,
  'd-is-': 1,
  'di-sd': 1,
  'dis-me': 1,
  'dis-s m3': 1,
  'dis-s me': 1,
  'd-isss': 1,
  'd-i\'t': 1,
  'di-x': 1,
  'di-z': 1,
  'd-z': 1,
  'd-j': 1,
  'd-j~': 1,
  'd-j†': 1,
  'dj-e^\'m': 1,
  'dj-e^m\'': 1,
  'dj-em': 1,
  'dj-em\'': 1,
  'd-jf': 1,
  'd-jit': 1,
  'd-jj~': 1,
  'djj-t': 1,
  'dj-s': 1,
  'd-jx': 1,
  'd-jz': 1,
  'd-k': 1,
  'd-k-': 1,
  'd-lt': 1,
  'do-et-': 1,
  'd-ú': 1,
  'd-u m3': 1,
  'du m-a': 1,
  'du m-á': 1,
  'du m-e maj`': 1,
  'd-u-': 1,
  'd-u- me-': 1,
  'du` mo-a\' an kut\'': 1,
  'du-k-': 1,
  'duon-g vat': 1,
  'd-uyt': 1,
  'du-yt': 1,
  'd-ÿ\u0018 ḿ\u0003': 1,
  'd-y-t': 1,
  'd-y`n': 1,
  'd-y~': 1,
  'dy~ de-o\' daj traj': 1,
  'd-ys': 1,
  'dys m-je': 1,
  'dy-t\'': 1,
  'dy-t': 1,
  'd-yt\'': 1,
  'dyt b-uoj ': 1,
  'dyt c-0n m3': 1,
  'dỵt c0-n me': 1,
  'dyt cai i0-ng c0ng l0z': 1,
  'dy-t dyt': 1,
  'dyt k0-an': 1,
  'dyt k-0n m3': 1,
  'd-yt kon me': 1,
  'dyt kon m-e kaj\'\' loz`': 1,
  'dyt k-on me sock': 1,
  'dy-t ku-': 1,
  'dyt l0-z': 1,
  'dy-t m': 1,
  'd-yt m3': 1,
  'dyt m-3 an kuz': 1,
  'dyt m-e': 1,
  'd-yt me': 1,
  'dyt m-e nung l0zl': 1,
  'dyt m-e thagfo`': 1,
  'dyt -me-': 1,
  'dy-t mje': 1,
  'đ-!†': 1,
  'đ-¡§': 1,
  'đ-¡†': 1,
  'đ-¡̣†': 1,
  'đ-¡•t': 1,
  'đ-¡̣t': 1,
  'đ¥-†': 1,
  'đ-¥̣†': 1,
  'đ-¥t': 1,
  'đ¥̣-t': 1,
  'đ€́-ø': 1,
  'đ-µ': 1,
  'đ-µ̣': 1,
  'đµ̣- møª́': 1,
  'đµ́-†': 1,
  'đ†ç-m': 1,
  'đả-ng': 1,
  'đ-é0': 1,
  'đe-ó': 1,
  'đ-éo': 1,
  'đ-ï': 1,
  'đĩ đ-ựç': 1,
  'đ-i†': 1,
  'đ-ị†': 1,
  'đị̈-†': 1,
  'đi†çâ-ñañh': 1,
  'đi†m-ẹ': 1,
  'đi-ên': 1,
  'đ-iĩ': 1,
  'đị-s': 1,
  'đ-is mẹ': 1,
  'đ-it m3-': 1,
  'đi-t mẹ': 1,
  'đ-ịt me': 1,
  'đ-ịt mẹ': 1,
  'đ-ịt-': 1,
  'địt- đ-ỳn': 1,
  'đ-ịt---': 1,
  'đ-iz': 1,
  'đ-î†̣': 1,
  'đị̂-†': 1,
  'đ-ị̂†…mẹ': 1,
  'đ-ị̂t': 1,
  'đ-j̃': 1,
  'đ-j†': 1,
  'đ-jếm': 1,
  'đjế-m ': 1,
  'đj-t': 1,
  'đ-j̣t': 1,
  'đk-lm': 1,
  'đl-t': 1,
  'đ-u': 1,
  'đ-ụ mẹ': 1,
  'đ-ỹ': 1,
  'đ-ÿ§': 1,
  'đy-†': 1,
  'đ-ÿ†': 1,
  'đỵ̈-†': 1,
  'đ-y†': 1,
  'đỵ† k-ụ': 1,
  'đ-ỵ̈† m€̣': 1,
  'đ-ys…': 1,
  'đ-yt': 1,
  'đ-ỵt': 1,
  'đ-ÿt': 1,
  'đ-yṭ mẹ': 1,
  'đ-yt me-': 1,
  'đy-t-': 1,
  'đ-yz': 1,
  'f`-o`': 1,
  'ƒµ¢-¶«': 1,
  'fµ-ck': 1,
  'ƒµ-ck': 1,
  'ƒµ-çk': 1,
  'f-0': 1,
  'ƒ-0': 1,
  'ƒ-0ƒ': 1,
  'f-ho`': 1,
  'f-o': 1,
  'f-ò': 1,
  'f-ö̀': 1,
  'f-ø̀': 1,
  'ƒ-o': 1,
  'ƒ-ò': 1,
  'ƒ-ø̀': 1,
  'f-o`': 1,
  'ƒ-o`': 1,
  'f-oo`': 1,
  'ƒu-c¶«': 1,
  'ƒu-ck': 1,
  'ƒü-çk': 1,
  'fu-uck': 1,
  'gh-e?': 1,
  'gie? ra-ch\'': 1,
  'ha-m~ ion': 1,
  'h-am~ loz': 1,
  'ham~ lo-zl': 1,
  'ha-m~ lozn`': 1,
  'ha-mloz': 1,
  'hc-m': 1,
  'hi-3p': 1,
  'hi-3\'p': 1,
  'hi-e\'p': 1,
  'hie-p\'': 1,
  'h-iếp': 1,
  'hiê-p\'': 1,
  'hj-ep': 1,
  'h-l`': 1,
  'i-tnh-au': 1,
  'i^0-n': 1,
  'i-0^k`': 1,
  'i-0`n': 1,
  'i-0`n`': 1,
  'i0-n': 1,
  'i-0n`': 1,
  'i-0z': 1,
  'i-ạ': 1,
  'i-o^`n': 1,
  'i-o^n': 1,
  'i-o^-n': 1,
  'i-o^n`': 1,
  'io-^n`': 1,
  'i-o^ng': 1,
  'i-o`n': 1,
  'io-`n': 1,
  'i-on': 1,
  'io-n`': 1,
  'io-n` me': 1,
  'io-n`- dis': 1,
  'i-oz': 1,
  'i-oz`': 1,
  'io-z`': 1,
  'iô-n': 1,
  'i-ồn': 1,
  'iồ-ñ': 1,
  'i-ồñ': 1,
  'iô-n`': 1,
  'iô-ng': 1,
  'ị-t': 1,
  'j-a?': 1,
  'k-0n': 1,
  'k0-n cac': 1,
  'k0-n ch0': 1,
  'k0n c-h0 an cuc\'': 1,
  'k0n m-0e- maj': 1,
  'k0n m-3': 1,
  'k0n m-e': 1,
  'k0n m-e maj': 1,
  'k3 m-3': 1,
  'k4-v3': 1,
  'k4-ve': 1,
  'kaj d-yt me': 1,
  'k-aj\' dyt- me': 1,
  'ka-k': 1,
  'k-at ku': 1,
  'ka-v3': 1,
  'ka-ve': 1,
  'k-ăc': 1,
  'k-ặc': 1,
  'k-ặç': 1,
  'k-it\'': 1,
  'k-lm': 1,
  'k-on': 1,
  'ko-n dkm': 1,
  'ko-n ch0\'': 1,
  'k-on cho\'': 1,
  'k-on dj?': 1,
  'ko-n dy~': 1,
  'ko-n f0': 1,
  'k-on kac': 1,
  'kon k-ak': 1,
  'ko-n ky~': 1,
  'k-on m3': 1,
  'kon m-e': 1,
  'ko-n mẹ': 1,
  'kote-x': 1,
  'k-u': 1,
  'k-ụ': 1,
  'k-u*\'t': 1,
  'ku-+t\'': 1,
  'k-uc\'': 1,
  'k-uc kut': 1,
  'k-ut': 1,
  'k-ut\'': 1,
  'ku-t ch0': 1,
  'ku-t het': 1,
  'k-ut nat': 1,
  'k-uz': 1,
  'k-uz\'': 1,
  'k-ứ†': 1,
  'kứ-†…çhó': 1,
  'k-ưt\'': 1,
  'k-ưt́': 1,
  'k-ứt': 1,
  'ky-nh nguye^t-': 1,
  'kh-ìn': 1,
  'kh-jn`': 1,
  'kho-viion': 1,
  'l do-g': 1,
  'l t-o': 1,
  'l-`': 1,
  'l-0^n`': 1,
  'l0-^z`': 1,
  'l-0`z': 1,
  'l0-n': 1,
  'l0o-n': 1,
  'l0-x': 1,
  'l-0z': 1,
  'l0-z`': 1,
  'l0z` me-j': 1,
  'l0-zl': 1,
  'l0-zl`': 1,
  'l0-zn': 1,
  'l0-zn`': 1,
  'l0-zz': 1,
  'la li-em': 1,
  'la ph-o`': 1,
  'la-m` fo`': 1,
  'li3-m': 1,
  'l-i3\'m': 1,
  'lie^m: lolz` m-ek lolz`': 1,
  'li-e\'m': 1,
  'lie-m\'': 1,
  'lie-m i0n ch0': 1,
  'li\'-m': 1,
  'lí-m': 1,
  'li-n`': 1,
  'l-jn': 1,
  'lj-n`': 1,
  'l-m': 1,
  'l-o^`n': 1,
  'l-o^lz`': 1,
  'l-o^n': 1,
  'l-o^n`': 1,
  'l-o^z': 1,
  'l-o^z`': 1,
  'lo^z-n`': 1,
  'l-o+i`': 1,
  'lo-0^n`': 1,
  'lo-0n`': 1,
  'lo-iz': 1,
  'l-ol': 1,
  'lo-lz': 1,
  'l-ön': 1,
  'lo-n\'': 1,
  'lo-on': 1,
  'loo-n`': 1,
  'lo-z': 1,
  'l-öz': 1,
  'lo-z`': 1,
  'l-ozl': 1,
  'lo-zl`': 1,
  'lo-zn': 1,
  'l-ô`n': 1,
  'lô-lz': 1,
  'l-ôñ': 1,
  'l-ôñ̀': 1,
  'lồ-ñ': 1,
  'lô-ǹ': 1,
  'lô-n`': 1,
  'l-ồnz': 1,
  'l-ồz': 1,
  'lu-`n': 1,
  'lu~ d-0g': 1,
  'lu~ re ra-ck:': 1,
  'lu~d-og': 1,
  'lũ…dog h-úp…máu': 1,
  'lua ti-nh': 1,
  'lu-n`': 1,
  'luoj~ tat\' va-`o dau` buoj`': 1,
  'lz-0`': 1,
  'lz-0n`': 1,
  'lz-o`': 1,
  'lz-o`l': 1,
  'lz-ol': 1,
  'lz-ol`': 1,
  'lz-ồn': 1,
  'm€̣ m-aj`': 1,
  'm-0m~': 1,
  'm-3': 1,
  'm3 ma-i': 1,
  'm-a(t- loz': 1,
  'ma-u\' io`n': 1,
  'm-au\' ion': 1,
  'ma-u l': 1,
  'm-au l0z': 1,
  'ma-u lol': 1,
  'm-au loz': 1,
  'ma-u non`': 1,
  'm-ay`': 1,
  'm-e': 1,
  'm-ẹ̈': 1,
  'm-e chu-ng maj': 1,
  'm-e m-ai': 1,
  'm-e m-aj': 1,
  'me- ma-j`': 1,
  'me-t loz': 1,
  'm-i': 1,
  'm-ịe': 1,
  'mi-e-': 1,
  'm-je': 1,
  'm-l': 1,
  'm-l`': 1,
  'mo-^m loz': 1,
  'm-õm': 1,
  'mo-m~': 1,
  'mo-m~ dog lu~ ch0': 1,
  'm-ú†': 1,
  'm-ut': 1,
  'mú-t': 1,
  'm-ut\'': 1,
  'm-ut bi0i': 1,
  'mut b-u0j': 1,
  'm-ut ku': 1,
  'm-ut\' lz0n`': 1,
  'ñ-§ü': 1,
  'ñ-gậm…ßµồ¡': 1,
  'ni-ém': 1,
  'nj-n`': 1,
  'n-o^n`': 1,
  'n-o`n': 1,
  'no-n': 1,
  'n-on^`': 1,
  'no-n`': 1,
  'n-ôn': 1,
  'n-ồn': 1,
  'n-ồñ': 1,
  'ñ-ồñ': 1,
  'nồ-n': 1,
  'ñ-ôǹ': 1,
  'nồ-z': 1,
  'n-u*ng\'': 1,
  'nu-n`': 1,
  'nu-ng*\' loz`': 1,
  'nứ-ng': 1,
  'ng-u': 1,
  'n-h0n`': 1,
  'nh-a` may`': 1,
  'n-ho^n`': 1,
  'nh-u cac': 1,
  'n-huc̣…': 1,
  'nh-uk': 1,
  'p-3`': 1,
  'p-à': 1,
  'p-a`': 1,
  'pa` m-ay`': 1,
  'playk-u': 1,
  'pó c-u': 1,
  'po k-u': 1,
  'pó k-u': 1,
  'po ma-y`': 1,
  'p-o"': 1,
  'p-o`': 1,
  'p-uoi`': 1,
  'pu-ồj': 1,
  'ph-`o': 1,
  'p-h0`': 1,
  'ph-a^n': 1,
  'ph-an^': 1,
  'ph-ân': 1,
  'ra-ck': 1,
  'r-áçk': 1,
  'r-ai\'': 1,
  're r-ack': 1,
  'rẻ ra-cḱ': 1,
  's0-ck k0n me': 1,
  's-elit': 1,
  's-ip': 1,
  'sk-m': 1,
  'so-ck': 1,
  'so-cl': 1,
  'ß-µ́': 1,
  'ßµ-ô¡': 1,
  'ßµ-ồ¡': 1,
  'ßµ-ồ¡¯': 1,
  'ßµ-ồ¿': 1,
  'ß-µồi': 1,
  'ß-µồï': 1,
  'ß-µồi¯': 1,
  'ßµ-ôî': 1,
  'ß-µồî': 1,
  'ß-ố': 1,
  'ßu-oi': 1,
  'ßu-oj': 1,
  'ß-uoj`': 1,
  'ßu-om': 1,
  'ß-uồi': 1,
  'ß-ựa': 1,
  'ßư-ớm': 1,
  'su-a?': 1,
  's-uc vat': 1,
  't-bc': 1,
  't-bs': 1,
  'tie-n su': 1,
  'tu-oi? io`n': 1,
  'tynh tru-g`': 1,
  'tha-ng fo': 1,
  'thang p-ho': 1,
  'th-ang` fo': 1,
  'thoi k-en': 1,
  'thủ d-âm': 1,
  'thủ z-âm': 1,
  'thu-? za^m': 1,
  'tr1-nh': 1,
  'tri-nh': 1,
  'trj-nh': 1,
  't-rlnh': 1,
  'tr-o\'': 1,
  'tr-o"': 1,
  't-rym': 1,
  'try-nh': 1,
  'v-åi': 1,
  'v-kc': 1,
  'v-kl': 1,
  'v-l': 1,
  'v-ú': 1,
  'tư b-ản đỏ': 1,
  'tub-ando': 1,
  'tu b-an do': 1,
  'tư-bản': 1,
  'xã hội ch-ũ nghĩa': 1,
  'xahoic-hunghia': 1,
  'xã hoich-unghia': 1,
  'sã hội chũ ng-hĩa': 1,
  'xa hội chu-nghia': 1,
  'xahoi ch-ủ nghia': 1,
  'xahoic-hu nghĩa': 1,
  'tư bản ch-ủ nghĩa': 1,
  'tubanchu-nghia': 1,
  'tu ban ch-u nghia': 1,
  'tưbản-chủnghĩa': 1,
  'sã-hộichũnghĩa': 1,
  'xãhội-chũnghĩa': 1,
  'an*ca*c': 1,
  'anc*ac': 1,
  'ăn c*ặc': 1,
  'ăn*cặc': 1,
  'ba*ma*y': 1,
  'bà m*ày': 1,
  'ba m*ày': 1,
  'bà*may': 1,
  'ba*mày': 1,
  'bàm*ày': 1,
  'bac*h*o': 1,
  'ba*may': 1,
  'ban*d*am': 1,
  'ban*ho*a': 1,
  'banda*m': 1,
  'ba*nhoa': 1,
  'bán*hoa': 1,
  'bit*ch': 1,
  'bo*ma*y': 1,
  'bo*may': 1,
  'bon*ch*o': 1,
  'bon*kh*on*nan': 1,
  'bonc*ho': 1,
  'bonk*honnan': 1,
  'bre*ast': 1,
  'buc*ac': 1,
  'bu*ồi': 1,
  'buo*m': 1,
  'b*ướm': 1,
  'c*san': 1,
  'cạ*c': 1,
  'cặ*c': 1,
  'cai*bu*oi': 1,
  'cai*ch*im': 1,
  'cai*c*u': 1,
  'cai*lo*n': 1,
  'caib*uoi': 1,
  'caic*him': 1,
  'ca*icu': 1,
  'cail*on': 1,
  'ca*ve': 1,
  'ch*im': 1,
  'chi*m*to': 1,
  'chi*mto': 1,
  'ch*ó': 1,
  'cho*ch*et': 1,
  'c*ho*kin': 1,
  'cho*chet': 1,
  'chok*in': 1,
  'con*c*ho': 1,
  'c*on*cu': 1,
  'c*on*cu*cac': 1,
  'con*cu*to*tu*ong': 1,
  'c*on*di': 1,
  'con*die*m': 1,
  'con*ph*o': 1,
  'conc*ho': 1,
  'con*cu': 1,
  'con*cucac': 1,
  'concuto*tuong': 1,
  'co*ndi': 1,
  'condie*m': 1,
  'cong*hoa': 1,
  'co*ng*san': 1,
  'cong*san': 1,
  'conl*on': 1,
  'conp*ho': 1,
  'cs*an': 1,
  'c*ụ': 1,
  'cu*ca*c': 1,
  'cu*m*ay': 1,
  'cu*t*o': 1,
  'cuc*ca*c': 1,
  'cuc*c*ut': 1,
  'cu*cac': 1,
  'cucca*c': 1,
  'cuc*cut': 1,
  'cu*ho': 1,
  'cu*may': 1,
  'cu*nt': 1,
  'cuo*ng*dam': 1,
  'cuon*g*hiep': 1,
  'cuon*gdam': 1,
  'cuo*nghiep': 1,
  'c*ứt': 1,
  'cut*o': 1,
  'đ*ái': 1,
  'dâ*m': 1,
  'da*n*chu': 1,
  'dan*chu': 1,
  'da*ng*c*s': 1,
  'da*ng*cong*san': 1,
  'dang*cong*san': 1,
  'da*ng*cs': 1,
  'da*ng*tien*tri': 1,
  'dan*g*tientri': 1,
  'dang*congsan': 1,
  'dang*cs': 1,
  'dang*tien*tri': 1,
  'da*ngtientri': 1,
  'dc*m': 1,
  'đc*m': 1,
  'đ*ĩ': 1,
  'điế*m': 1,
  'di*s*me': 1,
  'di*sme': 1,
  'd*it': 1,
  'dị*t': 1,
  'đí*t': 1,
  'đị*t': 1,
  'd*it*bo': 1,
  'di*t*con*cu': 1,
  'dit*co*n*me': 1,
  'dit*c*oncu': 1,
  'dit*con*me': 1,
  'd*it*cu': 1,
  'dit*cu*m*ay': 1,
  'dit*m*e': 1,
  'dit*o*ng': 1,
  'dit*ba': 1,
  'd*itbo': 1,
  'dit*me': 1,
  'ditm*e': 1,
  'ditm*emay': 1,
  'dito*ng': 1,
  'd*m': 1,
  'đ*m': 1,
  'doco*ncho': 1,
  'do*khon': 1,
  'd*rug': 1,
  'd*ụ': 1,
  'đ*ụ': 1,
  'du*m*a': 1,
  'd*ục': 1,
  'du*ma': 1,
  'du*me': 1,
  'fu*ck': 1,
  'gai*b*an*hoa': 1,
  'gai*die*m': 1,
  'gaiban*hoa': 1,
  'gaid*iem': 1,
  'h*am*hiep': 1,
  'hamh*iep': 1,
  'ha*nh*kinh': 1,
  'ha*nhkinh': 1,
  'hiế*p': 1,
  'hiep*da*m': 1,
  'hiepda*m': 1,
  'ho*chi*mi*nh': 1,
  'hồ*chí*m*inh': 1,
  'ho*chim*inh': 1,
  'hochi*m*inh': 1,
  'hochi*minh': 1,
  'i*ả': 1,
  'ỉ*a': 1,
  'k*hốn': 1,
  'kho*n*nan': 1,
  'kho*nnan': 1,
  'khu*ng*bo': 1,
  'kh*ungbo': 1,
  'ki*ep': 1,
  'ki*ép': 1,
  'kiế*p': 1,
  'la*m*tinh': 1,
  'lam*tinh': 1,
  'lie*m*cac': 1,
  'lie*mcac': 1,
  'lì*n': 1,
  'lo*n': 1,
  'l*òn': 1,
  'lồ*n': 1,
  'lợ*n': 1,
  'lo*n*to': 1,
  'lo*ng*lon': 1,
  'lo*nglon': 1,
  'lo*nto': 1,
  'lu*ch*o': 1,
  'lu*k*hon': 1,
  'luc*ho': 1,
  'luk*hon': 1,
  'mau*k*inh': 1,
  'm*au*lon': 1,
  'mauki*nh': 1,
  'mau*lon': 1,
  'm*ẹ': 1,
  'm*e*kiep': 1,
  'me*m*ay': 1,
  'me*kiep': 1,
  'me*may': 1,
  'mi*e': 1,
  'moha*met': 1,
  'mua*da*m': 1,
  'mua*dam': 1,
  'mu*t*cac': 1,
  'mu*tbuoi': 1,
  'mut*cac': 1,
  'na*ke': 1,
  'ngu*yen*ai*quoc': 1,
  'nguy*en*aiquoc': 1,
  'nguyen*ai*quoc': 1,
  'nguyen*aiquoc': 1,
  'nguyenaiq*uoc': 1,
  'ong*m*ay': 1,
  'ongm*ay': 1,
  'pen*is': 1,
  'ph*ò': 1,
  'pim*p': 1,
  'rap*e': 1,
  's*h*i*t': 1,
  'se*x': 1,
  'sh*it': 1,
  'sin*h*duc': 1,
  'sin*hduc': 1,
  'sl*ut': 1,
  'so*lo*n': 1,
  's*olon': 1,
  'su*bo*ma*y': 1,
  'subo*may': 1,
  'th*ang*cho': 1,
  'than*gcho': 1,
  'tie*n*su': 1,
  'tien*su': 1,
  'tinh*du*c': 1,
  'tin*hduc': 1,
  'to*s*u': 1,
  'to*su': 1,
  'v*co*ng': 1,
  'vai*da*i': 1,
  'v*ai*leu': 1,
  'v*ai*lin': 1,
  'va*i*lon': 1,
  'vaida*i': 1,
  'va*ileu': 1,
  'vaili*n': 1,
  'va*ilon': 1,
  'vco*ng': 1,
  'viet*co*ng': 1,
  'vietc*ong': 1,
  'thà*nh hồ': 1,
  'tha*nh ho': 1,
  'vua đi*nh': 1,
  'vu*a lê': 1,
  'h*oa lư': 1,
  'cố *đô huế': 1,
  '1*ồn': 1,
  '1ồ*n': 1,
  '1*0n': 1,
  '1*0`n': 1,
  '1`0*n': 1,
  '1*o`n': 1,
  '*ba*cho*': 1,
  '*bac*ho*': 1,
  '*b*acho*': 1,
  'ba*c*ho': 1,
  'b*ac*ho': 1,
  'b*ác hồ': 1,
  'bá*c hồ': 1,
  'b4*c hồ': 1,
  'b4c h*ồ': 1,
  'b\'*4c hồ': 1,
  'b\'4*c hồ': 1,
  'b4\'*c hồ': 1,
  'ba*c h0': 1,
  'b*ac h0': 1,
  'bac h*0': 1,
  'b*itch': 1,
  'bi*tch': 1,
  'bu*oi': 1,
  'bu*oi`': 1,
  'b*uoi`': 1,
  'b*uồi': 1,
  'b*u0`i': 1,
  'bu*0`i': 1,
  'congs*an': 1,
  'co*ng san': 1,
  'cong* san': 1,
  'con*g san': 1,
  'cộn*g sản': 1,
  'con*gsan': 1,
  'cuh*o': 1,
  'c*uh0': 1,
  'cuh*0': 1,
  'cu*h0': 1,
  'cu*h*o': 1,
  'cu**ho': 1,
  'c*ụ hồ': 1,
  'cụ h*ồ': 1,
  'c*a**c': 1,
  'c4*c': 1,
  'c*4c': 1,
  'ca*c*': 1,
  'c*ac*': 1,
  'că*c*': 1,
  'c*ăc*': 1,
  'c*ặc': 1,
  'cav*e': 1,
  'c*ave': 1,
  'd*1t': 1,
  'd1*t': 1,
  'd*ai\'': 1,
  'da*i\'': 1,
  'd*ái': 1,
  'đá*i': 1,
  'd*âm': 1,
  'dam*n': 1,
  'đ*i~': 1,
  'd*i~': 1,
  'd*ĩ': 1,
  'd*i*t': 1,
  'đ*i*t': 1,
  'đ*ịt': 1,
  'd*is': 1,
  'đi*s': 1,
  'đ*is': 1,
  'đi*t': 1,
  'đ*it': 1,
  'di*t': 1,
  'đi*ếm': 1,
  'dm*m': 1,
  'đm*m': 1,
  'đ*cm': 1,
  'đcm*m': 1,
  'dk*m': 1,
  'đk*m': 1,
  'd*cm': 1,
  'dk*mm': 1,
  'đk*mm': 1,
  'đ*u*': 1,
  'f*uck': 1,
  'f*u**c*k': 1,
  'f*u*c**k': 1,
  'g4m*emaster': 1,
  'g4me*m4ster': 1,
  'g4me*ma*ster': 1,
  'g4me*m4s*ter': 1,
  'g4*me*master': 1,
  'g4m*e*m4ster': 1,
  'ga*memaster': 1,
  'gam*e*master': 1,
  '[game]*master': 1,
  'game*m*aster': 1,
  'game[m*aster]': 1,
  'g*m': 1,
  '[g]*m': 1,
  'g*[m]': 1,
  'g**m': 1,
  'hồ chí m*inh': 1,
  'hồ c*hí minh': 1,
  'hồ chí mi*nh': 1,
  'hồ ch*í minh': 1,
  'h*ồ chí minh': 1,
  'hoch*iminh': 1,
  'ho*ch*i*minh': 1,
  'ho ch*i minh': 1,
  'ho c*hi minh': 1,
  'hi*ếp': 1,
  'lo*`n': 1,
  'l*o`n': 1,
  'lo*n`': 1,
  'l*on`': 1,
  'lô*n': 1,
  'l*ôn': 1,
  'l*ồn': 1,
  'm*k': 1,
  'nông đứ*c mạnh': 1,
  'nông *đức mạnh': 1,
  'nongduc*manh': 1,
  'nong*ducmanh': 1,
  'pe*nis': 1,
  'phạ*m văn đồng': 1,
  'phạm vă*n đồng': 1,
  'phamvand*ong': 1,
  'pham*vandong': 1,
  'p*ho`': 1,
  'ph*o`': 1,
  'ra*pe': 1,
  's*ex': 1,
  'sh*1t': 1,
  'sh1*t': 1,
  'tổ*ng bí thư': 1,
  'tổng b*í thư': 1,
  'tongb*ithu': 1,
  'tong b*i thu': 1,
  'vietcon*g': 1,
  'viet c*ong': 1,
  'vi*et cong': 1,
  'việt c*ông': 1,
  'việ*t cộng': 1,
  'việt c*ộng': 1,
  'l*ìn': 1,
  'li*`n': 1,
  'li`*n': 1,
  'th*ủ dâm': 1,
  'thủ dâ*m': 1,
  'th*ủ dâ*m': 1,
  '!ồ**n': 1,
  '£*j*n`': 1,
  '£*ô`n': 1,
  '£ô*ñ': 1,
  '£*ồn': 1,
  '£*ồñ': 1,
  '₫*éo': 1,
  '₫*iṭ': 1,
  '₫y*t': 1,
  'y*t*': 1,
  '¶)*¡t': 1,
  '¶)*ị†': 1,
  '¶*ồ*ñ': 1,
  '¶*ơ*ñ': 1,
  '¶*ồñ': 1,
  '†*¡ñ': 1,
  '†*€̀': 1,
  '†*ổ': 1,
  '1o*n': 1,
  '1*ôn': 1,
  'a(n c*ac': 1,
  'a*m vat': 1,
  'an b*uoi': 1,
  'an k*ut': 1,
  'an k*uz': 1,
  'a*n loz': 1,
  'an no*^n': 1,
  'äñ*£0ñ': 1,
  'an*loz': 1,
  'ăn bu*oi': 1,
  'b*µ́': 1,
  'bµ0*m': 1,
  'bµ*ồi': 1,
  'b*0 cu': 1,
  'b*0 ku': 1,
  'b*3`': 1,
  'b*à': 1,
  'b*a`': 1,
  'bí*m': 1,
  'b*kl': 1,
  'bó c*u': 1,
  'bo k*u': 1,
  'b*ó ku': 1,
  'b*o^\'': 1,
  'b*u\'': 1,
  'b*u b': 1,
  'b*u\' b': 1,
  'bu b*u0j': 1,
  'bu b*uoi': 1,
  'bu b*uoj': 1,
  'bu l*ol': 1,
  'bu\' l*ol': 1,
  'bu lo*z': 1,
  'bu\' lo*z': 1,
  'bu*0^j': 1,
  'bu*0+m': 1,
  'b*u0i': 1,
  'bu*0j': 1,
  'bu*0j`': 1,
  'bu0*j`': 1,
  'b*u0m': 1,
  'bu*0\'m': 1,
  'b*u0z`': 1,
  'bu*bu0¡': 1,
  'bub*uoj': 1,
  'bu*o^i': 1,
  'bu*o^j`': 1,
  'bu*o^\'m': 1,
  'bu*o^y`': 1,
  'bu*oi^': 1,
  'bu*oj': 1,
  'b*uoj`': 1,
  'bu*om': 1,
  'bu*o\'m': 1,
  'bu*ôi': 1,
  'b*uôì': 1,
  'bu*ôj': 1,
  'bu*ồj': 1,
  'bu*ồy': 1,
  'buớ*m': 1,
  'bư*ớm': 1,
  'bư*m': 1,
  'bv*s': 1,
  'by*m': 1,
  'bý*m': 1,
  'c0*n dy~': 1,
  'c0n f*0`': 1,
  'c*0n m3': 1,
  'c0*n me': 1,
  'c0n m*ẹ': 1,
  'c0*n pho': 1,
  'c0nch*0': 1,
  'c0n*g s4n': 1,
  'c4*v3': 1,
  'c4*ve': 1,
  'c*a*c': 1,
  'c*ac': 1,
  'c*ạc': 1,
  'c*ạ̈c': 1,
  'cai d*is': 1,
  'c*ai\' dis': 1,
  'cái d*is': 1,
  'cai dk*m': 1,
  'c*ai\' loz': 1,
  'cailo*z': 1,
  'caj di*s': 1,
  'caj dj*jt me': 1,
  'ca*j dkm': 1,
  'c*aj loz': 1,
  'caj lo*zl': 1,
  'ca*j…đị†': 1,
  'ca*k': 1,
  'ca*m iồn': 1,
  'ca*v3': 1,
  'că*c': 1,
  'cặ*ç': 1,
  'ç*ăç': 1,
  'c*ăk': 1,
  'cặ*k': 1,
  'c*ec*': 1,
  'çh*ÿm': 1,
  'c*l': 1,
  'c*on': 1,
  'ço*ñ': 1,
  'co*n cac': 1,
  'çøn ç*hǿ': 1,
  'c*on ch0': 1,
  'c*on di~': 1,
  'co*n di~': 1,
  'con die*m': 1,
  'co*n fò': 1,
  'co*n fo`': 1,
  'con i*on`': 1,
  'co*n m3': 1,
  'con m*e': 1,
  'co*n mẹ': 1,
  'cong sa*n': 1,
  'çu*+t\'': 1,
  'cu0n*g da^m': 1,
  'c*uc\'': 1,
  'cuc g*a`': 1,
  'ç*ứ†': 1,
  'c*h0\'': 1,
  'ch*0́': 1,
  'ch*0\'\'': 1,
  'ch0 g*he dis': 1,
  'ch0 su*a': 1,
  'ch*0*': 1,
  'ch*0\'a': 1,
  'ch*ém': 1,
  'ch*et': 1,
  'chi*m': 1,
  'chj*m': 1,
  'ch*o\'': 1,
  'cho ko*n bu\'': 1,
  'ch*o"': 1,
  'ch*ui': 1,
  'ch*uj': 1,
  'ch*uj?': 1,
  'ch*uj~': 1,
  'ch*uym': 1,
  'c*hửi**': 1,
  'ch*ym': 1,
  'd*!t': 1,
  'd!*t': 1,
  'd!*tl': 1,
  'd*yt': 1,
  'd*¥¶¯': 1,
  'd†c*m': 1,
  'd*0g': 1,
  'd*1~': 1,
  'dá*¡': 1,
  'd*aj': 1,
  'd*áj': 1,
  'da*j\'': 1,
  'da*mn': 1,
  'dang ha*ng': 1,
  'dạn*g háng': 1,
  'de*0': 1,
  'd*e0\'': 1,
  'de*0"': 1,
  'd*e0`': 1,
  'de*0~': 1,
  'd*ek': 1,
  'de*k\'': 1,
  'de*o': 1,
  'd*e\'o': 1,
  'd*eó': 1,
  'd*éo': 1,
  'de*o\'': 1,
  'd*eo': 1,
  'de*o\' ia?': 1,
  'de*o kut\'': 1,
  'd*eo"': 1,
  'd*et m3': 1,
  'd*et* me*': 1,
  'd*ey the\'': 1,
  'd**ĩ': 1,
  'd*i*s': 1,
  'di*s m*e*': 1,
  'd*ï§': 1,
  'd*i†': 1,
  'd*ị†': 1,
  'd*ï†': 1,
  'di*en': 1,
  'd*i*ếm': 1,
  'd*iit': 1,
  'di*s': 1,
  'd*ïs': 1,
  'd*is\'': 1,
  'dis c0n m*e': 1,
  'dis c*0n mje': 1,
  'dis co*0n me': 1,
  'di*s cu': 1,
  'dis k0*n me': 1,
  'd*is k*u': 1,
  'di*s m*e': 1,
  'd*is m*e…': 1,
  'di*s*': 1,
  'd*is*': 1,
  'di*sd': 1,
  'dis*me': 1,
  'dis*s m3': 1,
  'dis*s me': 1,
  'd*isss': 1,
  'd*i\'t': 1,
  'di*x': 1,
  'di*z': 1,
  'd*z': 1,
  'd*j': 1,
  'd*j~': 1,
  'd*j†': 1,
  'dj*e^\'m': 1,
  'dj*e^m\'': 1,
  'dj*em': 1,
  'dj*em\'': 1,
  'd*jf': 1,
  'd*jit': 1,
  'd*jj~': 1,
  'djj*t': 1,
  'dj*s': 1,
  'd*jx': 1,
  'd*jz': 1,
  'd*k': 1,
  'd*k*': 1,
  'd*lt': 1,
  'do*et*': 1,
  'd*ú': 1,
  'd*u m3': 1,
  'du m*a': 1,
  'du m*á': 1,
  'du m*e maj`': 1,
  'd*u*': 1,
  'd*u* me*': 1,
  'du` mo*a\' an kut\'': 1,
  'du*k*': 1,
  'duon*g vat': 1,
  'd*uyt': 1,
  'du*yt': 1,
  'd*ÿ\u0018 ḿ\u0003': 1,
  'd*y*t': 1,
  'd*y`n': 1,
  'd*y~': 1,
  'dy~ de*o\' daj traj': 1,
  'd*ys': 1,
  'dys m*je': 1,
  'dy*t\'': 1,
  'dy*t': 1,
  'd*yt\'': 1,
  'dyt b*uoj ': 1,
  'dyt c*0n m3': 1,
  'dỵt c0*n me': 1,
  'dyt cai i0*ng c0ng l0z': 1,
  'dy*t dyt': 1,
  'dyt k0*an': 1,
  'dyt k*0n m3': 1,
  'd*yt kon me': 1,
  'dyt kon m*e kaj\'\' loz`': 1,
  'dyt k*on me sock': 1,
  'dy*t ku*': 1,
  'dyt l0*z': 1,
  'dy*t m': 1,
  'd*yt m3': 1,
  'dyt m*3 an kuz': 1,
  'dyt m*e': 1,
  'd*yt me': 1,
  'dyt m*e nung l0zl': 1,
  'dyt m*e thagfo`': 1,
  'dyt *me*': 1,
  'dy*t mje': 1,
  'đ*!†': 1,
  'đ*¡§': 1,
  'đ*¡†': 1,
  'đ*¡̣†': 1,
  'đ*¡•t': 1,
  'đ*¡̣t': 1,
  'đ¥*†': 1,
  'đ*¥̣†': 1,
  'đ*¥t': 1,
  'đ¥̣*t': 1,
  'đ€́*ø': 1,
  'đ*µ': 1,
  'đ*µ̣': 1,
  'đµ̣* møª́': 1,
  'đµ́*†': 1,
  'đ†ç*m': 1,
  'đả*ng': 1,
  'đ*é0': 1,
  'đe*ó': 1,
  'đ*éo': 1,
  'đ*ï': 1,
  'đĩ đ*ựç': 1,
  'đ*ị†': 1,
  'đị̈*†': 1,
  'đ*i†': 1,
  'đi†çâ*ñañh': 1,
  'đi†m*ẹ': 1,
  'đi*ên': 1,
  'đ*iĩ': 1,
  'đị*s': 1,
  'đ*is mẹ': 1,
  'đ*it m3*': 1,
  'đi*t mẹ': 1,
  'đ*ịt me': 1,
  'đ*ịt mẹ': 1,
  'đ*ịt*': 1,
  'địt* đ*ỳn': 1,
  'đ*ịt***': 1,
  'đ*iz': 1,
  'đ*î†̣': 1,
  'đị̂*†': 1,
  'đ*ị̂†…mẹ': 1,
  'đ*ị̂t': 1,
  'đ*j̃': 1,
  'đ*j†': 1,
  'đ*jếm': 1,
  'đjế*m ': 1,
  'đj*t': 1,
  'đ*j̣t': 1,
  'đk*lm': 1,
  'đl*t': 1,
  'đ*u': 1,
  'đ*ụ mẹ': 1,
  'đ*ỹ': 1,
  'đ*ÿ§': 1,
  'đy*†': 1,
  'đ*ÿ†': 1,
  'đỵ̈*†': 1,
  'đ*y†': 1,
  'đỵ† k*ụ': 1,
  'đ*ỵ̈† m€̣': 1,
  'đ*ys…': 1,
  'đ*yt': 1,
  'đ*ỵt': 1,
  'đ*ÿt': 1,
  'đ*yṭ mẹ': 1,
  'đ*yt me*': 1,
  'đy*t*': 1,
  'đ*yz': 1,
  'f`*o`': 1,
  'ƒµ¢*¶«': 1,
  'fµ*ck': 1,
  'ƒµ*ck': 1,
  'ƒµ*çk': 1,
  'f*0': 1,
  'ƒ*0': 1,
  'ƒ*0ƒ': 1,
  'f*ho`': 1,
  'f*o': 1,
  'f*ò': 1,
  'f*ö̀': 1,
  'f*ø̀': 1,
  'ƒ*o': 1,
  'ƒ*ò': 1,
  'ƒ*ø̀': 1,
  'f*o`': 1,
  'ƒ*o`': 1,
  'f*oo`': 1,
  'ƒu*c¶«': 1,
  'ƒu*ck': 1,
  'ƒü*çk': 1,
  'fu*uck': 1,
  'gh*e?': 1,
  'gie? ra*ch\'': 1,
  'ha*m~ ion': 1,
  'h*am~ loz': 1,
  'ham~ lo*zl': 1,
  'ha*m~ lozn`': 1,
  'ha*mloz': 1,
  'hc*m': 1,
  'hi*3p': 1,
  'hi*3\'p': 1,
  'hi*e\'p': 1,
  'hie*p\'': 1,
  'h*iếp': 1,
  'hiê*p\'': 1,
  'hj*ep': 1,
  'h*l`': 1,
  'i*tnh*au': 1,
  'i^0*n': 1,
  'i*0^k`': 1,
  'i*0`n': 1,
  'i*0`n`': 1,
  'i0*n': 1,
  'i*0n`': 1,
  'i*0z': 1,
  'i*ạ': 1,
  'i*o^`n': 1,
  'i*o^n': 1,
  'i*o^*n': 1,
  'i*o^n`': 1,
  'io*^n`': 1,
  'i*o^ng': 1,
  'i*o`n': 1,
  'io*`n': 1,
  'i*on': 1,
  'io*n`': 1,
  'io*n` me': 1,
  'io*n`* dis': 1,
  'i*oz': 1,
  'i*oz`': 1,
  'io*z`': 1,
  'iô*n': 1,
  'i*ồn': 1,
  'iồ*ñ': 1,
  'i*ồñ': 1,
  'iô*n`': 1,
  'iô*ng': 1,
  'ị*t': 1,
  'j*a?': 1,
  'k*0n': 1,
  'k0*n cac': 1,
  'k0*n ch0': 1,
  'k0n c*h0 an cuc\'': 1,
  'k0n m*0e* maj': 1,
  'k0n m*3': 1,
  'k0n m*e': 1,
  'k0n m*e maj': 1,
  'k3 m*3': 1,
  'k4*v3': 1,
  'k4*ve': 1,
  'kaj d*yt me': 1,
  'k*aj\' dyt* me': 1,
  'ka*k': 1,
  'k*at ku': 1,
  'ka*v3': 1,
  'ka*ve': 1,
  'k*ăc': 1,
  'k*ặc': 1,
  'k*ặç': 1,
  'k*it\'': 1,
  'k*lm': 1,
  'k*on': 1,
  'ko*n dkm': 1,
  'ko*n ch0\'': 1,
  'k*on cho\'': 1,
  'k*on dj?': 1,
  'ko*n dy~': 1,
  'ko*n f0': 1,
  'k*on kac': 1,
  'kon k*ak': 1,
  'ko*n ky~': 1,
  'k*on m3': 1,
  'kon m*e': 1,
  'ko*n mẹ': 1,
  'kote*x': 1,
  'k*u': 1,
  'k*ụ': 1,
  'k*u*\'t': 1,
  'ku*+t\'': 1,
  'k*uc\'': 1,
  'k*uc kut': 1,
  'k*ut': 1,
  'k*ut\'': 1,
  'ku*t ch0': 1,
  'ku*t het': 1,
  'k*ut nat': 1,
  'k*uz': 1,
  'k*uz\'': 1,
  'k*ứ†': 1,
  'kứ*†…çhó': 1,
  'k*ưt\'': 1,
  'k*ưt́': 1,
  'k*ứt': 1,
  'ky*nh nguye^t*': 1,
  'kh*ìn': 1,
  'kh*jn`': 1,
  'kho*viion': 1,
  'l do*g': 1,
  'l t*o': 1,
  'l*`': 1,
  'l*0^n`': 1,
  'l0*^z`': 1,
  'l*0`z': 1,
  'l0*n': 1,
  'l0o*n': 1,
  'l0*x': 1,
  'l*0z': 1,
  'l0*z`': 1,
  'l0z` me*j': 1,
  'l0*zl': 1,
  'l0*zl`': 1,
  'l0*zn': 1,
  'l0*zn`': 1,
  'l0*zz': 1,
  'la li*em': 1,
  'la ph*o`': 1,
  'la*m` fo`': 1,
  'li3*m': 1,
  'l*i3\'m': 1,
  'lie^m: lolz` m*ek lolz`': 1,
  'li*e\'m': 1,
  'lie*m\'': 1,
  'lie*m i0n ch0': 1,
  'li\'*m': 1,
  'lí*m': 1,
  'li*n`': 1,
  'l*jn': 1,
  'lj*n`': 1,
  'l*m': 1,
  'l*o^`n': 1,
  'l*o^lz`': 1,
  'l*o^n': 1,
  'l*o^n`': 1,
  'l*o^z': 1,
  'l*o^z`': 1,
  'lo^z*n`': 1,
  'l*o+i`': 1,
  'lo*0^n`': 1,
  'lo*0n`': 1,
  'lo*iz': 1,
  'l*ol': 1,
  'lo*lz': 1,
  'l*ön': 1,
  'lo*n\'': 1,
  'lo*on': 1,
  'loo*n`': 1,
  'lo*z': 1,
  'l*öz': 1,
  'lo*z`': 1,
  'l*ozl': 1,
  'lo*zl`': 1,
  'lo*zn': 1,
  'l*ô`n': 1,
  'lô*lz': 1,
  'l*ôñ': 1,
  'l*ôñ̀': 1,
  'lồ*ñ': 1,
  'lô*ǹ': 1,
  'lô*n`': 1,
  'l*ồnz': 1,
  'l*ồz': 1,
  'lu*`n': 1,
  'lu~ d*0g': 1,
  'lu~ re ra*ck:': 1,
  'lu~d*og': 1,
  'lũ…dog h*úp…máu': 1,
  'lua ti*nh': 1,
  'lu*n`': 1,
  'luoj~ tat\' va*`o dau` buoj`': 1,
  'lz*0`': 1,
  'lz*0n`': 1,
  'lz*o`': 1,
  'lz*o`l': 1,
  'lz*ol': 1,
  'lz*ol`': 1,
  'lz*ồn': 1,
  'm€̣ m*aj`': 1,
  'm*0m~': 1,
  'm*3': 1,
  'm3 ma*i': 1,
  'm*a(t* loz': 1,
  'ma*u\' io`n': 1,
  'm*au\' ion': 1,
  'ma*u l': 1,
  'm*au l0z': 1,
  'ma*u lol': 1,
  'm*au loz': 1,
  'ma*u non`': 1,
  'm*ay`': 1,
  'm*e': 1,
  'm*ẹ̈': 1,
  'm*e chu*ng maj': 1,
  'm*e m*ai': 1,
  'm*e m*aj': 1,
  'me* ma*j`': 1,
  'me*t loz': 1,
  'm*i': 1,
  'm*ịe': 1,
  'mi*e*': 1,
  'm*je': 1,
  'm*l': 1,
  'm*l`': 1,
  'mo*^m loz': 1,
  'm*õm': 1,
  'mo*m~': 1,
  'mo*m~ dog lu~ ch0': 1,
  'm*ú†': 1,
  'm*ut': 1,
  'mú*t': 1,
  'm*ut\'': 1,
  'm*ut bi0i': 1,
  'mut b*u0j': 1,
  'm*ut ku': 1,
  'm*ut\' lz0n`': 1,
  'ñ*§ü': 1,
  'ñ*gậm…ßµồ¡': 1,
  'ni*ém': 1,
  'nj*n`': 1,
  'n*o^n`': 1,
  'n*o`n': 1,
  'no*n': 1,
  'n*on^`': 1,
  'no*n`': 1,
  'n*ôn': 1,
  'n*ồn': 1,
  'n*ồñ': 1,
  'ñ*ồñ': 1,
  'nồ*n': 1,
  'ñ*ôǹ': 1,
  'nồ*z': 1,
  'n*u*ng\'': 1,
  'nu*n`': 1,
  'nu*ng*\' loz`': 1,
  'nứ*ng': 1,
  'ng*u': 1,
  'n*h0n`': 1,
  'nh*a` may`': 1,
  'n*ho^n`': 1,
  'nh*u cac': 1,
  'n*huc̣…': 1,
  'nh*uk': 1,
  'p*3`': 1,
  'p*à': 1,
  'p*a`': 1,
  'pa` m*ay`': 1,
  'playk*u': 1,
  'pó c*u': 1,
  'po k*u': 1,
  'pó k*u': 1,
  'po ma*y`': 1,
  'p*o"': 1,
  'p*o`': 1,
  'p*uoi`': 1,
  'pu*ồj': 1,
  'ph*`o': 1,
  'p*h0`': 1,
  'ph*a^n': 1,
  'ph*an^': 1,
  'ph*ân': 1,
  'ra*ck': 1,
  'r*áçk': 1,
  'r*ai\'': 1,
  're r*ack': 1,
  'rẻ ra*cḱ': 1,
  's0*ck k0n me': 1,
  's*elit': 1,
  's*ip': 1,
  'sk*m': 1,
  'so*ck': 1,
  'so*cl': 1,
  'ß*µ́': 1,
  'ßµ*ô¡': 1,
  'ßµ*ồ¡': 1,
  'ßµ*ồ¡¯': 1,
  'ßµ*ồ¿': 1,
  'ß*µồi': 1,
  'ß*µồï': 1,
  'ß*µồi¯': 1,
  'ßµ*ôî': 1,
  'ß*µồî': 1,
  'ß*ố': 1,
  'ßu*oi': 1,
  'ßu*oj': 1,
  'ß*uoj`': 1,
  'ßu*om': 1,
  'ß*uồi': 1,
  'ß*ựa': 1,
  'ßư*ớm': 1,
  'su*a?': 1,
  's*uc vat': 1,
  't*bc': 1,
  't*bs': 1,
  'tie*n su': 1,
  'tu*oi? io`n': 1,
  'tynh tru*g`': 1,
  'tha*ng fo': 1,
  'thang p*ho': 1,
  'th*ang` fo': 1,
  'thoi k*en': 1,
  'thủ d*âm': 1,
  'thủ z*âm': 1,
  'thu*? za^m': 1,
  'tr1*nh': 1,
  'tri*nh': 1,
  'trj*nh': 1,
  't*rlnh': 1,
  'tr*o\'': 1,
  'tr*o"': 1,
  't*rym': 1,
  'try*nh': 1,
  'v*åi': 1,
  'v*kc': 1,
  'v*kl': 1,
  'v*l': 1,
  'v*ú': 1,
  'tư b*ản đỏ': 1,
  'tub*ando': 1,
  'tu b*an do': 1,
  'tư*bản': 1,
  'xã hội ch*ũ nghĩa': 1,
  'xahoic*hunghia': 1,
  'xã hoich*unghia': 1,
  'sã hội chũ ng*hĩa': 1,
  'xa hội chu*nghia': 1,
  'xahoi ch*ủ nghia': 1,
  'xahoic*hu nghĩa': 1,
  'tư bản ch*ủ nghĩa': 1,
  'tubanchu*nghia': 1,
  'tu ban ch*u nghia': 1,
  'tưbản*chủnghĩa': 1,
  'sã*hộichũnghĩa': 1,
  'xãhội*chũnghĩa': 1,
  'nong duc manh': 1,
  'nong ducmanh': 1,
  'nongduc manh': 1,
  'chính phủ': 1,
  'chínhphủ': 1,
  csvn: 1,
  'le kha phieu': 1,
  'lê khả phiêu': 1,
  'lêkhả phiêu': 1,
  'lê khảphiêu': 1,
  'lekha phieu': 1,
  'le khaphieu': 1,
  lekhaphieu: 1,
  vnch: 1,
  'trung cộng-việt cộng': 1,
  'trungcong-vietcong': 1,
  'trungcong-viet cong': 1,
  'trung cong-viet cong': 1,
  'trung cong-vietcong': 1,
  'trungcộng-việt cộng': 1,
  'trungcộng-việtcộng': 1,
  'trung cộng-việtcộng': 1,
  'phạm văn ðồng': 1,
  'phạmvăn ðồng': 1,
  'phạmvănðồng': 1,
  'phạm vănðồng': 1,
  'pham vandong': 1,
  'pham van dong': 1,
  'phamvan dong': 1,
  vndcch: 1,
  'trung cộng': 1,
  'trungcộng': 1,
  trungcong: 1,
  'trung cong': 1,
  'ðại nam': 1,
  'ðạinam': 1,
  dainam: 1,
  'dai nam': 1,
  'chính trị': 1,
  'chinh tri': 1,
  'nguyễn huệ': 1,
  'quang trung': 1,
  'hai bà trưng': 1,
  'nguyen hue': 1,
  'hai ba trung': 1,
  'nguyễn minh triết': 1,
  'nguyen minh triet': 1,
  'nguyễn tấn dũng': 1,
  'nguyen tan dung': 1,
  'quốc hội': 1,
  'quoc hoi': 1,
  'bộ trính trị': 1,
  'bo trinh tri': 1,
  'đảng': 1,
  'đảng cộng sản việt nam': 1,
  'dang cong san viet nam': 1,
  'nguyễn thị doan': 1,
  'mat tran to quoc viet nam': 1,
  'mặt trận tổ quốc việt nam': 1,
  'khủng bố': 1,
  'nguyen thai hoc': 1,
  'nguyễn thái học': 1,
  'cần lao': 1,
  'can lao': 1,
  'ngô đình diệm': 1,
  'ngo dinh diem': 1,
  'ông hồ': 1,
  'hồ chủ tịch': 1,
  'ho chu tich': 1,
  'việt tân': 1,
  'viet tan': 1,
  'phản động': 1,
  'phan dong': 1,
  hitler: 1,
  stalin: 1,
  'bach dang giang': 1,
  'bạch đằng giang': 1,
  chxhcn: 1,
  'cách mạng mầu': 1,
  'cach mang mau': 1,
  'đảng thăng tiến': 1,
  'khoi 8406': 1,
  'khối 8406': 1,
  'đảng dân chủ xxi': 1,
  'dang dan chu xxi': 1,
  'bô-xit': 1,
  'bo-xit': 1,
  bauxite: 1,
  'phản quốc': 1,
  'phan quoc': 1 }