/**
 * Created by vietanha34 on 1/6/16.
 */

module.exports =  {
  "an_cac": 1,
  "ancac": 1,
  "ăn cặc": 1,
  "ăncặc": 1,
  "bà mày": 1,
  "ba mày": 1,
  "bàmay": 1,
  "bamày": 1,
  "bàmày": 1,
  "bamay": 1,
  "ban_dam": 1,
  "ban_hoa": 1,
  "bandam": 1,
  "bomay": 1,
  "bon_cho": 1,
  "bon_khon_nan": 1,
  "boncho": 1,
  "bonkhonnan": 1,
  "bucac": 1,
  "cai_buoi": 1,
  "cai_chim": 1,
  "cai_cu": 1,
  "cai_lon": 1,
  "caibuoi": 1,
  "caichim": 1,
  "caicu": 1,
  "cailon": 1,
  "chim": 1,
  "chim_to": 1,
  "chimto": 1,
  "cho_kin": 1,
  "chochet": 1,
  "chokin": 1,
  "con_cho": 1,
  "con_cu_cac": 1,
  "con_cu_to_tuong": 1,
  "con_di": 1,
  "con_diem": 1,
  "con_pho": 1,
  "concho": 1,
  "concu": 1,
  "concucac": 1,
  "concutotuong": 1,
  "condi": 1,
  "condiem": 1,
  "conghoa": 1,
  "conlon": 1,
  "conpho": 1,
  "cụ": 1,
  "cu_to": 1,
  "cuc_cac": 1,
  "cucac": 1,
  "cuccac": 1,
  "cuccut": 1,
  "cuho": 1,
  "cumay": 1,
  "cuong_dam": 1,
  "cuong_hiep": 1,
  "cuongdam": 1,
  "cuonghiep": 1,
  "dịt": 1,
  "đít": 1,
  "dit_bo": 1,
  "dit_con_cu": 1,
  "dit_concu": 1,
  "dit_conme": 1,
  "dit_cu": 1,
  "dit_cu_may": 1,
  "dit_ong": 1,
  "ditba": 1,
  "ditbo": 1,
  "ditme": 1,
  "ditmemay": 1,
  "ditong": 1,
  "dume": 1,
  "gai_ban_hoa": 1,
  "gai_diem": 1,
  "Gaibanhoa": 1,
  "Gaidiem": 1,
  "ham_hiep": 1,
  "Hamhiep": 1,
  "hanh_kinh": 1,
  "Hanhkinh": 1,
  "hiep_dam": 1,
  "Hiepdam": 1,
  "hồ_chí_minh": 1,
  "ho_chiminh": 1,
  "Hochiminh": 1,
  "Iả": 1,
  "Ỉa": 1,
  "Khốn": 1,
  "khon_nan": 1,
  "Khonnan": 1,
  "Kiep": 1,
  "Kiép": 1,
  "kiếp": 1,
  "lamtinh": 1,
  "liem_cac": 1,
  "liemcac": 1,
  "lòn": 1,
  "lợn": 1,
  "lon_to": 1,
  "long_lon": 1,
  "longlon": 1,
  "lonto": 1,
  "mau_kinh": 1,
  "maukinh": 1,
  "maulon": 1,
  "mẹ": 1,
  "mekiep": 1,
  "memay": 1,
  "mie": 1,
  "mohamet": 1,
  "muadam": 1,
  "mutbuoi": 1,
  "mutcac": 1,
  "nake": 1,
  "nguyenai_quoc": 1,
  "nguyenaiquoc": 1,
  "pimp": 1,
  "sinh_duc": 1,
  "sinhduc": 1,
  "so_lon": 1,
  "solon": 1,
  "su_bo_may": 1,
  "subomay": 1,
  "tosu": 1,
  "v_cong": 1,
  "vai_dai": 1,
  "vai_leu": 1,
  "vai_lin": 1,
  "vai_lon": 1,
  "vaidai": 1,
  "vaileu": 1,
  "vailin": 1,
  "vailon": 1,
  "vcong": 1,
  "viet_cong": 1,
  "1Ồn": 1,
  "1ồN": 1,
  "10n": 1,
  "10`n": 1,
  "1`0n": 1,
  "1ỒN": 1,
  "_BacHo_": 1,
  "_BAcHo_": 1,
  "_Bacho_": 1,
  "_bacHo_": 1,
  "_bAcHo_": 1,
  "bac_ho": 1,
  "Bac_ho": 1,
  "bac_Ho": 1,
  "Bac_Ho": 1,
  "Bác Hồ": 1,
  "bác Hồ": 1,
  "Bác hồ": 1,
  "bác hồ": 1,
  "bÁc Hồ": 1,
  "bÁc hỒ": 1,
  "báC Hồ": 1,
  "b4c Hồ": 1,
  "b4c hỒ": 1,
  "b'4c Hồ": 1,
  "b'4c hỒ": 1,
  "b4'c Hồ": 1,
  "b4'c hỒ": 1,
  "bac h0": 1,
  "Bac h0": 1,
  "bac H0": 1,
  "Bac H0": 1,
  "Buoi": 1,
  "Buoi`": 1,
  "Buồi": 1,
  "bu0`i": 1,
  "Bu0`i": 1,
  "buỒi": 1,
  "BuỒi": 1,
  "congsan": 1,
  "Cong san": 1,
  "cong San": 1,
  "Cong San": 1,
  "cộng Sản": 1,
  "Cộng sản": 1,
  "Congsan": 1,
  "CongSan": 1,
  "C_a_c": 1,
  "c_A_c": 1,
  "C_A_c": 1,
  "C_A_C": 1,
  "c4c": 1,
  "C4c": 1,
  "C4C": 1,
  "cAc.": 1,
  "CAC.": 1,
  "căc.": 1,
  "Căc.": 1,
  "cĂc.": 1,
  "CĂc.": 1,
  "CĂC.": 1,
  "Cặc": 1,
  "cẶc": 1,
  "CẶc": 1,
  "CẶC": 1,
  "Cave": 1,
  "cAve": 1,
  "CAVE": 1,
  "cứt": 1,
  "cỨt": 1,
  "CỨT": 1,
  "CỨt": 1,
  "D1t": 1,
  "D1T": 1,
  "Dai'": 1,
  "dAi'": 1,
  "DAI'": 1,
  "dái": 1,
  "Đái": 1,
  "ĐÁI": 1,
  "dâm": 1,
  "DAMN": 1,
  "DCM": 1,
  "ĐCM": 1,
  "đĩ": 1,
  "đi~": 1,
  "Đi~": 1,
  "ĐĨ": 1,
  "ĐI~": 1,
  "Dĩ": 1,
  "DI~": 1,
  "Di.t": 1,
  "dI.t": 1,
  "Đi.t": 1,
  "địt": 1,
  "đỊt": 1,
  "ĐịT": 1,
  "ĐỊT": 1,
  "Dis": 1,
  "diS": 1,
  "đis": 1,
  "đit": 1,
  "Dit": 1,
  "DIT": 1,
  "ĐIT": 1,
  "điếm": 1,
  "Điếm": 1,
  "điẾm": 1,
  "ĐIẾM": 1,
  "Dm": 1,
  "DM": 1,
  "đm": 1,
  "ĐM": 1,
  "dmm": 1,
  "đmm": 1,
  "Dmm": 1,
  "Đmm": 1,
  "DMM": 1,
  "ĐMM": 1,
  "Đcm": 1,
  "ĐcM": 1,
  "đCM": 1,
  "đcmm": 1,
  "dkm": 1,
  "đkm": 1,
  "dkmm": 1,
  "đkmm": 1,
  "đụ": 1,
  "đỤ": 1,
  "ĐỤ": 1,
  "đu.": 1,
  "Đu.": 1,
  "ĐU.": 1,
  "Fuck": 1,
  "FUCK": 1,
  "f_u_c_k": 1,
  "F_U_C_K": 1,
  "G4meMaster": 1,
  "G4meM4ster": 1,
  "G4me_Master": 1,
  "G4me*Master": 1,
  "GameMaster": 1,
  "Game_Master": 1,
  "[Game]Master": 1,
  "Game*Master": 1,
  "Game[Master]": 1,
  "GM": 1,
  "[G]M": 1,
  "G[M]": 1,
  "Hồ chí minh": 1,
  "HỒ chí minh": 1,
  "hồ chí Minh": 1,
  "Hồ chí Minh": 1,
  "hồ Chí minh": 1,
  "hochiminh": 1,
  "HoChiMinh": 1,
  "HOCHIMINH": 1,
  "ho_chi_minh": 1,
  "Ho_Chi_Minh": 1,
  "Ho Chi Minh": 1,
  "HO CHI MINH": 1,
  "Hiếp": 1,
  "HIẾP": 1,
  "Lo`n": 1,
  "Lon`": 1,
  "lồn": 1,
  "Lôn": 1,
  "LÔN": 1,
  "LỒN": 1,
  "lỒn": 1,
  "mk": 1,
  "Mk": 1,
  "MK": 1,
  "nông đức mạnh": 1,
  "Nông Đức Mạnh": 1,
  "nongducmanh": 1,
  "NONGDUCMANH": 1,
  "PENIS": 1,
  "Phạm Văn Đồng": 1,
  "phạm văn đồng": 1,
  "PHAMVANDONG": 1,
  "Phò": 1,
  "phÒ": 1,
  "PHÒ": 1,
  "Pho`": 1,
  "PHO`": 1,
  "rape": 1,
  "Rape": 1,
  "RAPE": 1,
  "Sex": 1,
  "SEX": 1,
  "Sh1t": 1,
  "SH1T": 1,
  "Shit": 1,
  "SHIT": 1,
  "tổng bí thư": 1,
  "Tổng Bí Thư": 1,
  "tongbithu": 1,
  "tong bi thu": 1,
  "vietcong": 1,
  "Vietcong": 1,
  "VIETCONG": 1,
  "viet cong": 1,
  "Viet Cong": 1,
  "VIET CONG": 1,
  "việt công": 1,
  "Việt Cộng": 1,
  "VIỆT CỘNG": 1,
  "lìn": 1,
  "Lìn": 1,
  "LÌN": 1,
  "li`n": 1,
  "Li`n": 1,
  "LI`N": 1,
  "Thủ Dâm": 1,
  "THỦ DÂM": 1,
  "!ồn": 1,
  "£jn`": 1,
  "£ô`n": 1,
  "£ôÑ": 1,
  "£ồn": 1,
  "£ồñ": 1,
  "₫éo": 1,
  "₫iṭ": 1,
  "₫yt": 1,
  "=-yt.": 1,
  "¶)¡t": 1,
  "¶)ị†": 1,
  "¶_ơÑ": 1,
  "¶ồñ": 1,
  "†¡ñ": 1,
  "†€̀": 1,
  "†ổ": 1,
  "1o`n": 1,
  "1on": 1,
  "1ôn": 1,
  "1ồn": 1,
  "a(n cac": 1,
  "am vat": 1,
  "an buoi": 1,
  "an kut": 1,
  "an kuz": 1,
  "an loz": 1,
  "an no^n": 1,
  "äñ£0ñ": 1,
  "AnLoz": 1,
  "ăn buoi": 1,
  "bµ́": 1,
  "Bµ0m": 1,
  "bµồi": 1,
  "b0 cu": 1,
  "b0 ku": 1,
  "b3`": 1,
  "bà": 1,
  "ba`": 1,
  "bím": 1,
  "bitch": 1,
  "bkl": 1,
  "bó cu": 1,
  "bo ku": 1,
  "bó ku": 1,
  "bo^'": 1,
  "Bu'": 1,
  "bu b": 1,
  "bu' b": 1,
  "bu bu0j": 1,
  "bu buoi": 1,
  "bu buoj": 1,
  "bu lol": 1,
  "bu' lol": 1,
  "bu loz": 1,
  "bu' loz": 1,
  "bu0^j": 1,
  "bu0+m": 1,
  "bu0i": 1,
  "bu0j": 1,
  "bu0j`": 1,
  "bu0m": 1,
  "bu0'm": 1,
  "bu0z`": 1,
  "BuBu0¡": 1,
  "bubuoj": 1,
  "buo^i": 1,
  "bUO^J`": 1,
  "buo^'m": 1,
  "buO^y`": 1,
  "buoi": 1,
  "buoi^": 1,
  "buoi`": 1,
  "buoj": 1,
  "buoj`": 1,
  "buom": 1,
  "buo'm": 1,
  "buôi": 1,
  "Buôì": 1,
  "buồi": 1,
  "bUôj": 1,
  "bUồj": 1,
  "buồy": 1,
  "buớm": 1,
  "bướm": 1,
  "BVS": 1,
  "bym": 1,
  "bým": 1,
  "c0n dy~": 1,
  "c0n f0`": 1,
  "c0n m3": 1,
  "c0n me": 1,
  "c0n mẹ": 1,
  "c0n phO": 1,
  "C0nch0": 1,
  "c0ng s4n": 1,
  "c4v3": 1,
  "c4ve": 1,
  "ca.c": 1,
  "cAc": 1,
  "cạc": 1,
  "Cạ̈c": 1,
  "Cac.": 1,
  "cac.": 1,
  "cai dis": 1,
  "cai' dis": 1,
  "cái dis": 1,
  "cAi DKM": 1,
  "cai' loz": 1,
  "cailoz": 1,
  "caj dis": 1,
  "caj djjt me": 1,
  "caj DKM": 1,
  "caj loz": 1,
  "caj lozl": 1,
  "caj…Đị†": 1,
  "cak": 1,
  "cAM IồN": 1,
  "cav3": 1,
  "cave": 1,
  "căc": 1,
  "cặc": 1,
  "cặç": 1,
  "Çăç": 1,
  "Căk": 1,
  "cặk": 1,
  "cec.": 1,
  "çhÿm": 1,
  "CL": 1,
  "cON": 1,
  "Çoñ": 1,
  "con cac": 1,
  "Çøn Çhǿ": 1,
  "con ch0": 1,
  "Con di~": 1,
  "con di~": 1,
  "con diem": 1,
  "con fò": 1,
  "cOn fO`": 1,
  "con Ion`": 1,
  "con m3": 1,
  "con me": 1,
  "con mẹ": 1,
  "cong san": 1,
  "cộng sản": 1,
  "çU+t'": 1,
  "cu0ng da^m": 1,
  "cuc'": 1,
  "cuc ga`": 1,
  "Çứ†": 1,
  "Cứt": 1,
  "Ch0́": 1,
  "CH0\'\'": 1,
  "ch0'": 1,
  "ch0 ghE dis": 1,
  "ch0 Sua": 1,
  "ch0.": 1,
  "Ch0'a": 1,
  "chém": 1,
  "Chet": 1,
  "CHIM": 1,
  "chjm": 1,
  "chó": 1,
  "cho'": 1,
  "chO kOn bu'": 1,
  "cho\"": 1,
  "Chui": 1,
  "chuj": 1,
  "chuj?": 1,
  "chuj~": 1,
  "chuYm": 1,
  "Chửi..": 1,
  "Chym": 1,
  "chym": 1,
  "d!t": 1,
  "D!t": 1,
  "D!TL": 1,
  "D¥¶¯": 1,
  "D†CM": 1,
  "d0g": 1,
  "d1~": 1,
  "d1t": 1,
  "dá¡": 1,
  "dai'": 1,
  "daj": 1,
  "dáj": 1,
  "daj'": 1,
  "damn": 1,
  "dang hang": 1,
  "dạng háng": 1,
  "dÂm": 1,
  "dcm": 1,
  "de0": 1,
  "de0'": 1,
  "de0\"": 1,
  "de0`": 1,
  "de0~": 1,
  "dek": 1,
  "DEK'": 1,
  "deo": 1,
  "de'o": 1,
  "Deó": 1,
  "déo": 1,
  "-DeO'": 1,
  "DEO": 1,
  "deo'": 1,
  "deO' iA?": 1,
  "deo kut'": 1,
  "deo\"": 1,
  "det m3": 1,
  "dEt. mE.": 1,
  "dey the'": 1,
  "dĩ": 1,
  "di.S": 1,
  "di.S me.": 1,
  "di.t": 1,
  "di~": 1,
  "Dï§": 1,
  "di†": 1,
  "dị†": 1,
  "dï†": 1,
  "dien": 1,
  "D-iếm": 1,
  "diit": 1,
  "dïs": 1,
  "DIS'": 1,
  "dis": 1,
  "dis c0n me": 1,
  "dis c0n mje": 1,
  "DIS CO0N ME": 1,
  "dis cu": 1,
  "Dis K0n Me": 1,
  "dis ku": 1,
  "dis me": 1,
  "Dis me.": 1,
  "diS me.": 1,
  "Dis me…": 1,
  "Dis.": 1,
  "dis.": 1,
  "Disd": 1,
  "disme": 1,
  "diss m3": 1,
  "Diss Me": 1,
  "disss": 1,
  "dit": 1,
  "di't": 1,
  "Dịt": 1,
  "dix": 1,
  "diz": 1,
  "dịz": 1,
  "dj": 1,
  "dj~": 1,
  "dj†": 1,
  "djE^m'": 1,
  "dje^'m": 1,
  "djem": 1,
  "djem'": 1,
  "Djf": 1,
  "Djit": 1,
  "Djj~": 1,
  "djjt": 1,
  "Djs": 1,
  "djx": 1,
  "Djz": 1,
  "DK": 1,
  "dK.": 1,
  "dKm": 1,
  "DlT": 1,
  "dm": 1,
  "doet.": 1,
  "Dú": 1,
  "dụ": 1,
  "du m3": 1,
  "du ma": 1,
  "du má": 1,
  "du me maj`": 1,
  "du.": 1,
  "du. Me.": 1,
  "du` moa' an kut'": 1,
  "duk.": 1,
  "duong vat": 1,
  "DUYT": 1,
  "duyt": 1,
  "DŸ Ḿ": 1,
  "dy.t": 1,
  "Dy.t": 1,
  "dy`n": 1,
  "dY~": 1,
  "dy~ deo' daj traj": 1,
  "dys": 1,
  "dyS mjE": 1,
  "dyt": 1,
  "dYt'": 1,
  "dYt": 1,
  "dyt'": 1,
  "Dyt Buoj ": 1,
  "dyt c0n m3": 1,
  "dỵt c0n me": 1,
  "dyt cai I0ng c0ng l0z": 1,
  "dyt dyt": 1,
  "Dyt K0an": 1,
  "dYT k0n m3": 1,
  "dyt kon me": 1,
  "dyt kon me kaj\'\' loz`": 1,
  "dyt kon me sock": 1,
  "Dyt ku.": 1,
  "dyt l0z": 1,
  "dyt m": 1,
  "DYt m3": 1,
  "Dyt m3 an Kuz": 1,
  "dyt me": 1,
  "Dyt Me": 1,
  "dYt mE nUnG l0zl": 1,
  "dyt me thagfo`": 1,
  "dyt mE.": 1,
  "Dyt me.": 1,
  "dYt mJe": 1,
  "Đ!†": 1,
  "Đ¡§": 1,
  "Đ¡†": 1,
  "đ¡̣†": 1,
  "Đ¡•t": 1,
  "Đ¡̣t": 1,
  "đ¥†": 1,
  "Đ¥̣†": 1,
  "Đ¥t": 1,
  "Đ¥̣T": 1,
  "Đ€́ø": 1,
  "Đµ": 1,
  "đµ̣": 1,
  "Đµ̣ Møª́": 1,
  "Đµ́†": 1,
  "Đ†çm": 1,
  "đái": 1,
  "đcm": 1,
  "đé0": 1,
  "Đeó": 1,
  "đéo": 1,
  "Đĩ": 1,
  "Đï": 1,
  "Đĩ Đựç": 1,
  "Đị†": 1,
  "đị̈†": 1,
  "Đi†": 1,
  "đi†ÇâñAñh": 1,
  "Đi†mẹ": 1,
  "ĐiẾm": 1,
  "điên": 1,
  "Điĩ": 1,
  "Đis": 1,
  "Địs": 1,
  "Đis Mẹ": 1,
  "Đit": 1,
  "Địt": 1,
  "Đit M3.": 1,
  "Đit mẹ": 1,
  "Địt me": 1,
  "Địt mẹ": 1,
  "Địt.": 1,
  "Địt. Đỳn": 1,
  "Địt...": 1,
  "điz": 1,
  "Đî†̣": 1,
  "Đị̂†": 1,
  "Đị̂†…mẹ": 1,
  "Đị̂t": 1,
  "Đj̃": 1,
  "đJ†": 1,
  "đjếm": 1,
  "đjếm ": 1,
  "đjt": 1,
  "Đj̣t": 1,
  "đklm": 1,
  "Đkm": 1,
  "ĐKM": 1,
  "đlt": 1,
  "Đm": 1,
  "đu": 1,
  "Đụ": 1,
  "Đụ mẹ": 1,
  "Đỹ": 1,
  "Đÿ§": 1,
  "Đÿ†": 1,
  "Đỵ̈†": 1,
  "Đy†": 1,
  "Đỵ† kụ": 1,
  "ĐỴ̈† m€̣": 1,
  "Đys…": 1,
  "Đyt": 1,
  "ĐỴT": 1,
  "ĐŸt": 1,
  "đYt": 1,
  "đyṭ mẹ": 1,
  "Đyt me.": 1,
  "đyt.": 1,
  "Đyz": 1,
  "f`O`": 1,
  "ƒµ¢¶«": 1,
  "Fµck": 1,
  "ƒµck": 1,
  "ƒµçk": 1,
  "f0": 1,
  "ƒ0": 1,
  "ƒ0ƒ": 1,
  "fho`": 1,
  "fo": 1,
  "fö̀": 1,
  "fø̀": 1,
  "ƒo": 1,
  "ƒò": 1,
  "ƒø̀": 1,
  "Fò": 1,
  "ƒo`": 1,
  "fo`": 1,
  "foo`": 1,
  "ƒuc¶«": 1,
  "fuck": 1,
  "ƒuck": 1,
  "ƒüçk": 1,
  "Fuuck": 1,
  "ghe?": 1,
  "gie? rach'": 1,
  "ham~ Ion": 1,
  "ham~ loz": 1,
  "ham~ lozl": 1,
  "ham~ lozn`": 1,
  "hamloz": 1,
  "hcm": 1,
  "hi3p": 1,
  "hi3'p": 1,
  "hie'p": 1,
  "hiep'": 1,
  "hiếp": 1,
  "hiêp'": 1,
  "hjep": 1,
  "HL`": 1,
  "ho chi minh": 1,
  "hồ chí minh": 1,
  "i.t": 1,
  "I^0N": 1,
  "I0^k`": 1,
  "I0`n": 1,
  "I0`n`": 1,
  "I0n": 1,
  "I0n`": 1,
  "I0z": 1,
  "iạ": 1,
  "ỉa": 1,
  "IO^`n": 1,
  "IO^-n": 1,
  "Io^n": 1,
  "Io^n`": 1,
  "IO^n`": 1,
  "Io^ng": 1,
  "Io`n": 1,
  "Ion": 1,
  "Ion`": 1,
  "Ion` me": 1,
  "Ion`. Dis": 1,
  "IoZ": 1,
  "Ioz": 1,
  "Ioz`": 1,
  "Iôn": 1,
  "Iồn": 1,
  "Iồñ": 1,
  "Iôn`": 1,
  "Iông": 1,
  "ịt": 1,
  "ja?": 1,
  "k0n": 1,
  "k0n cac": 1,
  "K0n Ch0": 1,
  "k0n ch0 an cuc'": 1,
  "k0n m0e. mAj": 1,
  "k0n m3": 1,
  "k0n me": 1,
  "k0n me maj": 1,
  "K3 M3": 1,
  "k4v3": 1,
  "k4ve": 1,
  "kaj dyt mE": 1,
  "Kaj' dYt. mE": 1,
  "kak": 1,
  "kat ku": 1,
  "kav3": 1,
  "kave": 1,
  "kăc": 1,
  "kặc": 1,
  "kặç": 1,
  "kit'": 1,
  "KLM": 1,
  "Kon": 1,
  "kon DKM": 1,
  "kon ch0'": 1,
  "kon cho'": 1,
  "kon dj?": 1,
  "Kon Dkm": 1,
  "KON DY~": 1,
  "kon f0": 1,
  "kon kac": 1,
  "kon kak": 1,
  "kOn ky~": 1,
  "kon m3": 1,
  "kon me": 1,
  "kon mẹ": 1,
  "kotex": 1,
  "Ku": 1,
  "kụ": 1,
  "Ku*'t": 1,
  "kU+t'": 1,
  "kuc'": 1,
  "kuc kut": 1,
  "KUT": 1,
  "kut'": 1,
  "kut ch0": 1,
  "kut het": 1,
  "Kut nat": 1,
  "Kuz": 1,
  "Kuz'": 1,
  "Kứ†": 1,
  "Kứ†…Çhó": 1,
  "Kưt'": 1,
  "Kưt́": 1,
  "kứt": 1,
  "kYnh nguye^T.": 1,
  "khìn": 1,
  "khjn`": 1,
  "khoviIon": 1,
  "l dog": 1,
  "l to": 1,
  "L`": 1,
  "l0^n`": 1,
  "l0^z`": 1,
  "L0`z": 1,
  "l0n": 1,
  "l0on": 1,
  "l0x": 1,
  "l0z": 1,
  "l0z`": 1,
  "l0z` mej": 1,
  "l0zl": 1,
  "l0zl`": 1,
  "l0zn": 1,
  "l0zn`": 1,
  "l0zz": 1,
  "La Liem": 1,
  "lA pho`": 1,
  "lam` fo`": 1,
  "li3m": 1,
  "li3'm": 1,
  "lie^M: lolz` mek lolz`": 1,
  "lie'm": 1,
  "LIEM'": 1,
  "Liem I0n ch0": 1,
  "li'm": 1,
  "lím": 1,
  "lin`": 1,
  "ljn": 1,
  "ljn`": 1,
  "LM": 1,
  "lO^`n": 1,
  "Lo^lz`": 1,
  "lo^n": 1,
  "lo^n`": 1,
  "lo^z": 1,
  "lO^z`": 1,
  "lo^zn`": 1,
  "lo`n": 1,
  "lO+i`": 1,
  "LO0^N`": 1,
  "lo0n`": 1,
  "loiz": 1,
  "lol": 1,
  "lOlz": 1,
  "lon": 1,
  "lÖn": 1,
  "lon'": 1,
  "lon`": 1,
  "loon": 1,
  "loon`": 1,
  "loz": 1,
  "löz": 1,
  "loz`": 1,
  "Lozl": 1,
  "lozl`": 1,
  "lozn": 1,
  "Lô`n": 1,
  "lÔlz": 1,
  "lôñ": 1,
  "Lôñ̀": 1,
  "Lồn": 1,
  "lồñ": 1,
  "Lôǹ": 1,
  "lôn`": 1,
  "lồnz": 1,
  "lồz": 1,
  "lu`n": 1,
  "Lu`n": 1,
  "Lu~ d0g": 1,
  "lu~ re rack:": 1,
  "lu~dog": 1,
  "Lũ…Dog Húp…Máu": 1,
  "lua tinh": 1,
  "lun`": 1,
  "luoj~ tat' va`o dau` buoj`": 1,
  "lz0`": 1,
  "lz0n`": 1,
  "lzo`": 1,
  "lZO`l": 1,
  "lzol": 1,
  "lzol`": 1,
  "lzồn": 1,
  "m€̣ mAj`": 1,
  "m0m~": 1,
  "m3": 1,
  "m3 mai": 1,
  "mA(t. lOz": 1,
  "mau' Io`n": 1,
  "mau' Ion": 1,
  "mau L": 1,
  "mau l0z": 1,
  "mau lol": 1,
  "mau loz": 1,
  "mau non`": 1,
  "MAy`": 1,
  "me": 1,
  "Mẹ": 1,
  "Mẹ̈": 1,
  "me chung maj": 1,
  "me mai": 1,
  "me maj": 1,
  "me. maj`": 1,
  "met loz": 1,
  "mI": 1,
  "Mịe": 1,
  "mie.": 1,
  "mje": 1,
  "ML": 1,
  "ml": 1,
  "ML`": 1,
  "ml`": 1,
  "mo^m loz": 1,
  "mõm": 1,
  "Mom~": 1,
  "mom~ dog lu~ ch0": 1,
  "mú†": 1,
  "mut": 1,
  "mút": 1,
  "mut'": 1,
  "mut bi0i": 1,
  "mut bu0j": 1,
  "mut ku": 1,
  "mut' lz0n`": 1,
  "Ñ§ü": 1,
  "Ñgậm…ßµồ¡": 1,
  "niém": 1,
  "njn`": 1,
  "no^n`": 1,
  "no`n": 1,
  "non": 1,
  "non^`": 1,
  "non`": 1,
  "nôn": 1,
  "nồn": 1,
  "Nồñ": 1,
  "Ñồñ": 1,
  "Nồn": 1,
  "Ñôǹ": 1,
  "nỒz": 1,
  "nu*ng'": 1,
  "nUn`": 1,
  "nung*' loz`": 1,
  "nứng": 1,
  "ngu": 1,
  "nh0n`": 1,
  "nha` may`": 1,
  "nho^n`": 1,
  "nhu cac": 1,
  "Nhuc̣…": 1,
  "nhuk": 1,
  "p3`": 1,
  "pà": 1,
  "pA`": 1,
  "pa` may`": 1,
  "penis": 1,
  "playku": 1,
  "pó cu": 1,
  "po ku": 1,
  "pó ku": 1,
  "po may`": 1,
  "po\"": 1,
  "po`": 1,
  "Puoi`": 1,
  "puồj": 1,
  "Ph`o": 1,
  "ph0`": 1,
  "pha^n": 1,
  "phan^": 1,
  "phân": 1,
  "phò": 1,
  "pho`": 1,
  "rack": 1,
  "Ráçk": 1,
  "rai'": 1,
  "re rack": 1,
  "rẻ racḱ": 1,
  "s0ck k0n me": 1,
  "Selit": 1,
  "sex": 1,
  "sh1t": 1,
  "shit": 1,
  "sip": 1,
  "skm": 1,
  "sOck": 1,
  "socl": 1,
  "ßµ́": 1,
  "ßµô¡": 1,
  "ßµồ¡": 1,
  "ßµồ¡¯": 1,
  "ßµồ¿": 1,
  "ßµồi": 1,
  "ßµồï": 1,
  "ßµồi¯": 1,
  "ßµôî": 1,
  "ßµồî": 1,
  "ßố": 1,
  "ßuoi": 1,
  "ßuoj": 1,
  "ßuoj`": 1,
  "ßuom": 1,
  "ßuồi": 1,
  "ßựa": 1,
  "ßướm": 1,
  "sua?": 1,
  "suc vaT": 1,
  "tbc": 1,
  "tbs": 1,
  "Tien Su": 1,
  "Tuoi? Io`n": 1,
  "tYnh truG`": 1,
  "thang fo": 1,
  "thang pho": 1,
  "thang` fo": 1,
  "thoi ken": 1,
  "thủ dâm": 1,
  "thủ zâm": 1,
  "thu? za^m": 1,
  "tr1nh": 1,
  "trlnh": 1,
  "tro'": 1,
  "tro\"": 1,
  "trym": 1,
  "trynh": 1,
  "våi": 1,
  "vkc": 1,
  "vkl": 1,
  "vl": 1,
  "vú": 1,
  "vu'": 1,
  "xl": 1,
  "zá¡": 1,
  "zaj": 1,
  "záj": 1,
  "zaj'": 1,
  "zú": 1,
  "an_ca.c": 1,
  "anc.ac": 1,
  "ăn c.ặc": 1,
  "ăn.cặc": 1,
  "ba_ma.y": 1,
  "bà m.ày": 1,
  "ba m.ày": 1,
  "bà.may": 1,
  "ba.mày": 1,
  "bàm.ày": 1,
  "bac_h.o": 1,
  "ba.may": 1,
  "ban_d.am": 1,
  "ban_ho.a": 1,
  "banda.m": 1,
  "ba.nhoa": 1,
  "bán.hoa": 1,
  "bo_ma.y": 1,
  "bo.may": 1,
  "bon_ch.o": 1,
  "bon_kh.on_nan": 1,
  "bonc.ho": 1,
  "bonk.honnan": 1,
  "bre.ast": 1,
  "buc.ac": 1,
  "bu.ồi": 1,
  "buo.m": 1,
  "b.ướm": 1,
  "cạ.c": 1,
  "cặ.c": 1,
  "cai_bu.oi": 1,
  "cai_ch.im": 1,
  "cai_c.u": 1,
  "cai_lo.n": 1,
  "caib.uoi": 1,
  "caic.him": 1,
  "ca.icu": 1,
  "cail.on": 1,
  "ch.im": 1,
  "chi.m_to": 1,
  "chi.mto": 1,
  "cho_ch.et": 1,
  "c.ho_kin": 1,
  "cho.chet": 1,
  "chok.in": 1,
  "con_c.ho": 1,
  "c.on_cu": 1,
  "c.on_cu_cac": 1,
  "con_cu_to_tu.ong": 1,
  "c.on_di": 1,
  "con_die.m": 1,
  "con_ph.o": 1,
  "conc.ho": 1,
  "con.cu": 1,
  "con.cucac": 1,
  "concuto.tuong": 1,
  "co.ndi": 1,
  "condie.m": 1,
  "cong.hoa": 1,
  "cong.san": 1,
  "conl.on": 1,
  "conp.ho": 1,
  "cs.an": 1,
  "c.ụ": 1,
  "cu_ca.c": 1,
  "cu_m.ay": 1,
  "cu_t.o": 1,
  "cuc_ca.c": 1,
  "cuc_c.ut": 1,
  "cu.cac": 1,
  "cucca.c": 1,
  "cuc.cut": 1,
  "cu.ho": 1,
  "cu.may": 1,
  "cu.nt": 1,
  "cuo.ng_dam": 1,
  "cuon.g_hiep": 1,
  "cuon.gdam": 1,
  "cuo.nghiep": 1,
  "cut.o": 1,
  "dâ.m": 1,
  "da.n_chu": 1,
  "dan.chu": 1,
  "da.ng_c_s": 1,
  "da.ng_cong_san": 1,
  "dang_cong.san": 1,
  "da.ng_cs": 1,
  "da.ng_tien_tri": 1,
  "dan.g_tientri": 1,
  "dang.congsan": 1,
  "dang.cs": 1,
  "dang.tien_tri": 1,
  "da.ngtientri": 1,
  "điế.m": 1,
  "di.s_me": 1,
  "di.sme": 1,
  "dị.t": 1,
  "đí.t": 1,
  "d.it_bo": 1,
  "di.t_con_cu": 1,
  "dit_co.n_me": 1,
  "dit_c.oncu": 1,
  "dit_con.me": 1,
  "d.it_cu": 1,
  "dit_cu_m.ay": 1,
  "dit_m.e": 1,
  "dit_o.ng": 1,
  "dit.ba": 1,
  "d.itbo": 1,
  "dit.me": 1,
  "ditm.e": 1,
  "ditm.emay": 1,
  "dito.ng": 1,
  "doco.ncho": 1,
  "do.khon": 1,
  "d.rug": 1,
  "du_m.a": 1,
  "d.ục": 1,
  "du.ma": 1,
  "du.me": 1,
  "gai_b.an_hoa": 1,
  "gai_die.m": 1,
  "Gaiban.hoa": 1,
  "Gaid.iem": 1,
  "h.am_hiep": 1,
  "Hamh.iep": 1,
  "ha.nh_kinh": 1,
  "Ha.nhkinh": 1,
  "Hiế.p": 1,
  "hiep_da.m": 1,
  "Hiepda.m": 1,
  "ho_chi_mi.nh": 1,
  "hồ_chí_m.inh": 1,
  "ho_chim.inh": 1,
  "hochi_m.inh": 1,
  "Hochi.minh": 1,
  "I.ả": 1,
  "Ỉ.a": 1,
  "K.hốn": 1,
  "kho.n_nan": 1,
  "Kho.nnan": 1,
  "khu.ng_bo": 1,
  "Kh.ungbo": 1,
  "Ki.ep": 1,
  "Ki.ép": 1,
  "kiế.p": 1,
  "la.m_tinh": 1,
  "lam.tinh": 1,
  "lie.m_cac": 1,
  "lie.mcac": 1,
  "l.òn": 1,
  "lợ.n": 1,
  "lo.n_to": 1,
  "lo.ng_lon": 1,
  "lo.nglon": 1,
  "lo.nto": 1,
  "lu_ch.o": 1,
  "lu_k.hon": 1,
  "luc.ho": 1,
  "luk.hon": 1,
  "mau_k.inh": 1,
  "m.au_lon": 1,
  "mauki.nh": 1,
  "mau.lon": 1,
  "m.ẹ": 1,
  "m.e_kiep": 1,
  "me_m.ay": 1,
  "me.kiep": 1,
  "me.may": 1,
  "mi.e": 1,
  "moha.met": 1,
  "mua_da.m": 1,
  "mua.dam": 1,
  "mu.t_cac": 1,
  "mu.tbuoi": 1,
  "mut.cac": 1,
  "na.ke": 1,
  "ngu.yen_ai_quoc": 1,
  "nguy.en_aiquoc": 1,
  "nguyen.ai_quoc": 1,
  "nguyen.aiquoc": 1,
  "nguyenaiq.uoc": 1,
  "ong_m.ay": 1,
  "ongm.ay": 1,
  "pim.p": 1,
  "sin.h_duc": 1,
  "sin.hduc": 1,
  "sl.ut": 1,
  "so_lo.n": 1,
  "s.olon": 1,
  "su_bo_ma.y": 1,
  "subo.may": 1,
  "th.ang_cho": 1,
  "than.gcho": 1,
  "tie.n_su": 1,
  "tien.su": 1,
  "tinh_du.c": 1,
  "tin.hduc": 1,
  "to_s.u": 1,
  "to.su": 1,
  "v_co.ng": 1,
  "vai_da.i": 1,
  "v.ai_leu": 1,
  "v.ai_lin": 1,
  "va.i_lon": 1,
  "vaida.i": 1,
  "va.ileu": 1,
  "vaili.n": 1,
  "va.ilon": 1,
  "vco.ng": 1,
  "viet_co.ng": 1,
  "Cổ L.oa": 1,
  "Vạn X.uân": 1,
  "Thà.nh Hồ": 1,
  "Tha.nh Ho": 1,
  "Vua Đi.nh": 1,
  "Vu.a Lê": 1,
  "H.oa Lư": 1,
  "Cố .Đô Huế": 1,
  "1.ồn": 1,
  "1.Ồn": 1,
  "1ồ.N": 1,
  "1.0n": 1,
  "1.0`n": 1,
  "1`0.n": 1,
  "1Ồ.N": 1,
  "_Ba.cHo_": 1,
  "_Bac.Ho_": 1,
  "_Ba.cho_": 1,
  "_b.acHo_": 1,
  "_bAc.Ho_": 1,
  "ba.c_ho": 1,
  "B.ac_ho": 1,
  "b.ac_Ho": 1,
  "Ba.c_Ho": 1,
  "B.ác Hồ": 1,
  "b.ác Hồ": 1,
  "B.ác hồ": 1,
  "bá.c hồ": 1,
  "b.Ác Hồ": 1,
  "bÁ.c hỒ": 1,
  "bá.C Hồ": 1,
  "b4.c Hồ": 1,
  "b4c h.Ồ": 1,
  "b'.4c Hồ": 1,
  "b'4.c hỒ": 1,
  "b4'.c Hồ": 1,
  "b4'.c hỒ": 1,
  "ba.c h0": 1,
  "B.ac h0": 1,
  "bac H.0": 1,
  "B.ac H0": 1,
  "b.itch": 1,
  "BIT.CH": 1,
  "Bi.tch": 1,
  "Bu.oi": 1,
  "B.uoi`": 1,
  "Bu.ồi": 1,
  "b.u0`i": 1,
  "Bu.0`i": 1,
  "bu.Ồi": 1,
  "Bu.Ồi": 1,
  "congs.an": 1,
  "co.ng san": 1,
  "Cong. san": 1,
  "co.ng San": 1,
  "Con.g San": 1,
  "cộn.g Sản": 1,
  "Cộn.g sản": 1,
  "co.ng_san": 1,
  "Con.gsan": 1,
  "Con.gSan": 1,
  "cuh.o": 1,
  "Cu.ho": 1,
  "cuH.o": 1,
  "CuH.o": 1,
  "c.uh0": 1,
  "Cuh.0": 1,
  "cu.H0": 1,
  "Cu.H0": 1,
  "cu_h.o": 1,
  "Cu_h.o": 1,
  "cU_h.o": 1,
  "cu_.Ho": 1,
  "cu_h.O": 1,
  "c.ụ hồ": 1,
  "Cụ h.ồ": 1,
  "cỤ h.ồ": 1,
  "cụ H.ồ": 1,
  "cụ h.Ồ": 1,
  "c_a._c": 1,
  "C_a._c": 1,
  "c_A._c": 1,
  "C_A._c": 1,
  "C_A._C": 1,
  "c4.c": 1,
  "C.4c": 1,
  "C4.C": 1,
  "ca.c.": 1,
  "c.Ac.": 1,
  "C.AC.": 1,
  "că.c.": 1,
  "C.ăc.": 1,
  "cĂ.c.": 1,
  "C.Ăc.": 1,
  "CĂ.C.": 1,
  "C.ặc": 1,
  "c.Ặc": 1,
  "CẶ.c": 1,
  "C.ẶC": 1,
  "cav.e": 1,
  "Ca.ve": 1,
  "cA.ve": 1,
  "c.Ave": 1,
  "c.ứt": 1,
  "c.Ứt": 1,
  "C.ỨT": 1,
  "C.Ứt": 1,
  "d.1t": 1,
  "D1.t": 1,
  "D.1T": 1,
  "Da.i'": 1,
  "dA.i'": 1,
  "D.AI'": 1,
  "d.ái": 1,
  "đá.i": 1,
  "Đ.ái": 1,
  "Đ.ÁI": 1,
  "d.âm": 1,
  "dÂ.m": 1,
  "dam.n": 1,
  "DAM.N": 1,
  "DC.M": 1,
  "ĐC.M": 1,
  "Đc.m": 1,
  "đ.ĩ": 1,
  "đ.i~": 1,
  "Đ.i~": 1,
  "Đ.Ĩ": 1,
  "Đ.I~": 1,
  "D.ĩ": 1,
  "D.I~": 1,
  "D.i.t": 1,
  "d.I.t": 1,
  "D.I.T": 1,
  "đ.i.t": 1,
  "Đ.i.t": 1,
  "Đ.I.T": 1,
  "đị.t": 1,
  "đ.Ịt": 1,
  "Đ.ịT": 1,
  "Đ.ỊT": 1,
  "D.is": 1,
  "d.iS": 1,
  "đi.s": 1,
  "đi.t": 1,
  "D.it": 1,
  "DI.T": 1,
  "ĐI.T": 1,
  "đi.ếm": 1,
  "Đi.ếm": 1,
  "điẾ.m": 1,
  "ĐiẾ.M": 1,
  "D.m": 1,
  "D.M": 1,
  "đ.m": 1,
  "Đ.M": 1,
  "dm.m": 1,
  "đm.m": 1,
  "Dm.m": 1,
  "Đm.m": 1,
  "DM.M": 1,
  "ĐM.M": 1,
  "Đ.cm": 1,
  "Đc.M": 1,
  "đC.M": 1,
  "đcm.m": 1,
  "dk.m": 1,
  "đk.m": 1,
  "d.cm": 1,
  "dk.mm": 1,
  "đk.mm": 1,
  "đ.ụ": 1,
  "đ.Ụ": 1,
  "Đ.Ụ": 1,
  "đ.u.": 1,
  "Đ.u.": 1,
  "Đ.U.": 1,
  "F.uck": 1,
  "FU.CK": 1,
  "f_u._c_k": 1,
  "F_U_C._K": 1,
  "G4m.eMaster": 1,
  "G4me.M4ster": 1,
  "G4me_Ma.ster": 1,
  "G4me_M4s.ter": 1,
  "G4.me*Master": 1,
  "G4m.e*M4ster": 1,
  "Ga.meMaster": 1,
  "Gam.e_Master": 1,
  "[Game].Master": 1,
  "Game*M.aster": 1,
  "Game[M.aster]": 1,
  "G.M": 1,
  "[G].M": 1,
  "G.[M]": 1,
  "G_.M": 1,
  "G*.M": 1,
  "Hồ chí m.inh": 1,
  "HỒ c.hí minh": 1,
  "hồ C.hí minh": 1,
  "hồ chí Mi.nh": 1,
  "Hồ ch.í Minh": 1,
  "h.ồ Chí minh": 1,
  "hochi.minh": 1,
  "HoCh.iMinh": 1,
  "HOCH.IMINH": 1,
  "ho_ch.i_minh": 1,
  "Ho_Ch.i_Minh": 1,
  "Ho C.hi Minh": 1,
  "HO C.HI MINH": 1,
  "hi.ếp": 1,
  "Hi.ếp": 1,
  "HI.ẾP": 1,
  "L.o`n": 1,
  "lo.n`": 1,
  "L.on`": 1,
  "lồ.n": 1,
  "Lồ.n": 1,
  "L.ôn": 1,
  "LÔ.N": 1,
  "L.ỒN": 1,
  "l.Ồn": 1,
  "m.k": 1,
  "M.k": 1,
  "M.K": 1,
  "nông đứ.c mạnh": 1,
  "Nông .Đức Mạnh": 1,
  "nongduc.manh": 1,
  "NONG.DUCMANH": 1,
  "pen.is": 1,
  "PE.NIS": 1,
  "Phạ.m Văn Đồng": 1,
  "phạm vă.n đồng": 1,
  "phamvand.ong": 1,
  "PHAM.VANDONG": 1,
  "Ph.ò": 1,
  "ph.Ò": 1,
  "PH.Ò": 1,
  "Ph.o`": 1,
  "PH.O`": 1,
  "rap.e": 1,
  "Ra.pe": 1,
  "RA.PE": 1,
  "s.ex": 1,
  "Se.x": 1,
  "SE.X": 1,
  "Sh1.t": 1,
  "SH1.T": 1,
  "Sh.it": 1,
  "SH.IT": 1,
  "tổ.ng bí thư": 1,
  "Tổng B.í Thư": 1,
  "tongb.ithu": 1,
  "tong b.i thu": 1,
  "vietc.ong": 1,
  "Vietcon.g": 1,
  "VIETC.ONG": 1,
  "viet c.ong": 1,
  "Vi.et Cong": 1,
  "VIET C.ONG": 1,
  "việt c.ông": 1,
  "Việ.t Cộng": 1,
  "VIỆT C.ỘNG": 1,
  "lì.n": 1,
  "L.ìn": 1,
  "LÌ.N": 1,
  "li.`n": 1,
  "Li.`n": 1,
  "LI`.N": 1,
  "th.ủ dâm": 1,
  "Thủ Dâ.m": 1,
  "TH.Ủ DÂ.M": 1,
  "!ồ..n": 1,
  "£.j.n`": 1,
  "£.ô`n": 1,
  "£ô.Ñ": 1,
  "£.ồn": 1,
  "£.ồñ": 1,
  "₫.éo": 1,
  "₫.iṭ": 1,
  "₫y.t": 1,
  "y.t.": 1,
  "¶).¡t": 1,
  "¶).ị†": 1,
  "¶_ồ.ñ": 1,
  "¶_ơ.Ñ": 1,
  "¶.ồñ": 1,
  "†.¡ñ": 1,
  "†.€̀": 1,
  "†.ổ": 1,
  "1.o`n": 1,
  "1o.n": 1,
  "1.ôn": 1,
  "1ồ.n": 1,
  "a(n c.ac": 1,
  "a.m vat": 1,
  "an b.uoi": 1,
  "an k.ut": 1,
  "an k.uz": 1,
  "a.n loz": 1,
  "an no.^n": 1,
  "äñ.£0ñ": 1,
  "An.Loz": 1,
  "ăn bu.oi": 1,
  "b.µ́": 1,
  "Bµ0.m": 1,
  "bµ.ồi": 1,
  "b.0 cu": 1,
  "b.0 ku": 1,
  "b.3`": 1,
  "b.à": 1,
  "b.a`": 1,
  "bí.m": 1,
  "bit.ch": 1,
  "b.kl": 1,
  "bó c.u": 1,
  "bo k.u": 1,
  "b.ó ku": 1,
  "b.o^'": 1,
  "B.u'": 1,
  "b.u b": 1,
  "b.u' b": 1,
  "bu b.u0j": 1,
  "bu b.uoi": 1,
  "bu b.uoj": 1,
  "bu l.ol": 1,
  "bu' l.ol": 1,
  "bu lo.z": 1,
  "bu' lo.z": 1,
  "bu.0^j": 1,
  "bu.0+m": 1,
  "b.u0i": 1,
  "bu.0j": 1,
  "bu.0j`": 1,
  "bu0.j`": 1,
  "b.u0m": 1,
  "bu.0'm": 1,
  "b.u0z`": 1,
  "Bu.Bu0¡": 1,
  "bub.uoj": 1,
  "bu.o^i": 1,
  "bU.O^J`": 1,
  "bu.o^'m": 1,
  "bu.O^y`": 1,
  "bu.oi": 1,
  "bu.oi^": 1,
  "bu.oi`": 1,
  "bu.oj": 1,
  "b.uoj`": 1,
  "bu.om": 1,
  "bu.o'm": 1,
  "bu.ôi": 1,
  "B.uôì": 1,
  "b.uồi": 1,
  "bU.ôj": 1,
  "bU.ồj": 1,
  "bu.ồy": 1,
  "buớ.m": 1,
  "bư.ớm": 1,
  "bư.m": 1,
  "BV.S": 1,
  "by.m": 1,
  "bý.m": 1,
  "c0.n dy~": 1,
  "c0n f.0`": 1,
  "c.0n m3": 1,
  "c0.n me": 1,
  "c0n m.ẹ": 1,
  "c0.n phO": 1,
  "C0nch.0": 1,
  "c0n.g s4n": 1,
  "c4.v3": 1,
  "c4.ve": 1,
  "c.a.c": 1,
  "c.Ac": 1,
  "c.ạc": 1,
  "C.ạ̈c": 1,
  "C.ac.": 1,
  "c.ac.": 1,
  "cai d.is": 1,
  "c.ai' dis": 1,
  "cái d.is": 1,
  "cAi DK.M": 1,
  "c.ai' loz": 1,
  "cailo.z": 1,
  "caj di.s": 1,
  "caj dj.jt me": 1,
  "ca.j DKM": 1,
  "c.aj loz": 1,
  "caj lo.zl": 1,
  "ca.j…Đị†": 1,
  "ca.k": 1,
  "cA.M IồN": 1,
  "ca.v3": 1,
  "ca.ve": 1,
  "că.c": 1,
  "c.ặc": 1,
  "cặ.ç": 1,
  "Ç.ăç": 1,
  "C.ăk": 1,
  "cặ.k": 1,
  "c.ec.": 1,
  "çh.ÿm": 1,
  "C.L": 1,
  "c.ON": 1,
  "Ço.ñ": 1,
  "co.n cac": 1,
  "Çøn Ç.hǿ": 1,
  "c.on ch0": 1,
  "C.on di~": 1,
  "co.n di~": 1,
  "con die.m": 1,
  "co.n fò": 1,
  "cO.n fO`": 1,
  "con I.on`": 1,
  "co.n m3": 1,
  "con m.e": 1,
  "co.n mẹ": 1,
  "cong sa.n": 1,
  "cộn.g sản": 1,
  "çU.+t'": 1,
  "cu0n.g da^m": 1,
  "c.uc'": 1,
  "cuc g.a`": 1,
  "Ç.ứ†": 1,
  "C.ứt": 1,
  "Ch.0́": 1,
  "CH.0\'\'": 1,
  "c.h0'": 1,
  "ch0 g.hE dis": 1,
  "ch0 Su.a": 1,
  "ch.0.": 1,
  "Ch.0'a": 1,
  "ch.ém": 1,
  "Ch.et": 1,
  "CH.IM": 1,
  "CHI.M": 1,
  "chj.m": 1,
  "ch.ó": 1,
  "ch.o'": 1,
  "chO kO.n bu'": 1,
  "ch.o\"": 1,
  "Ch.ui": 1,
  "ch.uj": 1,
  "ch.uj?": 1,
  "ch.uj~": 1,
  "ch.uYm": 1,
  "C.hửi..": 1,
  "Ch.ym": 1,
  "ch.ym": 1,
  "d.!t": 1,
  "D!.t": 1,
  "D!.TL": 1,
  "D.yt": 1,
  "D.¥¶¯": 1,
  "D†C.M": 1,
  "d.0g": 1,
  "d.1~": 1,
  "d1.t": 1,
  "dá.¡": 1,
  "d.ai'": 1,
  "d.aj": 1,
  "d.áj": 1,
  "da.j'": 1,
  "da.mn": 1,
  "dang ha.ng": 1,
  "dạn.g háng": 1,
  "d.Âm": 1,
  "dc.m": 1,
  "de.0": 1,
  "d.e0'": 1,
  "de.0\"": 1,
  "d.e0`": 1,
  "de.0~": 1,
  "d.ek": 1,
  "DE.K'": 1,
  "de.o": 1,
  "d.e'o": 1,
  "D.eó": 1,
  "d.éo": 1,
  "De.O'": 1,
  "D.EO": 1,
  "de.o'": 1,
  "de.O' iA?": 1,
  "de.o kut'": 1,
  "d.eo\"": 1,
  "d.et m3": 1,
  "d.Et. mE.": 1,
  "d.ey the'": 1,
  "d.ĩ": 1,
  "D.-ĩ": 1,
  "d.i.S": 1,
  "di.S m.e.": 1,
  "d.i.t": 1,
  "d.i~": 1,
  "D.ï§": 1,
  "d.i†": 1,
  "d.ị†": 1,
  "d.ï†": 1,
  "di.en": 1,
  "D-i.ếm": 1,
  "d.iit": 1,
  "di.s": 1,
  "d.ïs": 1,
  "D.IS'": 1,
  "d.is": 1,
  "dis c0n m.e": 1,
  "dis c.0n mje": 1,
  "DIS CO.0N ME": 1,
  "di.s cu": 1,
  "Dis K0.n Me": 1,
  "d.is k.u": 1,
  "di.s m.e": 1,
  "Di.s m.e.": 1,
  "D.is m.e…": 1,
  "Di.s.": 1,
  "d.is.": 1,
  "Di.sd": 1,
  "dis.me": 1,
  "dis.s m3": 1,
  "Dis.s Me": 1,
  "d.isss": 1,
  "d.it": 1,
  "d.i't": 1,
  "Dị.t": 1,
  "di.x": 1,
  "di.z": 1,
  "d.z": 1,
  "d.j": 1,
  "d.j~": 1,
  "d.j†": 1,
  "dj.E^m'": 1,
  "dj.e^'m": 1,
  "dj.em": 1,
  "dj.em'": 1,
  "D.jf": 1,
  "D.jit": 1,
  "D.jj~": 1,
  "djj.t": 1,
  "Dj.s": 1,
  "d.jx": 1,
  "D.jz": 1,
  "D.K": 1,
  "d.K.": 1,
  "dK.m": 1,
  "D.lT": 1,
  "d.m": 1,
  "do.et.": 1,
  "D.ú": 1,
  "d.ụ": 1,
  "d.u m3": 1,
  "du m.a": 1,
  "du m.á": 1,
  "du m.e maj`": 1,
  "d.u.": 1,
  "d.u. Me.": 1,
  "du` mo.a' an kut'": 1,
  "du.k.": 1,
  "duon.g vat": 1,
  "D.UYT": 1,
  "du.yt": 1,
  "D.Ÿ Ḿ": 1,
  "d.y.t": 1,
  "D.y.t": 1,
  "d.y`n": 1,
  "d.Y~": 1,
  "dy~ de.o' daj traj": 1,
  "d.ys": 1,
  "dyS m.jE": 1,
  "d.yt": 1,
  "dY.t'": 1,
  "dY.t": 1,
  "d.yt'": 1,
  "Dyt B.uoj ": 1,
  "dyt c.0n m3": 1,
  "dỵt c0.n me": 1,
  "dyt cai I0.ng c0ng l0z": 1,
  "dy.t dyt": 1,
  "Dyt K0.an": 1,
  "dYT k.0n m3": 1,
  "d.yt kon me": 1,
  "dyt kon m.e kaj\'\' loz`": 1,
  "dyt k.on me sock": 1,
  "Dy.t ku.": 1,
  "dyt l0.z": 1,
  "dy.t m": 1,
  "D.Yt m3": 1,
  "Dyt m.3 an Kuz": 1,
  "dyt m.e": 1,
  "D.yt Me": 1,
  "dYt m.E nUnG l0zl": 1,
  "dyt m.e thagfo`": 1,
  "dyt .mE.": 1,
  "Dyt .me.": 1,
  "dY.t mJe": 1,
  "Đ.!†": 1,
  "Đ.¡§": 1,
  "Đ.¡†": 1,
  "đ.¡̣†": 1,
  "Đ.¡•t": 1,
  "Đ.¡̣t": 1,
  "đ¥.†": 1,
  "Đ.¥̣†": 1,
  "Đ.¥t": 1,
  "Đ¥̣.T": 1,
  "Đ€́.ø": 1,
  "Đ.µ": 1,
  "đ.µ̣": 1,
  "Đµ̣. Møª́": 1,
  "Đµ́.†": 1,
  "Đ†ç.m": 1,
  "đ.ái": 1,
  "đả.ng": 1,
  "đc.m": 1,
  "đ.é0": 1,
  "Đe.ó": 1,
  "đ.éo": 1,
  "Đ.ĩ": 1,
  "Đ.ï": 1,
  "Đĩ Đ.ựç": 1,
  "đị̈.†": 1,
  "Đ.i†": 1,
  "Đ.ị†": 1,
  "đi†Çâ.ñAñh": 1,
  "Đi†m.ẹ": 1,
  "Đi.Ếm": 1,
  "đi.ên": 1,
  "Đ.iĩ": 1,
  "Đ.is": 1,
  "Đị.s": 1,
  "Đ.is Mẹ": 1,
  "Đ.it": 1,
  "Đ.ịt": 1,
  "Đ.it M3.": 1,
  "Đi.t mẹ": 1,
  "Đ.ịt me": 1,
  "Đ.ịt mẹ": 1,
  "Đ.ịt.": 1,
  "Địt. Đ.ỳn": 1,
  "Đ.ịt...": 1,
  "đ.iz": 1,
  "Đ.î†̣": 1,
  "Đị̂.†": 1,
  "Đ.ị̂†…mẹ": 1,
  "Đ.ị̂t": 1,
  "Đ.j̃": 1,
  "đ.J†": 1,
  "đ.jếm": 1,
  "đjế.m ": 1,
  "đj.t": 1,
  "Đ.j̣t": 1,
  "đk.lm": 1,
  "Đk.m": 1,
  "ĐK.M": 1,
  "đl.t": 1,
  "Đ.m": 1,
  "đ.u": 1,
  "Đ.ụ": 1,
  "Đ.ụ mẹ": 1,
  "Đ.ỹ": 1,
  "Đ.ÿ§": 1,
  "Đy.†": 1,
  "Đ.ÿ†": 1,
  "Đỵ̈.†": 1,
  "Đ.y†": 1,
  "Đỵ† k.ụ": 1,
  "Đ.Ỵ̈† m€̣": 1,
  "Đ.ys…": 1,
  "Đ.yt": 1,
  "Đ.ỴT": 1,
  "Đ.Ÿt": 1,
  "đ.Yt": 1,
  "đ.yṭ mẹ": 1,
  "Đ.yt me.": 1,
  "đy.t.": 1,
  "Đ.yz": 1,
  "f`.O`": 1,
  "ƒµ¢.¶«": 1,
  "Fµ.ck": 1,
  "ƒµ.ck": 1,
  "ƒµ.çk": 1,
  "f.0": 1,
  "ƒ.0": 1,
  "ƒ.0ƒ": 1,
  "f.ho`": 1,
  "f.o": 1,
  "f.ö̀": 1,
  "f.ø̀": 1,
  "ƒ.o": 1,
  "ƒ.ò": 1,
  "ƒ.ø̀": 1,
  "F.ò": 1,
  "ƒ.o`": 1,
  "f.o`": 1,
  "f.oo`": 1,
  "ƒu.c¶«": 1,
  "fu.ck": 1,
  "ƒu.ck": 1,
  "ƒü.çk": 1,
  "Fu.uck": 1,
  "gh.e?": 1,
  "gie? Ra.ch'": 1,
  "ha.m~ Ion": 1,
  "h.am~ loz": 1,
  "ham~ lo.zl": 1,
  "ha.m~ lozn`": 1,
  "ha.mloz": 1,
  "hc.m": 1,
  "hi.3p": 1,
  "hi.3'p": 1,
  "hi.e'p": 1,
  "hie.p'": 1,
  "h.iếp": 1,
  "hiê.p'": 1,
  "hj.ep": 1,
  "H.L`": 1,
  "ho ch.i minh": 1,
  "hồ ch.í minh": 1,
  "i.tnh.au": 1,
  "I^0.N": 1,
  "I.0^k`": 1,
  "I.0`n": 1,
  "I.0`n`": 1,
  "I0.n": 1,
  "I.0n`": 1,
  "I.0z": 1,
  "i.ạ": 1,
  "ỉ.a": 1,
  "I.O^`n": 1,
  "I.O^-n": 1,
  "I.o^n": 1,
  "I.o^n`": 1,
  "IO.^n`": 1,
  "I.o^ng": 1,
  "I.o`n": 1,
  "Io.`n": 1,
  "I.on": 1,
  "Io.n`": 1,
  "Io.n` me": 1,
  "Io.n`. Dis": 1,
  "I.oZ": 1,
  "I.oz": 1,
  "I.oz`": 1,
  "Io.z`": 1,
  "Iô.n": 1,
  "I.ồn": 1,
  "Iồ.ñ": 1,
  "I.ồñ": 1,
  "Iô.n`": 1,
  "Iô.ng": 1,
  "ị.t": 1,
  "j.a?": 1,
  "k.0n": 1,
  "k0.n cac": 1,
  "K0.n Ch0": 1,
  "k0n c.h0 an cuc'": 1,
  "k0n m.0e. mAj": 1,
  "k0n m.3": 1,
  "k0n m.e": 1,
  "k0n m.e maj": 1,
  "K3 M.3": 1,
  "k4.v3": 1,
  "k4.ve": 1,
  "kaj d.yt mE": 1,
  "K.aj' dYt. mE": 1,
  "ka.k": 1,
  "k.at ku": 1,
  "ka.v3": 1,
  "ka.ve": 1,
  "k.ăc": 1,
  "k.ặc": 1,
  "k.ặç": 1,
  "k.it'": 1,
  "K.LM": 1,
  "K.on": 1,
  "ko.n DKM": 1,
  "ko.n ch0'": 1,
  "k.on cho'": 1,
  "k.on dj?": 1,
  "Ko.n Dkm": 1,
  "KO.N DY~": 1,
  "ko.n f0": 1,
  "k.on kac": 1,
  "kon k.ak": 1,
  "kO.n ky~": 1,
  "k.on m3": 1,
  "kon m.e": 1,
  "ko.n mẹ": 1,
  "kote.x": 1,
  "K.u": 1,
  "k.ụ": 1,
  "K.u*'t": 1,
  "kU.+t'": 1,
  "k.uc'": 1,
  "k.uc kut": 1,
  "K.UT": 1,
  "k.ut'": 1,
  "ku.t ch0": 1,
  "ku.t het": 1,
  "K.ut nat": 1,
  "K.uz": 1,
  "K.uz'": 1,
  "K.ứ†": 1,
  "Kứ.†…Çhó": 1,
  "K.ưt'": 1,
  "K.ưt́": 1,
  "k.ứt": 1,
  "kY.nh nguye^T.": 1,
  "kh.ìn": 1,
  "kh.jn`": 1,
  "kho.viIon": 1,
  "l do.g": 1,
  "l t.o": 1,
  "L.`": 1,
  "l.0^n`": 1,
  "l0.^z`": 1,
  "L.0`z": 1,
  "l0.n": 1,
  "l0o.n": 1,
  "l0.x": 1,
  "l.0z": 1,
  "l0.z`": 1,
  "l0z` me.j": 1,
  "l0.zl": 1,
  "l0.zl`": 1,
  "l0.zn": 1,
  "l0.zn`": 1,
  "l0.zz": 1,
  "La Li.em": 1,
  "lA ph.o`": 1,
  "la.m` fo`": 1,
  "li3.m": 1,
  "l.i3'm": 1,
  "lie^M: lolz` m.ek lolz`": 1,
  "li.e'm": 1,
  "LIE.M'": 1,
  "Lie.m I0n ch0": 1,
  "li'.m": 1,
  "lí.m": 1,
  "li.n`": 1,
  "l.jn": 1,
  "lj.n`": 1,
  "L.M": 1,
  "l.O^`n": 1,
  "L.o^lz`": 1,
  "l.o^n": 1,
  "l.o^n`": 1,
  "l.o^z": 1,
  "l.O^z`": 1,
  "lo^z.n`": 1,
  "lo.`n": 1,
  "l.O+i`": 1,
  "LO.0^N`": 1,
  "lo.0n`": 1,
  "lo.iz": 1,
  "l.ol": 1,
  "lO.lz": 1,
  "lo.n": 1,
  "l.Ön": 1,
  "lo.n'": 1,
  "l.on`": 1,
  "lo.on": 1,
  "loo.n`": 1,
  "lo.z": 1,
  "l.öz": 1,
  "lo.z`": 1,
  "L.ozl": 1,
  "lo.zl`": 1,
  "lo.zn": 1,
  "L.ô`n": 1,
  "lÔ.lz": 1,
  "lô.n": 1,
  "l.ôñ": 1,
  "L.ôñ̀": 1,
  "L.ồn": 1,
  "lồ.ñ": 1,
  "Lô.ǹ": 1,
  "lô.n`": 1,
  "l.ồnz": 1,
  "l.ồz": 1,
  "lu.`n": 1,
  "Lu.`n": 1,
  "Lu~ d.0g": 1,
  "lu~ re ra.ck:": 1,
  "lu~d.og": 1,
  "Lũ…Dog H.úp…Máu": 1,
  "lua ti.nh": 1,
  "lu.n`": 1,
  "luoj~ tat' va.`o dau` buoj`": 1,
  "lz.0`": 1,
  "lz.0n`": 1,
  "lz.o`": 1,
  "lZ.O`l": 1,
  "lz.ol": 1,
  "lz.ol`": 1,
  "lz.ồn": 1,
  "m€̣ m.Aj`": 1,
  "m.0m~": 1,
  "m.3": 1,
  "m3 ma.i": 1,
  "m.A(t. lOz": 1,
  "ma.u' Io`n": 1,
  "m.au' Ion": 1,
  "ma.u L": 1,
  "m.au l0z": 1,
  "ma.u lol": 1,
  "m.au loz": 1,
  "ma.u non`": 1,
  "M.Ay`": 1,
  "m.e": 1,
  "M.ẹ": 1,
  "M.ẹ̈": 1,
  "m.e chu.ng maj": 1,
  "m.e m.ai": 1,
  "m.e m.aj": 1,
  "me. Ma.j`": 1,
  "me.t loz": 1,
  "m.I": 1,
  "M.ịe": 1,
  "mi.e.": 1,
  "m.je": 1,
  "M.L": 1,
  "m.l": 1,
  "M.L`": 1,
  "m.l`": 1,
  "mo.^m loz": 1,
  "m.õm": 1,
  "Mo.m~": 1,
  "mo.m~ dog lu~ ch0": 1,
  "m.ú†": 1,
  "m.ut": 1,
  "mú.t": 1,
  "m.ut'": 1,
  "m.ut bi0i": 1,
  "mut b.u0j": 1,
  "m.ut ku": 1,
  "m.ut' lz0n`": 1,
  "Ñ.§ü": 1,
  "Ñ.gậm…ßµồ¡": 1,
  "ni.ém": 1,
  "nj.n`": 1,
  "n.o^n`": 1,
  "n.o`n": 1,
  "no.n": 1,
  "n.on^`": 1,
  "no.n`": 1,
  "n.ôn": 1,
  "n.ồn": 1,
  "N.ồñ": 1,
  "Ñ.ồñ": 1,
  "Nồ.n": 1,
  "Ñ.ôǹ": 1,
  "nỒ.z": 1,
  "n.u*ng'": 1,
  "nU.n`": 1,
  "nu.ng*' loz`": 1,
  "nứ.ng": 1,
  "ng.u": 1,
  "n.h0n`": 1,
  "nh.a` may`": 1,
  "n.ho^n`": 1,
  "nh.u cac": 1,
  "N.huc̣…": 1,
  "nh.uk": 1,
  "p.3`": 1,
  "p.à": 1,
  "p.A`": 1,
  "pa` m.ay`": 1,
  "pe.nis": 1,
  "playk.u": 1,
  "pó c.u": 1,
  "po k.u": 1,
  "pó k.u": 1,
  "po ma.y`": 1,
  "p.o\"": 1,
  "p.o`": 1,
  "P.uoi`": 1,
  "pu.ồj": 1,
  "Ph.`o": 1,
  "p.h0`": 1,
  "ph.a^n": 1,
  "ph.an^": 1,
  "ph.ân": 1,
  "ph.ò": 1,
  "p.ho`": 1,
  "ra.ck": 1,
  "R.áçk": 1,
  "r.ai'": 1,
  "ra.pe": 1,
  "re r.ack": 1,
  "rẻ ra.cḱ": 1,
  "s0.ck k0n me": 1,
  "S.elit": 1,
  "se.x": 1,
  "sh.1t": 1,
  "sh.it": 1,
  "s.ip": 1,
  "sk.m": 1,
  "sO.ck": 1,
  "so.cl": 1,
  "ß.µ́": 1,
  "ßµ.ô¡": 1,
  "ßµ.ồ¡": 1,
  "ßµ.ồ¡¯": 1,
  "ßµ.ồ¿": 1,
  "ß.µồi": 1,
  "ß.µồï": 1,
  "ß.µồi¯": 1,
  "ßµ.ôî": 1,
  "ß.µồî": 1,
  "ß.ố": 1,
  "ßu.oi": 1,
  "ßu.oj": 1,
  "ß.uoj`": 1,
  "ßu.om": 1,
  "ß.uồi": 1,
  "ß.ựa": 1,
  "ßư.ớm": 1,
  "su.a?": 1,
  "s.uc vaT": 1,
  "t.bc": 1,
  "t.bs": 1,
  "Tie.n Su": 1,
  "Tu.oi? Io`n": 1,
  "tYnh tru.G`": 1,
  "tha.ng fo": 1,
  "thang p.ho": 1,
  "th.ang` fo": 1,
  "thoi k.en": 1,
  "thủ d.âm": 1,
  "thủ z.âm": 1,
  "thu.? za^m": 1,
  "tr1.nh": 1,
  "tri.nh": 1,
  "trj.nh": 1,
  "t.rlnh": 1,
  "tr.o'": 1,
  "tr.o\"": 1,
  "t.rym": 1,
  "try.nh": 1,
  "v.åi": 1,
  "v.kc": 1,
  "v.kl": 1,
  "v.l": 1,
  "v.ú": 1,
  "tư b.ản đỏ": 1,
  "tub.ando": 1,
  "tu b.an do": 1,
  "tư.bản": 1,
  "xã hội ch.ũ nghĩa": 1,
  "xahoic.hunghia": 1,
  "xã hoich.unghia": 1,
  "sã hội chũ ng.hĩa": 1,
  "xa hội chu.nghia": 1,
  "xahoi ch.ủ nghia": 1,
  "xahoic.hu nghĩa": 1,
  "tư bản ch.ủ nghĩa": 1,
  "tubanchu.nghia": 1,
  "tu ban ch.u nghia": 1,
  "tưbản.chủnghĩa": 1,
  "sã.hộichũnghĩa": 1,
  "xãhội.chũnghĩa": 1,
  "an_ca_c": 1,
  "anc_ac": 1,
  "ăn c_ặc": 1,
  "ăn_cặc": 1,
  "ba_ma_y": 1,
  "bà m_ày": 1,
  "ba m_ày": 1,
  "bà_may": 1,
  "ba_mày": 1,
  "bàm_ày": 1,
  "bac_h_o": 1,
  "ba_may": 1,
  "ban_d_am": 1,
  "ban_ho_a": 1,
  "banda_m": 1,
  "ba_nhoa": 1,
  "bán_hoa": 1,
  "bo_ma_y": 1,
  "bo_may": 1,
  "bon_ch_o": 1,
  "bon_kh_on_nan": 1,
  "bonc_ho": 1,
  "bonk_honnan": 1,
  "bre_ast": 1,
  "buc_ac": 1,
  "bu_ồi": 1,
  "buo_m": 1,
  "b_ướm": 1,
  "c_san": 1,
  "cạ_c": 1,
  "cặ_c": 1,
  "cai_bu_oi": 1,
  "cai_ch_im": 1,
  "cai_c_u": 1,
  "cai_lo_n": 1,
  "caib_uoi": 1,
  "caic_him": 1,
  "ca_icu": 1,
  "cail_on": 1,
  "ch_im": 1,
  "chi_m_to": 1,
  "chi_mto": 1,
  "cho_ch_et": 1,
  "c_ho_kin": 1,
  "cho_chet": 1,
  "chok_in": 1,
  "con_c_ho": 1,
  "c_on_cu": 1,
  "c_on_cu_cac": 1,
  "con_cu_to_tu_ong": 1,
  "c_on_di": 1,
  "con_die_m": 1,
  "con_ph_o": 1,
  "conc_ho": 1,
  "con_cu": 1,
  "con_cucac": 1,
  "concuto_tuong": 1,
  "co_ndi": 1,
  "condie_m": 1,
  "cong_hoa": 1,
  "cong_san": 1,
  "conl_on": 1,
  "conp_ho": 1,
  "cs_an": 1,
  "c_ụ": 1,
  "cu_ca_c": 1,
  "cu_m_ay": 1,
  "cu_t_o": 1,
  "cuc_ca_c": 1,
  "cuc_c_ut": 1,
  "cu_cac": 1,
  "cucca_c": 1,
  "cuc_cut": 1,
  "cu_ho": 1,
  "cu_may": 1,
  "cu_nt": 1,
  "cuo_ng_dam": 1,
  "cuon_g_hiep": 1,
  "cuon_gdam": 1,
  "cuo_nghiep": 1,
  "cut_o": 1,
  "dâ_m": 1,
  "da_n_chu": 1,
  "dan_chu": 1,
  "da_ng_c_s": 1,
  "da_ng_cong_san": 1,
  "dang_cong_san": 1,
  "da_ng_cs": 1,
  "da_ng_tien_tri": 1,
  "dan_g_tientri": 1,
  "dang_congsan": 1,
  "dang_cs": 1,
  "dang_tien_tri": 1,
  "da_ngtientri": 1,
  "điế_m": 1,
  "di_s_me": 1,
  "di_sme": 1,
  "dị_t": 1,
  "đí_t": 1,
  "d_it_bo": 1,
  "di_t_con_cu": 1,
  "dit_co_n_me": 1,
  "dit_c_oncu": 1,
  "dit_con_me": 1,
  "d_it_cu": 1,
  "dit_cu_m_ay": 1,
  "dit_m_e": 1,
  "dit_o_ng": 1,
  "dit_ba": 1,
  "d_itbo": 1,
  "dit_me": 1,
  "ditm_e": 1,
  "ditm_emay": 1,
  "dito_ng": 1,
  "doco_ncho": 1,
  "do_khon": 1,
  "d_rug": 1,
  "du_m_a": 1,
  "d_ục": 1,
  "du_ma": 1,
  "du_me": 1,
  "gai_b_an_hoa": 1,
  "gai_die_m": 1,
  "Gaiban_hoa": 1,
  "Gaid_iem": 1,
  "h_am_hiep": 1,
  "Hamh_iep": 1,
  "ha_nh_kinh": 1,
  "Ha_nhkinh": 1,
  "Hiế_p": 1,
  "hiep_da_m": 1,
  "Hiepda_m": 1,
  "ho_chi_mi_nh": 1,
  "hồ_chí_m_inh": 1,
  "ho_chim_inh": 1,
  "hochi_m_inh": 1,
  "Hochi_minh": 1,
  "I_ả": 1,
  "Ỉ_a": 1,
  "K_hốn": 1,
  "kho_n_nan": 1,
  "Kho_nnan": 1,
  "khu_ng_bo": 1,
  "Kh_ungbo": 1,
  "Ki_ep": 1,
  "Ki_ép": 1,
  "kiế_p": 1,
  "la_m_tinh": 1,
  "lam_tinh": 1,
  "lie_m_cac": 1,
  "lie_mcac": 1,
  "l_òn": 1,
  "lợ_n": 1,
  "lo_n_to": 1,
  "lo_ng_lon": 1,
  "lo_nglon": 1,
  "lo_nto": 1,
  "lu_ch_o": 1,
  "lu_k_hon": 1,
  "luc_ho": 1,
  "luk_hon": 1,
  "mau_k_inh": 1,
  "m_au_lon": 1,
  "mauki_nh": 1,
  "mau_lon": 1,
  "m_ẹ": 1,
  "m_e_kiep": 1,
  "me_m_ay": 1,
  "me_kiep": 1,
  "me_may": 1,
  "mi_e": 1,
  "moha_met": 1,
  "mua_da_m": 1,
  "mua_dam": 1,
  "mu_t_cac": 1,
  "mu_tbuoi": 1,
  "mut_cac": 1,
  "na_ke": 1,
  "ngu_yen_ai_quoc": 1,
  "nguy_en_aiquoc": 1,
  "nguyen_ai_quoc": 1,
  "nguyen_aiquoc": 1,
  "nguyenaiq_uoc": 1,
  "ong_m_ay": 1,
  "ongm_ay": 1,
  "pim_p": 1,
  "s_h_i_t": 1,
  "sin_h_duc": 1,
  "sin_hduc": 1,
  "sl_ut": 1,
  "so_lo_n": 1,
  "s_olon": 1,
  "su_bo_ma_y": 1,
  "subo_may": 1,
  "th_ang_cho": 1,
  "than_gcho": 1,
  "tie_n_su": 1,
  "tien_su": 1,
  "tinh_du_c": 1,
  "tin_hduc": 1,
  "to_s_u": 1,
  "to_su": 1,
  "v_co_ng": 1,
  "vai_da_i": 1,
  "v_ai_leu": 1,
  "v_ai_lin": 1,
  "va_i_lon": 1,
  "vaida_i": 1,
  "va_ileu": 1,
  "vaili_n": 1,
  "va_ilon": 1,
  "vco_ng": 1,
  "viet_co_ng": 1,
  "Vạn X_uân": 1,
  "Thà_nh Hồ": 1,
  "Tha_nh Ho": 1,
  "Vua Đi_nh": 1,
  "Vu_a Lê": 1,
  "H_oa Lư": 1,
  "Cố _Đô Huế": 1,
  "1_ồn": 1,
  "1_Ồn": 1,
  "1ồ_N": 1,
  "1_0n": 1,
  "1_0`n": 1,
  "1`0_n": 1,
  "1Ồ_N": 1,
  "_Ba_cHo_": 1,
  "_Bac_Ho_": 1,
  "_Ba_cho_": 1,
  "_b_acHo_": 1,
  "_bAc_Ho_": 1,
  "ba_c_ho": 1,
  "B_ac_ho": 1,
  "b_ac_Ho": 1,
  "Ba_c_Ho": 1,
  "B_ác Hồ": 1,
  "b_ác Hồ": 1,
  "B_ác hồ": 1,
  "bá_c hồ": 1,
  "b_Ác Hồ": 1,
  "bÁ_c hỒ": 1,
  "bá_C Hồ": 1,
  "b4_c Hồ": 1,
  "b4c h_Ồ": 1,
  "b'_4c Hồ": 1,
  "b'4_c hỒ": 1,
  "b4'_c Hồ": 1,
  "b4'_c hỒ": 1,
  "ba_c h0": 1,
  "B_ac h0": 1,
  "bac H_0": 1,
  "B_ac H0": 1,
  "b_itch": 1,
  "BIT_CH": 1,
  "Bi_tch": 1,
  "Bu_oi": 1,
  "B_uoi`": 1,
  "Bu_ồi": 1,
  "b_u0`i": 1,
  "Bu_0`i": 1,
  "bu_Ồi": 1,
  "Bu_Ồi": 1,
  "congs_an": 1,
  "co_ng san": 1,
  "Cong_ san": 1,
  "co_ng San": 1,
  "Con_g San": 1,
  "cộn_g Sản": 1,
  "Cộn_g sản": 1,
  "co_ng_san": 1,
  "Con_gsan": 1,
  "Con_gSan": 1,
  "cuh_o": 1,
  "Cu_ho": 1,
  "cuH_o": 1,
  "CuH_o": 1,
  "c_uh0": 1,
  "Cuh_0": 1,
  "cu_H0": 1,
  "Cu_H0": 1,
  "cu_h_o": 1,
  "Cu_h_o": 1,
  "cU_h_o": 1,
  "cu__Ho": 1,
  "cu_h_O": 1,
  "c_ụ hồ": 1,
  "Cụ h_ồ": 1,
  "cỤ h_ồ": 1,
  "cụ H_ồ": 1,
  "cụ h_Ồ": 1,
  "c_a__c": 1,
  "C_a__c": 1,
  "c_A__c": 1,
  "C_A__c": 1,
  "C_A__C": 1,
  "c4_c": 1,
  "C_4c": 1,
  "C4_C": 1,
  "ca_c_": 1,
  "c_Ac_": 1,
  "C_AC_": 1,
  "că_c_": 1,
  "C_ăc_": 1,
  "cĂ_c_": 1,
  "C_Ăc_": 1,
  "CĂ_C_": 1,
  "C_ặc": 1,
  "c_Ặc": 1,
  "CẶ_c": 1,
  "C_ẶC": 1,
  "cav_e": 1,
  "Ca_ve": 1,
  "cA_ve": 1,
  "c_Ave": 1,
  "CA_VE": 1,
  "c_ứt": 1,
  "c_Ứt": 1,
  "C_ỨT": 1,
  "C_Ứt": 1,
  "d_1t": 1,
  "D1_t": 1,
  "D_1T": 1,
  "Da_i'": 1,
  "dA_i'": 1,
  "D_AI'": 1,
  "d_ái": 1,
  "đá_i": 1,
  "Đ_ái": 1,
  "Đ_ÁI": 1,
  "d_âm": 1,
  "dÂ_m": 1,
  "dam_n": 1,
  "DAM_N": 1,
  "DC_M": 1,
  "ĐC_M": 1,
  "Đc_m": 1,
  "đ_ĩ": 1,
  "đ_i~": 1,
  "Đ_i~": 1,
  "Đ_Ĩ": 1,
  "Đ_I~": 1,
  "D_ĩ": 1,
  "D_I~": 1,
  "D_i_t": 1,
  "d_I_t": 1,
  "D_I_T": 1,
  "đ_i_t": 1,
  "Đ_i_t": 1,
  "Đ_I_T": 1,
  "đị_t": 1,
  "đ_Ịt": 1,
  "Đ_ịT": 1,
  "Đ_ỊT": 1,
  "D_is": 1,
  "d_iS": 1,
  "đi_s": 1,
  "đi_t": 1,
  "D_it": 1,
  "DI_T": 1,
  "ĐI_T": 1,
  "đi_ếm": 1,
  "Đi_ếm": 1,
  "điẾ_m": 1,
  "ĐiẾ_M": 1,
  "D_m": 1,
  "D_M": 1,
  "đ_m": 1,
  "Đ_M": 1,
  "dm_m": 1,
  "đm_m": 1,
  "Dm_m": 1,
  "Đm_m": 1,
  "DM_M": 1,
  "ĐM_M": 1,
  "Đ_cm": 1,
  "Đc_M": 1,
  "đC_M": 1,
  "đcm_m": 1,
  "dk_m": 1,
  "đk_m": 1,
  "d_cm": 1,
  "dk_mm": 1,
  "đk_mm": 1,
  "đ_ụ": 1,
  "đ_Ụ": 1,
  "Đ_Ụ": 1,
  "đ_u_": 1,
  "Đ_u_": 1,
  "Đ_U_": 1,
  "F_uck": 1,
  "FU_CK": 1,
  "f_u__c_k": 1,
  "F_U_C__K": 1,
  "G4m_eMaster": 1,
  "G4me_M4ster": 1,
  "G4me_Ma_ster": 1,
  "G4me_M4s_ter": 1,
  "G4_me*Master": 1,
  "G4m_e*M4ster": 1,
  "Ga_meMaster": 1,
  "Gam_e_Master": 1,
  "[Game]_Master": 1,
  "Game*M_aster": 1,
  "Game[M_aster]": 1,
  "G_M": 1,
  "[G]_M": 1,
  "G_[M]": 1,
  "G__M": 1,
  "G*_M": 1,
  "Hồ chí m_inh": 1,
  "HỒ c_hí minh": 1,
  "hồ C_hí minh": 1,
  "hồ chí Mi_nh": 1,
  "Hồ ch_í Minh": 1,
  "h_ồ Chí minh": 1,
  "hochi_minh": 1,
  "HoCh_iMinh": 1,
  "HOCH_IMINH": 1,
  "ho_ch_i_minh": 1,
  "Ho_Ch_i_Minh": 1,
  "Ho C_hi Minh": 1,
  "HO C_HI MINH": 1,
  "hi_ếp": 1,
  "Hi_ếp": 1,
  "HI_ẾP": 1,
  "L_o`n": 1,
  "lo_n`": 1,
  "L_on`": 1,
  "lồ_n": 1,
  "Lồ_n": 1,
  "L_ôn": 1,
  "LÔ_N": 1,
  "L_ỒN": 1,
  "l_Ồn": 1,
  "m_k": 1,
  "M_k": 1,
  "M_K": 1,
  "nông đứ_c mạnh": 1,
  "Nông _Đức Mạnh": 1,
  "nongduc_manh": 1,
  "NONG_DUCMANH": 1,
  "pen_is": 1,
  "PE_NIS": 1,
  "Phạ_m Văn Đồng": 1,
  "phạm vă_n đồng": 1,
  "phamvand_ong": 1,
  "PHAM_VANDONG": 1,
  "Ph_ò": 1,
  "ph_Ò": 1,
  "PH_Ò": 1,
  "Ph_o`": 1,
  "PH_O`": 1,
  "rap_e": 1,
  "Ra_pe": 1,
  "RA_PE": 1,
  "s_ex": 1,
  "Se_x": 1,
  "SE_X": 1,
  "Sh1_t": 1,
  "SH1_T": 1,
  "Sh_it": 1,
  "SH_IT": 1,
  "tổ_ng bí thư": 1,
  "Tổng B_í Thư": 1,
  "tongb_ithu": 1,
  "tong b_i thu": 1,
  "vietc_ong": 1,
  "Vietcon_g": 1,
  "VIETC_ONG": 1,
  "viet c_ong": 1,
  "Vi_et Cong": 1,
  "VIET C_ONG": 1,
  "việt c_ông": 1,
  "Việ_t Cộng": 1,
  "VIỆT C_ỘNG": 1,
  "lì_n": 1,
  "L_ìn": 1,
  "LÌ_N": 1,
  "li_`n": 1,
  "Li_`n": 1,
  "LI`_N": 1,
  "th_ủ dâm": 1,
  "Thủ Dâ_m": 1,
  "TH_Ủ DÂ_M": 1,
  "!ồ__n": 1,
  "£_j_n`": 1,
  "£_ô`n": 1,
  "£ô_Ñ": 1,
  "£_ồn": 1,
  "£_ồñ": 1,
  "₫_éo": 1,
  "₫_iṭ": 1,
  "₫y_t": 1,
  "y_t_": 1,
  "¶)_¡t": 1,
  "¶)_ị†": 1,
  "¶_ồ_ñ": 1,
  "¶_ơ_Ñ": 1,
  "¶_ồñ": 1,
  "†_¡ñ": 1,
  "†_€̀": 1,
  "†_ổ": 1,
  "1_o`n": 1,
  "1o_n": 1,
  "1_ôn": 1,
  "1ồ_n": 1,
  "a(n c_ac": 1,
  "a_m vat": 1,
  "an b_uoi": 1,
  "an k_ut": 1,
  "an k_uz": 1,
  "a_n loz": 1,
  "an no_^n": 1,
  "äñ_£0ñ": 1,
  "An_Loz": 1,
  "ăn bu_oi": 1,
  "b_µ́": 1,
  "Bµ0_m": 1,
  "bµ_ồi": 1,
  "b_0 cu": 1,
  "b_0 ku": 1,
  "b_3`": 1,
  "b_à": 1,
  "b_a`": 1,
  "bí_m": 1,
  "bit_ch": 1,
  "b_kl": 1,
  "bó c_u": 1,
  "bo k_u": 1,
  "b_ó ku": 1,
  "b_o^'": 1,
  "B_u'": 1,
  "b_u b": 1,
  "b_u' b": 1,
  "bu b_u0j": 1,
  "bu b_uoi": 1,
  "bu b_uoj": 1,
  "bu l_ol": 1,
  "bu' l_ol": 1,
  "bu lo_z": 1,
  "bu' lo_z": 1,
  "bu_0^j": 1,
  "bu_0+m": 1,
  "b_u0i": 1,
  "bu_0j": 1,
  "bu_0j`": 1,
  "bu0_j`": 1,
  "b_u0m": 1,
  "bu_0'm": 1,
  "b_u0z`": 1,
  "Bu_Bu0¡": 1,
  "bub_uoj": 1,
  "bu_o^i": 1,
  "bU_O^J`": 1,
  "bu_o^'m": 1,
  "bu_O^y`": 1,
  "bu_oi": 1,
  "bu_oi^": 1,
  "bu_oi`": 1,
  "bu_oj": 1,
  "b_uoj`": 1,
  "bu_om": 1,
  "bu_o'm": 1,
  "bu_ôi": 1,
  "B_uôì": 1,
  "b_uồi": 1,
  "bU_ôj": 1,
  "bU_ồj": 1,
  "bu_ồy": 1,
  "buớ_m": 1,
  "bư_ớm": 1,
  "bư_m": 1,
  "BV_S": 1,
  "by_m": 1,
  "bý_m": 1,
  "c0_n dy~": 1,
  "c0n f_0`": 1,
  "c_0n m3": 1,
  "c0_n me": 1,
  "c0n m_ẹ": 1,
  "c0_n phO": 1,
  "C0nch_0": 1,
  "c0n_g s4n": 1,
  "c4_v3": 1,
  "c4_ve": 1,
  "c_a_c": 1,
  "c_Ac": 1,
  "c_ạc": 1,
  "C_ạ̈c": 1,
  "C_ac_": 1,
  "c_ac_": 1,
  "cai d_is": 1,
  "c_ai' dis": 1,
  "cái d_is": 1,
  "cAi DK_M": 1,
  "c_ai' loz": 1,
  "cailo_z": 1,
  "caj di_s": 1,
  "caj dj_jt me": 1,
  "ca_j DKM": 1,
  "c_aj loz": 1,
  "caj lo_zl": 1,
  "ca_j…Đị†": 1,
  "ca_k": 1,
  "cA_M IồN": 1,
  "ca_v3": 1,
  "ca_ve": 1,
  "că_c": 1,
  "c_ặc": 1,
  "cặ_ç": 1,
  "Ç_ăç": 1,
  "C_ăk": 1,
  "cặ_k": 1,
  "c_ec_": 1,
  "çh_ÿm": 1,
  "C_L": 1,
  "c_ON": 1,
  "Ço_ñ": 1,
  "co_n cac": 1,
  "Çøn Ç_hǿ": 1,
  "c_on ch0": 1,
  "C_on di~": 1,
  "co_n di~": 1,
  "con die_m": 1,
  "co_n fò": 1,
  "cO_n fO`": 1,
  "con I_on`": 1,
  "co_n m3": 1,
  "con m_e": 1,
  "co_n mẹ": 1,
  "cong sa_n": 1,
  "cộn_g sản": 1,
  "çU_+t'": 1,
  "cu0n_g da^m": 1,
  "c_uc'": 1,
  "cuc g_a`": 1,
  "Ç_ứ†": 1,
  "C_ứt": 1,
  "Ch_0́": 1,
  "CH_0\'\'": 1,
  "c_h0'": 1,
  "ch0 g_hE dis": 1,
  "ch0 Su_a": 1,
  "ch_0_": 1,
  "Ch_0'a": 1,
  "ch_ém": 1,
  "Ch_et": 1,
  "CH_IM": 1,
  "CHI_M": 1,
  "chj_m": 1,
  "ch_ó": 1,
  "ch_o'": 1,
  "chO kO_n bu'": 1,
  "ch_o\"": 1,
  "Ch_ui": 1,
  "ch_uj": 1,
  "ch_uj?": 1,
  "ch_uj~": 1,
  "ch_uYm": 1,
  "C_hửi__": 1,
  "Ch_ym": 1,
  "ch_ym": 1,
  "d_!t": 1,
  "D!_t": 1,
  "D!_TL": 1,
  "D_yt": 1,
  "D_¥¶¯": 1,
  "D†C_M": 1,
  "d_0g": 1,
  "d_1~": 1,
  "d1_t": 1,
  "dá_¡": 1,
  "d_ai'": 1,
  "d_aj": 1,
  "d_áj": 1,
  "da_j'": 1,
  "da_mn": 1,
  "dang ha_ng": 1,
  "dạn_g háng": 1,
  "d_Âm": 1,
  "dc_m": 1,
  "de_0": 1,
  "d_e0'": 1,
  "de_0\"": 1,
  "d_e0`": 1,
  "de_0~": 1,
  "d_ek": 1,
  "DE_K'": 1,
  "de_o": 1,
  "d_e'o": 1,
  "D_eó": 1,
  "d_éo": 1,
  "De_O'": 1,
  "D_EO": 1,
  "de_o'": 1,
  "de_O' iA?": 1,
  "de_o kut'": 1,
  "d_eo\"": 1,
  "d_et m3": 1,
  "d_Et_ mE_": 1,
  "d_ey the'": 1,
  "d_ĩ": 1,
  "D_-ĩ": 1,
  "d_i_S": 1,
  "d_i_t": 1,
  "d_i~": 1,
  "D_ï§": 1,
  "d_i†": 1,
  "d_ị†": 1,
  "d_ï†": 1,
  "di_en": 1,
  "D-i_ếm": 1,
  "d_iit": 1,
  "di_s": 1,
  "d_ïs": 1,
  "D_IS'": 1,
  "d_is": 1,
  "dis c0n m_e": 1,
  "dis c_0n mje": 1,
  "DIS CO_0N ME": 1,
  "di_s cu": 1,
  "Dis K0_n Me": 1,
  "d_is k_u": 1,
  "di_s m_e": 1,
  "Di_s m_e_": 1,
  "di_S m_e_": 1,
  "D_is m_e…": 1,
  "Di_s_": 1,
  "d_is_": 1,
  "Di_sd": 1,
  "dis_me": 1,
  "dis_s m3": 1,
  "Dis_s Me": 1,
  "d_isss": 1,
  "d_it": 1,
  "d_i't": 1,
  "Dị_t": 1,
  "di_x": 1,
  "di_z": 1,
  "d_z": 1,
  "d_j": 1,
  "d_j~": 1,
  "d_j†": 1,
  "dj_E^m'": 1,
  "dj_e^'m": 1,
  "dj_em": 1,
  "dj_em'": 1,
  "D_jf": 1,
  "D_jit": 1,
  "D_jj~": 1,
  "djj_t": 1,
  "Dj_s": 1,
  "d_jx": 1,
  "D_jz": 1,
  "D_K": 1,
  "d_K_": 1,
  "dK_m": 1,
  "D_lT": 1,
  "d_m": 1,
  "do_et_": 1,
  "D_ú": 1,
  "d_ụ": 1,
  "d_u m3": 1,
  "du m_a": 1,
  "du m_á": 1,
  "du m_e maj`": 1,
  "d_u_": 1,
  "d_u_ Me_": 1,
  "du` mo_a' an kut'": 1,
  "du_k_": 1,
  "duon_g vat": 1,
  "D_UYT": 1,
  "du_yt": 1,
  "D_Ÿ Ḿ": 1,
  "d_y_t": 1,
  "D_y_t": 1,
  "d_y`n": 1,
  "d_Y~": 1,
  "dy~ de_o' daj traj": 1,
  "d_ys": 1,
  "dyS m_jE": 1,
  "d_yt": 1,
  "dY_t'": 1,
  "dY_t": 1,
  "d_yt'": 1,
  "Dyt B_uoj ": 1,
  "dyt c_0n m3": 1,
  "dỵt c0_n me": 1,
  "dyt cai I0_ng c0ng l0z": 1,
  "dy_t dyt": 1,
  "Dyt K0_an": 1,
  "dYT k_0n m3": 1,
  "d_yt kon me": 1,
  "dyt kon m_e kaj\'\' loz`": 1,
  "dyt k_on me sock": 1,
  "Dy_t ku_": 1,
  "dyt l0_z": 1,
  "dy_t m": 1,
  "D_Yt m3": 1,
  "Dyt m_3 an Kuz": 1,
  "dyt m_e": 1,
  "D_yt Me": 1,
  "dYt m_E nUnG l0zl": 1,
  "dyt m_e thagfo`": 1,
  "dyt _mE_": 1,
  "Dyt _me_": 1,
  "dY_t mJe": 1,
  "Đ_!†": 1,
  "Đ_¡§": 1,
  "Đ_¡†": 1,
  "đ_¡̣†": 1,
  "Đ_¡•t": 1,
  "Đ_¡̣t": 1,
  "đ¥_†": 1,
  "Đ_¥̣†": 1,
  "Đ_¥t": 1,
  "Đ¥̣_T": 1,
  "Đ€́_ø": 1,
  "Đ_µ": 1,
  "đ_µ̣": 1,
  "Đµ̣_ Møª́": 1,
  "Đµ́_†": 1,
  "Đ†ç_m": 1,
  "đ_ái": 1,
  "đả_ng": 1,
  "đc_m": 1,
  "đ_é0": 1,
  "Đe_ó": 1,
  "đ_éo": 1,
  "Đ_ĩ": 1,
  "Đ_ï": 1,
  "Đĩ Đ_ựç": 1,
  "Đ_i†": 1,
  "Đ_ị†": 1,
  "đị̈_†": 1,
  "đi†Çâ_ñAñh": 1,
  "Đi†m_ẹ": 1,
  "Đi_Ếm": 1,
  "đi_ên": 1,
  "Đ_iĩ": 1,
  "Đ_is": 1,
  "Đị_s": 1,
  "Đ_is Mẹ": 1,
  "Đ_it": 1,
  "Đ_ịt": 1,
  "Đ_it M3_": 1,
  "Đi_t mẹ": 1,
  "Đ_ịt me": 1,
  "Đ_ịt mẹ": 1,
  "Đ_ịt_": 1,
  "Địt_ Đ_ỳn": 1,
  "Đ_ịt___": 1,
  "đ_iz": 1,
  "Đ_î†̣": 1,
  "Đị̂_†": 1,
  "Đ_ị̂†…mẹ": 1,
  "Đ_ị̂t": 1,
  "Đ_j̃": 1,
  "đ_J†": 1,
  "đ_jếm": 1,
  "đjế_m ": 1,
  "đj_t": 1,
  "Đ_j̣t": 1,
  "đk_lm": 1,
  "Đk_m": 1,
  "ĐK_M": 1,
  "đl_t": 1,
  "Đ_m": 1,
  "đ_u": 1,
  "Đ_ụ": 1,
  "Đ_ụ mẹ": 1,
  "Đ_ỹ": 1,
  "Đ_ÿ§": 1,
  "Đy_†": 1,
  "Đ_ÿ†": 1,
  "Đỵ̈_†": 1,
  "Đ_y†": 1,
  "Đỵ† k_ụ": 1,
  "Đ_Ỵ̈† m€̣": 1,
  "Đ_ys…": 1,
  "Đ_yt": 1,
  "Đ_ỴT": 1,
  "Đ_Ÿt": 1,
  "đ_Yt": 1,
  "đ_yṭ mẹ": 1,
  "Đ_yt me_": 1,
  "đy_t_": 1,
  "Đ_yz": 1,
  "f`_O`": 1,
  "ƒµ¢_¶«": 1,
  "Fµ_ck": 1,
  "ƒµ_ck": 1,
  "ƒµ_çk": 1,
  "f_0": 1,
  "ƒ_0": 1,
  "ƒ_0ƒ": 1,
  "f_ho`": 1,
  "f_o": 1,
  "F_ò": 1,
  "f_ö̀": 1,
  "f_ø̀": 1,
  "ƒ_o": 1,
  "ƒ_ò": 1,
  "ƒ_ø̀": 1,
  "f_o`": 1,
  "ƒ_o`": 1,
  "f_oo`": 1,
  "ƒu_c¶«": 1,
  "fu_ck": 1,
  "ƒu_ck": 1,
  "ƒü_çk": 1,
  "Fu_uck": 1,
  "gh_e?": 1,
  "gie? Ra_ch'": 1,
  "ha_m~ Ion": 1,
  "h_am~ loz": 1,
  "ham~ lo_zl": 1,
  "ha_m~ lozn`": 1,
  "ha_mloz": 1,
  "hc_m": 1,
  "hi_3p": 1,
  "hi_3'p": 1,
  "hi_e'p": 1,
  "hie_p'": 1,
  "h_iếp": 1,
  "hiê_p'": 1,
  "hj_ep": 1,
  "H_L`": 1,
  "ho ch_i minh": 1,
  "hồ ch_í minh": 1,
  "i_tnh_au": 1,
  "I^0_N": 1,
  "I_0^k`": 1,
  "I_0`n": 1,
  "I_0`n`": 1,
  "I0_n": 1,
  "I_0n`": 1,
  "I_0z": 1,
  "i_ạ": 1,
  "ỉ_a": 1,
  "I_O^`n": 1,
  "I_o^n": 1,
  "I_O^-n": 1,
  "I_o^n`": 1,
  "IO_^n`": 1,
  "I_o^ng": 1,
  "I_o`n": 1,
  "Io_`n": 1,
  "I_on": 1,
  "Io_n`": 1,
  "Io_n` me": 1,
  "Io_n`_ Dis": 1,
  "I_oZ": 1,
  "I_oz": 1,
  "I_oz`": 1,
  "Io_z`": 1,
  "Iô_n": 1,
  "I_ồn": 1,
  "Iồ_ñ": 1,
  "I_ồñ": 1,
  "Iô_n`": 1,
  "Iô_ng": 1,
  "ị_t": 1,
  "j_a?": 1,
  "k_0n": 1,
  "k0_n cac": 1,
  "K0_n Ch0": 1,
  "k0n c_h0 an cuc'": 1,
  "k0n m_0e_ mAj": 1,
  "k0n m_3": 1,
  "k0n m_e": 1,
  "k0n m_e maj": 1,
  "K3 M_3": 1,
  "k4_v3": 1,
  "k4_ve": 1,
  "kaj d_yt mE": 1,
  "K_aj' dYt_ mE": 1,
  "ka_k": 1,
  "k_at ku": 1,
  "ka_v3": 1,
  "ka_ve": 1,
  "k_ăc": 1,
  "k_ặc": 1,
  "k_ặç": 1,
  "k_it'": 1,
  "K_LM": 1,
  "K_on": 1,
  "ko_n DKM": 1,
  "ko_n ch0'": 1,
  "k_on cho'": 1,
  "k_on dj?": 1,
  "Ko_n Dkm": 1,
  "KO_N DY~": 1,
  "ko_n f0": 1,
  "k_on kac": 1,
  "kon k_ak": 1,
  "kO_n ky~": 1,
  "k_on m3": 1,
  "kon m_e": 1,
  "ko_n mẹ": 1,
  "kote_x": 1,
  "K_u": 1,
  "k_ụ": 1,
  "K_u*'t": 1,
  "kU_+t'": 1,
  "k_uc'": 1,
  "k_uc kut": 1,
  "K_UT": 1,
  "k_ut'": 1,
  "ku_t ch0": 1,
  "ku_t het": 1,
  "K_ut nat": 1,
  "K_uz": 1,
  "K_uz'": 1,
  "K_ứ†": 1,
  "Kứ_†…Çhó": 1,
  "K_ưt'": 1,
  "K_ưt́": 1,
  "k_ứt": 1,
  "kY_nh nguye^T_": 1,
  "kh_ìn": 1,
  "kh_jn`": 1,
  "kho_viIon": 1,
  "l do_g": 1,
  "l t_o": 1,
  "L_`": 1,
  "l_0^n`": 1,
  "l0_^z`": 1,
  "L_0`z": 1,
  "l0_n": 1,
  "l0o_n": 1,
  "l0_x": 1,
  "l_0z": 1,
  "l0_z`": 1,
  "l0z` me_j": 1,
  "l0_zl": 1,
  "l0_zl`": 1,
  "l0_zn": 1,
  "l0_zn`": 1,
  "l0_zz": 1,
  "La Li_em": 1,
  "lA ph_o`": 1,
  "la_m` fo`": 1,
  "li3_m": 1,
  "l_i3'm": 1,
  "lie^M: lolz` m_ek lolz`": 1,
  "li_e'm": 1,
  "LIE_M'": 1,
  "Lie_m I0n ch0": 1,
  "li'_m": 1,
  "lí_m": 1,
  "li_n`": 1,
  "l_jn": 1,
  "lj_n`": 1,
  "L_M": 1,
  "l_O^`n": 1,
  "L_o^lz`": 1,
  "l_o^n": 1,
  "l_o^n`": 1,
  "l_o^z": 1,
  "l_O^z`": 1,
  "lo^z_n`": 1,
  "lo_`n": 1,
  "l_O+i`": 1,
  "LO_0^N`": 1,
  "lo_0n`": 1,
  "lo_iz": 1,
  "l_ol": 1,
  "lO_lz": 1,
  "lo_n": 1,
  "l_Ön": 1,
  "lo_n'": 1,
  "l_on`": 1,
  "lo_on": 1,
  "loo_n`": 1,
  "lo_z": 1,
  "l_öz": 1,
  "lo_z`": 1,
  "L_ozl": 1,
  "lo_zl`": 1,
  "lo_zn": 1,
  "L_ô`n": 1,
  "lÔ_lz": 1,
  "lô_n": 1,
  "l_ôñ": 1,
  "L_ôñ̀": 1,
  "L_ồn": 1,
  "lồ_ñ": 1,
  "Lô_ǹ": 1,
  "lô_n`": 1,
  "l_ồnz": 1,
  "l_ồz": 1,
  "lu_`n": 1,
  "Lu_`n": 1,
  "Lu~ d_0g": 1,
  "lu~ re ra_ck:": 1,
  "lu~d_og": 1,
  "Lũ…Dog H_úp…Máu": 1,
  "lua ti_nh": 1,
  "lu_n`": 1,
  "luoj~ tat' va_`o dau` buoj`": 1,
  "lz_0`": 1,
  "lz_0n`": 1,
  "lz_o`": 1,
  "lZ_O`l": 1,
  "lz_ol": 1,
  "lz_ol`": 1,
  "lz_ồn": 1,
  "m€̣ m_Aj`": 1,
  "m_0m~": 1,
  "m_3": 1,
  "m3 ma_i": 1,
  "m_A(t_ lOz": 1,
  "ma_u' Io`n": 1,
  "m_au' Ion": 1,
  "ma_u L": 1,
  "m_au l0z": 1,
  "ma_u lol": 1,
  "m_au loz": 1,
  "ma_u non`": 1,
  "M_Ay`": 1,
  "m_e": 1,
  "M_ẹ": 1,
  "M_ẹ̈": 1,
  "m_e chu_ng maj": 1,
  "m_e m_ai": 1,
  "m_e m_aj": 1,
  "me_ Ma_j`": 1,
  "me_t loz": 1,
  "m_I": 1,
  "M_ịe": 1,
  "mi_e_": 1,
  "m_je": 1,
  "M_L": 1,
  "m_l": 1,
  "M_L`": 1,
  "m_l`": 1,
  "mo_^m loz": 1,
  "m_õm": 1,
  "Mo_m~": 1,
  "mo_m~ dog lu~ ch0": 1,
  "m_ú†": 1,
  "m_ut": 1,
  "mú_t": 1,
  "m_ut'": 1,
  "m_ut bi0i": 1,
  "mut b_u0j": 1,
  "m_ut ku": 1,
  "m_ut' lz0n`": 1,
  "Ñ_§ü": 1,
  "Ñ_gậm…ßµồ¡": 1,
  "ni_ém": 1,
  "nj_n`": 1,
  "n_o^n`": 1,
  "n_o`n": 1,
  "no_n": 1,
  "n_on^`": 1,
  "no_n`": 1,
  "n_ôn": 1,
  "n_ồn": 1,
  "N_ồñ": 1,
  "Ñ_ồñ": 1,
  "Nồ_n": 1,
  "Ñ_ôǹ": 1,
  "nỒ_z": 1,
  "n_u*ng'": 1,
  "nU_n`": 1,
  "nu_ng*' loz`": 1,
  "nứ_ng": 1,
  "ng_u": 1,
  "n_h0n`": 1,
  "nh_a` may`": 1,
  "n_ho^n`": 1,
  "nh_u cac": 1,
  "N_huc̣…": 1,
  "nh_uk": 1,
  "p_3`": 1,
  "p_à": 1,
  "p_A`": 1,
  "pa` m_ay`": 1,
  "pe_nis": 1,
  "playk_u": 1,
  "pó c_u": 1,
  "po k_u": 1,
  "pó k_u": 1,
  "po ma_y`": 1,
  "p_o\"": 1,
  "p_o`": 1,
  "P_uoi`": 1,
  "pu_ồj": 1,
  "Ph_`o": 1,
  "p_h0`": 1,
  "ph_a^n": 1,
  "ph_an^": 1,
  "ph_ân": 1,
  "ph_ò": 1,
  "p_ho`": 1,
  "ra_ck": 1,
  "R_áçk": 1,
  "r_ai'": 1,
  "ra_pe": 1,
  "re r_ack": 1,
  "rẻ ra_cḱ": 1,
  "s0_ck k0n me": 1,
  "S_elit": 1,
  "se_x": 1,
  "sh_1t": 1,
  "sh_it": 1,
  "s_ip": 1,
  "sk_m": 1,
  "sO_ck": 1,
  "so_cl": 1,
  "ß_µ́": 1,
  "ßµ_ô¡": 1,
  "ßµ_ồ¡": 1,
  "ßµ_ồ¡¯": 1,
  "ßµ_ồ¿": 1,
  "ß_µồi": 1,
  "ß_µồï": 1,
  "ß_µồi¯": 1,
  "ßµ_ôî": 1,
  "ß_µồî": 1,
  "ß_ố": 1,
  "ßu_oi": 1,
  "ßu_oj": 1,
  "ß_uoj`": 1,
  "ßu_om": 1,
  "ß_uồi": 1,
  "ß_ựa": 1,
  "ßư_ớm": 1,
  "su_a?": 1,
  "s_uc vaT": 1,
  "t_bc": 1,
  "t_bs": 1,
  "Tie_n Su": 1,
  "Tu_oi? Io`n": 1,
  "tYnh tru_G`": 1,
  "tha_ng fo": 1,
  "thang p_ho": 1,
  "th_ang` fo": 1,
  "thoi k_en": 1,
  "thủ d_âm": 1,
  "thủ z_âm": 1,
  "thu_? za^m": 1,
  "tr1_nh": 1,
  "tri_nh": 1,
  "trj_nh": 1,
  "t_rlnh": 1,
  "tr_o'": 1,
  "tr_o\"": 1,
  "t_rym": 1,
  "try_nh": 1,
  "v_åi": 1,
  "v_kc": 1,
  "v_kl": 1,
  "v_l": 1,
  "v_ú": 1,
  "tư b_ản đỏ": 1,
  "tub_ando": 1,
  "tu b_an do": 1,
  "tư_bản": 1,
  "xã hội ch_ũ nghĩa": 1,
  "xahoic_hunghia": 1,
  "xã hoich_unghia": 1,
  "sã hội chũ ng_hĩa": 1,
  "xa hội chu_nghia": 1,
  "xahoi ch_ủ nghia": 1,
  "xahoic_hu nghĩa": 1,
  "tư bản ch_ủ nghĩa": 1,
  "tubanchu_nghia": 1,
  "tu ban ch_u nghia": 1,
  "tưbản_chủnghĩa": 1,
  "sã_hộichũnghĩa": 1,
  "xãhội_chũnghĩa": 1,
  "an-ca-c": 1,
  "anc-ac": 1,
  "ăn c-ặc": 1,
  "ăn-cặc": 1,
  "ba-ma-y": 1,
  "bà m-ày": 1,
  "ba m-ày": 1,
  "bà-may": 1,
  "ba-mày": 1,
  "bàm-ày": 1,
  "bac-h-o": 1,
  "ba-may": 1,
  "ban-d-am": 1,
  "ban-ho-a": 1,
  "banda-m": 1,
  "ba-nhoa": 1,
  "bán-hoa": 1,
  "bit-ch": 1,
  "bo-ma-y": 1,
  "bo-may": 1,
  "bon-ch-o": 1,
  "bon-kh-on-nan": 1,
  "bonc-ho": 1,
  "bonk-honnan": 1,
  "bre-ast": 1,
  "buc-ac": 1,
  "bu-oi": 1,
  "bu-ồi": 1,
  "buo-m": 1,
  "b-ướm": 1,
  "c-san": 1,
  "cạ-c": 1,
  "cặ-c": 1,
  "cai-bu-oi": 1,
  "cai-ch-im": 1,
  "cai-c-u": 1,
  "cai-lo-n": 1,
  "caib-uoi": 1,
  "caic-him": 1,
  "ca-icu": 1,
  "cail-on": 1,
  "ca-ve": 1,
  "ch-im": 1,
  "chi-m-to": 1,
  "chi-mto": 1,
  "ch-ó": 1,
  "cho-ch-et": 1,
  "c-ho-kin": 1,
  "cho-chet": 1,
  "chok-in": 1,
  "con-c-ho": 1,
  "c-on-cu": 1,
  "c-on-cu-cac": 1,
  "con-cu-to-tu-ong": 1,
  "c-on-di": 1,
  "con-die-m": 1,
  "con-ph-o": 1,
  "conc-ho": 1,
  "con-cu": 1,
  "con-cucac": 1,
  "concuto-tuong": 1,
  "co-ndi": 1,
  "condie-m": 1,
  "cong-hoa": 1,
  "co-ng-san": 1,
  "cong-san": 1,
  "conl-on": 1,
  "conp-ho": 1,
  "cs-an": 1,
  "c-ụ": 1,
  "cu-ca-c": 1,
  "cu-h-o": 1,
  "cu-m-ay": 1,
  "cu-t-o": 1,
  "cuc-ca-c": 1,
  "cuc-c-ut": 1,
  "cu-cac": 1,
  "cucca-c": 1,
  "cuc-cut": 1,
  "cu-ho": 1,
  "cu-may": 1,
  "cu-nt": 1,
  "cuo-ng-dam": 1,
  "cuon-g-hiep": 1,
  "cuon-gdam": 1,
  "cuo-nghiep": 1,
  "c-ứt": 1,
  "cut-o": 1,
  "đ-ái": 1,
  "dâ-m": 1,
  "da-n-chu": 1,
  "dan-chu": 1,
  "da-ng-c-s": 1,
  "da-ng-cong-san": 1,
  "dang-cong-san": 1,
  "da-ng-cs": 1,
  "da-ng-tien-tri": 1,
  "dan-g-tientri": 1,
  "dang-congsan": 1,
  "dang-cs": 1,
  "dang-tien-tri": 1,
  "da-ngtientri": 1,
  "dc-m": 1,
  "đc-m": 1,
  "đ-ĩ": 1,
  "điế-m": 1,
  "di-s-me": 1,
  "di-sme": 1,
  "d-it": 1,
  "dị-t": 1,
  "đí-t": 1,
  "đị-t": 1,
  "d-it-bo": 1,
  "di-t-con-cu": 1,
  "dit-co-n-me": 1,
  "dit-c-oncu": 1,
  "dit-con-me": 1,
  "d-it-cu": 1,
  "dit-cu-m-ay": 1,
  "dit-m-e": 1,
  "dit-o-ng": 1,
  "dit-ba": 1,
  "d-itbo": 1,
  "dit-me": 1,
  "ditm-e": 1,
  "ditm-emay": 1,
  "dito-ng": 1,
  "d-m": 1,
  "đ-m": 1,
  "doco-ncho": 1,
  "do-khon": 1,
  "d-rug": 1,
  "d-ụ": 1,
  "đ-ụ": 1,
  "du-m-a": 1,
  "d-ục": 1,
  "du-ma": 1,
  "du-me": 1,
  "fu-ck": 1,
  "gai-b-an-hoa": 1,
  "gai-die-m": 1,
  "Gaiban-hoa": 1,
  "Gaid-iem": 1,
  "h-am-hiep": 1,
  "Hamh-iep": 1,
  "ha-nh-kinh": 1,
  "Ha-nhkinh": 1,
  "Hiế-p": 1,
  "hiep-da-m": 1,
  "Hiepda-m": 1,
  "ho-chi-mi-nh": 1,
  "hồ-chí-m-inh": 1,
  "ho-chim-inh": 1,
  "hochi-m-inh": 1,
  "Hochi-minh": 1,
  "I-ả": 1,
  "Ỉ-a": 1,
  "K-hốn": 1,
  "kho-n-nan": 1,
  "Kho-nnan": 1,
  "khu-ng-bo": 1,
  "Kh-ungbo": 1,
  "Ki-ep": 1,
  "Ki-ép": 1,
  "kiế-p": 1,
  "la-m-tinh": 1,
  "lam-tinh": 1,
  "lie-m-cac": 1,
  "lie-mcac": 1,
  "lì-n": 1,
  "lo-n": 1,
  "l-òn": 1,
  "lồ-n": 1,
  "lợ-n": 1,
  "lo-n-to": 1,
  "lo-ng-lon": 1,
  "lo-nglon": 1,
  "lo-nto": 1,
  "lu-ch-o": 1,
  "lu-k-hon": 1,
  "luc-ho": 1,
  "luk-hon": 1,
  "mau-k-inh": 1,
  "m-au-lon": 1,
  "mauki-nh": 1,
  "mau-lon": 1,
  "m-ẹ": 1,
  "m-e-kiep": 1,
  "me-m-ay": 1,
  "me-kiep": 1,
  "me-may": 1,
  "mi-e": 1,
  "moha-met": 1,
  "mua-da-m": 1,
  "mua-dam": 1,
  "mu-t-cac": 1,
  "mu-tbuoi": 1,
  "mut-cac": 1,
  "na-ke": 1,
  "ngu-yen-ai-quoc": 1,
  "nguy-en-aiquoc": 1,
  "nguyen-ai-quoc": 1,
  "nguyen-aiquoc": 1,
  "nguyenaiq-uoc": 1,
  "ong-m-ay": 1,
  "ongm-ay": 1,
  "pen-is": 1,
  "ph-ò": 1,
  "pim-p": 1,
  "rap-e": 1,
  "s-h-i-t": 1,
  "se-x": 1,
  "sh-it": 1,
  "sin-h-duc": 1,
  "sin-hduc": 1,
  "sl-ut": 1,
  "so-lo-n": 1,
  "s-olon": 1,
  "su-bo-ma-y": 1,
  "subo-may": 1,
  "th-ang-cho": 1,
  "than-gcho": 1,
  "tie-n-su": 1,
  "tien-su": 1,
  "tinh-du-c": 1,
  "tin-hduc": 1,
  "to-s-u": 1,
  "to-su": 1,
  "v-co-ng": 1,
  "vai-da-i": 1,
  "v-ai-leu": 1,
  "v-ai-lin": 1,
  "va-i-lon": 1,
  "vaida-i": 1,
  "va-ileu": 1,
  "vaili-n": 1,
  "va-ilon": 1,
  "vco-ng": 1,
  "viet-co-ng": 1,
  "1-ồn": 1,
  "1-Ồn": 1,
  "1ồ-N": 1,
  "1-0n": 1,
  "1-0`n": 1,
  "1`0-n": 1,
  "1-o`n": 1,
  "1Ồ-N": 1,
  "-Ba-cHo-": 1,
  "-Bac-Ho-": 1,
  "-Ba-cho-": 1,
  "-b-acHo-": 1,
  "-bAc-Ho-": 1,
  "ba-c-ho": 1,
  "B-ac-ho": 1,
  "b-ac-Ho": 1,
  "Ba-c-Ho": 1,
  "B-ác Hồ": 1,
  "b-ác Hồ": 1,
  "B-ác hồ": 1,
  "bá-c hồ": 1,
  "b-Ác Hồ": 1,
  "bÁ-c hỒ": 1,
  "bá-C Hồ": 1,
  "b4-c Hồ": 1,
  "b4c h-Ồ": 1,
  "b'-4c Hồ": 1,
  "b'4-c hỒ": 1,
  "b4'-c Hồ": 1,
  "b4'-c hỒ": 1,
  "ba-c h0": 1,
  "B-ac h0": 1,
  "bac H-0": 1,
  "B-ac H0": 1,
  "b-itch": 1,
  "BIT-CH": 1,
  "Bi-tch": 1,
  "Bu-oi": 1,
  "bu-oi`": 1,
  "B-uoi`": 1,
  "b-uồi": 1,
  "Bu-ồi": 1,
  "b-u0`i": 1,
  "Bu-0`i": 1,
  "bu-Ồi": 1,
  "Bu-Ồi": 1,
  "congs-an": 1,
  "co-ng san": 1,
  "Cong- san": 1,
  "co-ng San": 1,
  "Con-g San": 1,
  "cộn-g sản": 1,
  "cộn-g Sản": 1,
  "Cộn-g sản": 1,
  "Con-gsan": 1,
  "Con-gSan": 1,
  "cuh-o": 1,
  "Cu-ho": 1,
  "cuH-o": 1,
  "CuH-o": 1,
  "c-uh0": 1,
  "Cuh-0": 1,
  "cu-H0": 1,
  "Cu-H0": 1,
  "Cu-h-o": 1,
  "cU-h-o": 1,
  "cu--Ho": 1,
  "cu-h-O": 1,
  "c-ụ hồ": 1,
  "Cụ h-ồ": 1,
  "cỤ h-ồ": 1,
  "cụ H-ồ": 1,
  "cụ h-Ồ": 1,
  "c-a--c": 1,
  "C-a--c": 1,
  "c-A--c": 1,
  "C-A--c": 1,
  "C-A--C": 1,
  "c4-c": 1,
  "C-4c": 1,
  "C4-C": 1,
  "ca-c-": 1,
  "C-ac-": 1,
  "c-Ac-": 1,
  "C-AC-": 1,
  "că-c-": 1,
  "C-ăc-": 1,
  "cĂ-c-": 1,
  "C-Ăc-": 1,
  "CĂ-C-": 1,
  "c-ặc": 1,
  "C-ặc": 1,
  "c-Ặc": 1,
  "CẶ-c": 1,
  "C-ẶC": 1,
  "cav-e": 1,
  "Ca-ve": 1,
  "cA-ve": 1,
  "CA-VE": 1,
  "c-Ave": 1,
  "C-ứt": 1,
  "c-Ứt": 1,
  "C-ỨT": 1,
  "C-Ứt": 1,
  "d-1t": 1,
  "D1-t": 1,
  "D-1T": 1,
  "d-ai'": 1,
  "Da-i'": 1,
  "dA-i'": 1,
  "D-AI'": 1,
  "d-ái": 1,
  "đá-i": 1,
  "Đ-ái": 1,
  "Đ-ÁI": 1,
  "d-âm": 1,
  "dÂ-m": 1,
  "dam-n": 1,
  "DAM-N": 1,
  "DC-M": 1,
  "ĐC-M": 1,
  "Đc-M": 1,
  "Đc-m": 1,
  "Đ-ĩ": 1,
  "đ-i~": 1,
  "Đ-i~": 1,
  "Đ-Ĩ": 1,
  "Đ-I~": 1,
  "d-i~": 1,
  "D-ĩ": 1,
  "D-I~": 1,
  "d-i-t": 1,
  "D-i-t": 1,
  "d-I-t": 1,
  "D-I-T": 1,
  "đ-i-t": 1,
  "Đ-i-t": 1,
  "Đ-I-T": 1,
  "đ-Ịt": 1,
  "Đ-ịt": 1,
  "Đ-ịT": 1,
  "Đ-ỊT": 1,
  "d-is": 1,
  "D-is": 1,
  "d-iS": 1,
  "đi-s": 1,
  "Đ-is": 1,
  "đi-t": 1,
  "D-it": 1,
  "Đ-it": 1,
  "DI-T": 1,
  "ĐI-T": 1,
  "đi-ếm": 1,
  "Đi-ếm": 1,
  "điẾ-m": 1,
  "Đi-Ếm": 1,
  "ĐiẾ-M": 1,
  "D-m": 1,
  "D-M": 1,
  "Đ-m": 1,
  "Đ-M": 1,
  "dm-m": 1,
  "đm-m": 1,
  "Dm-m": 1,
  "Đm-m": 1,
  "DM-M": 1,
  "ĐM-M": 1,
  "Đ-cm": 1,
  "đC-M": 1,
  "đcm-m": 1,
  "dk-m": 1,
  "đk-m": 1,
  "d-cm": 1,
  "dk-mm": 1,
  "đk-mm": 1,
  "đ-Ụ": 1,
  "Đ-Ụ": 1,
  "đ-u-": 1,
  "Đ-u-": 1,
  "Đ-U-": 1,
  "F-uck": 1,
  "FU-CK": 1,
  "f-u--c-k": 1,
  "F-U-C--K": 1,
  "G4m-eMaster": 1,
  "G4me-M4ster": 1,
  "G4me-Ma-ster": 1,
  "G4me-M4s-ter": 1,
  "G4-me*Master": 1,
  "G4m-e*M4ster": 1,
  "Ga-meMaster": 1,
  "Gam-e-Master": 1,
  "[Game]-Master": 1,
  "Game*M-aster": 1,
  "Game[M-aster]": 1,
  "G-M": 1,
  "[G]-M": 1,
  "G-[M]": 1,
  "G--M": 1,
  "G*-M": 1,
  "Hồ chí m-inh": 1,
  "HỒ c-hí minh": 1,
  "hồ C-hí minh": 1,
  "hồ chí Mi-nh": 1,
  "Hồ ch-í Minh": 1,
  "h-ồ Chí minh": 1,
  "hồ ch-í minh": 1,
  "hochi-minh": 1,
  "HoCh-iMinh": 1,
  "HOCH-IMINH": 1,
  "ho-ch-i-minh": 1,
  "Ho-Ch-i-Minh": 1,
  "ho ch-i minh": 1,
  "Ho C-hi Minh": 1,
  "HO C-HI MINH": 1,
  "hi-ếp": 1,
  "Hi-ếp": 1,
  "HI-ẾP": 1,
  "lo-`n": 1,
  "L-o`n": 1,
  "lo-n`": 1,
  "L-on`": 1,
  "Lồ-n": 1,
  "lô-n": 1,
  "L-ôn": 1,
  "LÔ-N": 1,
  "L-ỒN": 1,
  "l-Ồn": 1,
  "m-k": 1,
  "M-k": 1,
  "M-K": 1,
  "nông đứ-c mạnh": 1,
  "Nông -Đức Mạnh": 1,
  "nongduc-manh": 1,
  "NONG-DUCMANH": 1,
  "PE-NIS": 1,
  "Phạ-m Văn Đồng": 1,
  "phạm vă-n đồng": 1,
  "phamvand-ong": 1,
  "PHAM-VANDONG": 1,
  "Ph-ò": 1,
  "ph-Ò": 1,
  "PH-Ò": 1,
  "p-ho`": 1,
  "Ph-o`": 1,
  "PH-O`": 1,
  "Ra-pe": 1,
  "RA-PE": 1,
  "s-ex": 1,
  "Se-x": 1,
  "SE-X": 1,
  "sh-1t": 1,
  "Sh1-t": 1,
  "SH1-T": 1,
  "Sh-it": 1,
  "SH-IT": 1,
  "tổ-ng bí thư": 1,
  "Tổng B-í Thư": 1,
  "tongb-ithu": 1,
  "tong b-i thu": 1,
  "Vietcon-g": 1,
  "VIETC-ONG": 1,
  "viet c-ong": 1,
  "Vi-et Cong": 1,
  "VIET C-ONG": 1,
  "việt c-ông": 1,
  "Việ-t Cộng": 1,
  "VIỆT C-ỘNG": 1,
  "L-ìn": 1,
  "LÌ-N": 1,
  "li-`n": 1,
  "Li-`n": 1,
  "LI`-N": 1,
  "th-ủ dâm": 1,
  "Thủ Dâ-m": 1,
  "TH-Ủ DÂ-M": 1,
  "!ồ--n": 1,
  "£-j-n`": 1,
  "£-ô`n": 1,
  "£ô-Ñ": 1,
  "£-ồn": 1,
  "£-ồñ": 1,
  "₫-éo": 1,
  "₫-iṭ": 1,
  "₫y-t": 1,
  "y-t-": 1,
  "¶)-¡t": 1,
  "¶)-ị†": 1,
  "¶-ồ-ñ": 1,
  "¶-ơ-Ñ": 1,
  "¶-ồñ": 1,
  "†-¡ñ": 1,
  "†-€̀": 1,
  "†-ổ": 1,
  "1o-n": 1,
  "1-ôn": 1,
  "1ồ-n": 1,
  "a(n c-ac": 1,
  "a-m vat": 1,
  "an b-uoi": 1,
  "an k-ut": 1,
  "an k-uz": 1,
  "a-n loz": 1,
  "an no-^n": 1,
  "äñ-£0ñ": 1,
  "An-Loz": 1,
  "ăn bu-oi": 1,
  "b-µ́": 1,
  "Bµ0-m": 1,
  "bµ-ồi": 1,
  "b-0 cu": 1,
  "b-0 ku": 1,
  "b-3`": 1,
  "b-à": 1,
  "b-a`": 1,
  "bí-m": 1,
  "b-kl": 1,
  "bó c-u": 1,
  "bo k-u": 1,
  "b-ó ku": 1,
  "b-o^'": 1,
  "B-u'": 1,
  "b-u b": 1,
  "b-u' b": 1,
  "bu b-u0j": 1,
  "bu b-uoi": 1,
  "bu b-uoj": 1,
  "bu l-ol": 1,
  "bu' l-ol": 1,
  "bu lo-z": 1,
  "bu' lo-z": 1,
  "bu-0^j": 1,
  "bu-0+m": 1,
  "b-u0i": 1,
  "bu-0j": 1,
  "bu-0j`": 1,
  "bu0-j`": 1,
  "b-u0m": 1,
  "bu-0'm": 1,
  "b-u0z`": 1,
  "Bu-Bu0¡": 1,
  "bub-uoj": 1,
  "bu-o^i": 1,
  "bU-O^J`": 1,
  "bu-o^'m": 1,
  "bu-O^y`": 1,
  "bu-oi^": 1,
  "bu-oj": 1,
  "b-uoj`": 1,
  "bu-om": 1,
  "bu-o'm": 1,
  "bu-ôi": 1,
  "B-uôì": 1,
  "bU-ôj": 1,
  "bU-ồj": 1,
  "bu-ồy": 1,
  "buớ-m": 1,
  "bư-ớm": 1,
  "bư-m": 1,
  "BV-S": 1,
  "by-m": 1,
  "bý-m": 1,
  "c0-n dy~": 1,
  "c0n f-0`": 1,
  "c-0n m3": 1,
  "c0-n me": 1,
  "c0n m-ẹ": 1,
  "c0-n phO": 1,
  "C0nch-0": 1,
  "c0n-g s4n": 1,
  "c4-v3": 1,
  "c4-ve": 1,
  "c-a-c": 1,
  "c-Ac": 1,
  "c-ạc": 1,
  "C-ạ̈c": 1,
  "c-ac-": 1,
  "cai d-is": 1,
  "c-ai' dis": 1,
  "cái d-is": 1,
  "cAi DK-M": 1,
  "c-ai' loz": 1,
  "cailo-z": 1,
  "caj di-s": 1,
  "caj dj-jt me": 1,
  "ca-j DKM": 1,
  "c-aj loz": 1,
  "caj lo-zl": 1,
  "ca-j…Đị†": 1,
  "ca-k": 1,
  "cA-M IồN": 1,
  "ca-v3": 1,
  "că-c": 1,
  "cặ-ç": 1,
  "Ç-ăç": 1,
  "C-ăk": 1,
  "cặ-k": 1,
  "c-ec-": 1,
  "çh-ÿm": 1,
  "C-L": 1,
  "c-ON": 1,
  "Ço-ñ": 1,
  "co-n cac": 1,
  "Çøn Ç-hǿ": 1,
  "c-on ch0": 1,
  "C-on di~": 1,
  "co-n di~": 1,
  "con die-m": 1,
  "co-n fò": 1,
  "cO-n fO`": 1,
  "con I-on`": 1,
  "co-n m3": 1,
  "con m-e": 1,
  "co-n mẹ": 1,
  "cong sa-n": 1,
  "çU-+t'": 1,
  "cu0n-g da^m": 1,
  "c-uc'": 1,
  "cuc g-a`": 1,
  "Ç-ứ†": 1,
  "c-h0'": 1,
  "Ch-0́": 1,
  "CH-0\'\'": 1,
  "ch0 g-hE dis": 1,
  "ch0 Su-a": 1,
  "ch-0-": 1,
  "Ch-0'a": 1,
  "ch-ém": 1,
  "Ch-et": 1,
  "CH-IM": 1,
  "CHI-M": 1,
  "chj-m": 1,
  "ch-o'": 1,
  "chO kO-n bu'": 1,
  "ch-o\"": 1,
  "Ch-ui": 1,
  "ch-uj": 1,
  "ch-uj?": 1,
  "ch-uj~": 1,
  "ch-uYm": 1,
  "C-hửi--": 1,
  "Ch-ym": 1,
  "ch-ym": 1,
  "d-!t": 1,
  "D!-t": 1,
  "D!-TL": 1,
  "D-yt": 1,
  "D-¥¶¯": 1,
  "D†C-M": 1,
  "d-0g": 1,
  "d-1~": 1,
  "d1-t": 1,
  "dá-¡": 1,
  "d-aj": 1,
  "d-áj": 1,
  "da-j'": 1,
  "da-mn": 1,
  "dang ha-ng": 1,
  "dạn-g háng": 1,
  "d-Âm": 1,
  "de-0": 1,
  "d-e0'": 1,
  "de-0\"": 1,
  "d-e0`": 1,
  "de-0~": 1,
  "d-ek": 1,
  "DE-K'": 1,
  "de-o": 1,
  "d-e'o": 1,
  "D-eó": 1,
  "d-éo": 1,
  "de-o'": 1,
  "De-O'": 1,
  "D-EO": 1,
  "de-O' iA?": 1,
  "de-o kut'": 1,
  "d-eo\"": 1,
  "d-et m3": 1,
  "d-Et- mE-": 1,
  "d-ey the'": 1,
  "d-ĩ": 1,
  "D--ĩ": 1,
  "d-i-S": 1,
  "di-S m-e-": 1,
  "D-ï§": 1,
  "d-i†": 1,
  "d-ị†": 1,
  "d-ï†": 1,
  "di-en": 1,
  "D-i-ếm": 1,
  "d-iit": 1,
  "di-s": 1,
  "d-ïs": 1,
  "D-IS'": 1,
  "dis c0n m-e": 1,
  "dis c-0n mje": 1,
  "DIS CO-0N ME": 1,
  "di-s cu": 1,
  "Dis K0-n Me": 1,
  "d-is k-u": 1,
  "di-s m-e": 1,
  "Di-s m-e-": 1,
  "D-is m-e…": 1,
  "Di-s-": 1,
  "d-is-": 1,
  "Di-sd": 1,
  "dis-me": 1,
  "dis-s m3": 1,
  "Dis-s Me": 1,
  "d-isss": 1,
  "d-i't": 1,
  "Dị-t": 1,
  "di-x": 1,
  "di-z": 1,
  "d-z": 1,
  "d-j": 1,
  "d-j~": 1,
  "d-j†": 1,
  "dj-e^'m": 1,
  "dj-E^m'": 1,
  "dj-em": 1,
  "dj-em'": 1,
  "D-jf": 1,
  "D-jit": 1,
  "D-jj~": 1,
  "djj-t": 1,
  "Dj-s": 1,
  "d-jx": 1,
  "D-jz": 1,
  "D-K": 1,
  "d-K-": 1,
  "dK-m": 1,
  "D-lT": 1,
  "do-et-": 1,
  "D-ú": 1,
  "d-u m3": 1,
  "du m-a": 1,
  "du m-á": 1,
  "du m-e maj`": 1,
  "d-u-": 1,
  "d-u- Me-": 1,
  "du` mo-a' an kut'": 1,
  "du-k-": 1,
  "duon-g vat": 1,
  "D-UYT": 1,
  "du-yt": 1,
  "D-Ÿ Ḿ": 1,
  "d-y-t": 1,
  "D-y-t": 1,
  "d-y`n": 1,
  "d-Y~": 1,
  "dy~ de-o' daj traj": 1,
  "d-ys": 1,
  "dyS m-jE": 1,
  "d-yt": 1,
  "dY-t'": 1,
  "dY-t": 1,
  "d-yt'": 1,
  "Dyt B-uoj ": 1,
  "dyt c-0n m3": 1,
  "dỵt c0-n me": 1,
  "dyt cai I0-ng c0ng l0z": 1,
  "dy-t dyt": 1,
  "Dyt K0-an": 1,
  "dYT k-0n m3": 1,
  "d-yt kon me": 1,
  "dyt kon m-e kaj\'\' loz`": 1,
  "dyt k-on me sock": 1,
  "Dy-t ku-": 1,
  "dyt l0-z": 1,
  "dy-t m": 1,
  "D-Yt m3": 1,
  "Dyt m-3 an Kuz": 1,
  "dyt m-e": 1,
  "D-yt Me": 1,
  "dYt m-E nUnG l0zl": 1,
  "dyt m-e thagfo`": 1,
  "dyt -mE-": 1,
  "Dyt -me-": 1,
  "dY-t mJe": 1,
  "Đ-!†": 1,
  "Đ-¡§": 1,
  "Đ-¡†": 1,
  "đ-¡̣†": 1,
  "Đ-¡•t": 1,
  "Đ-¡̣t": 1,
  "đ¥-†": 1,
  "Đ-¥̣†": 1,
  "Đ-¥t": 1,
  "Đ¥̣-T": 1,
  "Đ€́-ø": 1,
  "Đ-µ": 1,
  "đ-µ̣": 1,
  "Đµ̣- Møª́": 1,
  "Đµ́-†": 1,
  "Đ†ç-m": 1,
  "đả-ng": 1,
  "đ-é0": 1,
  "Đe-ó": 1,
  "đ-éo": 1,
  "Đ-ï": 1,
  "Đĩ Đ-ựç": 1,
  "Đ-i†": 1,
  "Đ-ị†": 1,
  "đị̈-†": 1,
  "đi†Çâ-ñAñh": 1,
  "Đi†m-ẹ": 1,
  "đi-ên": 1,
  "Đ-iĩ": 1,
  "Đị-s": 1,
  "Đ-is Mẹ": 1,
  "Đ-it M3-": 1,
  "Đi-t mẹ": 1,
  "Đ-ịt me": 1,
  "Đ-ịt mẹ": 1,
  "Đ-ịt-": 1,
  "Địt- Đ-ỳn": 1,
  "Đ-ịt---": 1,
  "đ-iz": 1,
  "Đ-î†̣": 1,
  "Đị̂-†": 1,
  "Đ-ị̂†…mẹ": 1,
  "Đ-ị̂t": 1,
  "Đ-j̃": 1,
  "đ-J†": 1,
  "đ-jếm": 1,
  "đjế-m ": 1,
  "đj-t": 1,
  "Đ-j̣t": 1,
  "đk-lm": 1,
  "Đk-m": 1,
  "ĐK-M": 1,
  "đl-t": 1,
  "đ-u": 1,
  "Đ-ụ mẹ": 1,
  "Đ-ỹ": 1,
  "Đ-ÿ§": 1,
  "Đy-†": 1,
  "Đ-ÿ†": 1,
  "Đỵ̈-†": 1,
  "Đ-y†": 1,
  "Đỵ† k-ụ": 1,
  "Đ-Ỵ̈† m€̣": 1,
  "Đ-ys…": 1,
  "Đ-yt": 1,
  "Đ-ỴT": 1,
  "Đ-Ÿt": 1,
  "đ-Yt": 1,
  "đ-yṭ mẹ": 1,
  "Đ-yt me-": 1,
  "đy-t-": 1,
  "Đ-yz": 1,
  "f`-O`": 1,
  "ƒµ¢-¶«": 1,
  "Fµ-ck": 1,
  "ƒµ-ck": 1,
  "ƒµ-çk": 1,
  "f-0": 1,
  "ƒ-0": 1,
  "ƒ-0ƒ": 1,
  "f-ho`": 1,
  "f-o": 1,
  "F-ò": 1,
  "f-ö̀": 1,
  "f-ø̀": 1,
  "ƒ-o": 1,
  "ƒ-ò": 1,
  "ƒ-ø̀": 1,
  "f-o`": 1,
  "ƒ-o`": 1,
  "f-oo`": 1,
  "ƒu-c¶«": 1,
  "ƒu-ck": 1,
  "ƒü-çk": 1,
  "Fu-uck": 1,
  "gh-e?": 1,
  "gie? Ra-ch'": 1,
  "ha-m~ Ion": 1,
  "h-am~ loz": 1,
  "ham~ lo-zl": 1,
  "ha-m~ lozn`": 1,
  "ha-mloz": 1,
  "hc-m": 1,
  "hi-3p": 1,
  "hi-3'p": 1,
  "hi-e'p": 1,
  "hie-p'": 1,
  "h-iếp": 1,
  "hiê-p'": 1,
  "hj-ep": 1,
  "H-L`": 1,
  "i-tnh-au": 1,
  "I^0-N": 1,
  "I-0^k`": 1,
  "I-0`n": 1,
  "I-0`n`": 1,
  "I0-n": 1,
  "I-0n`": 1,
  "I-0z": 1,
  "i-ạ": 1,
  "ỉ-a": 1,
  "I-O^`n": 1,
  "I-o^n": 1,
  "I-O^-n": 1,
  "I-o^n`": 1,
  "IO-^n`": 1,
  "I-o^ng": 1,
  "I-o`n": 1,
  "Io-`n": 1,
  "I-on": 1,
  "Io-n`": 1,
  "Io-n` me": 1,
  "Io-n`- Dis": 1,
  "I-oZ": 1,
  "I-oz": 1,
  "I-oz`": 1,
  "Io-z`": 1,
  "Iô-n": 1,
  "I-ồn": 1,
  "Iồ-ñ": 1,
  "I-ồñ": 1,
  "Iô-n`": 1,
  "Iô-ng": 1,
  "ị-t": 1,
  "j-a?": 1,
  "k-0n": 1,
  "k0-n cac": 1,
  "K0-n Ch0": 1,
  "k0n c-h0 an cuc'": 1,
  "k0n m-0e- mAj": 1,
  "k0n m-3": 1,
  "k0n m-e": 1,
  "k0n m-e maj": 1,
  "K3 M-3": 1,
  "k4-v3": 1,
  "k4-ve": 1,
  "kaj d-yt mE": 1,
  "K-aj' dYt- mE": 1,
  "ka-k": 1,
  "k-at ku": 1,
  "ka-v3": 1,
  "ka-ve": 1,
  "k-ăc": 1,
  "k-ặc": 1,
  "k-ặç": 1,
  "k-it'": 1,
  "K-LM": 1,
  "K-on": 1,
  "ko-n DKM": 1,
  "ko-n ch0'": 1,
  "k-on cho'": 1,
  "k-on dj?": 1,
  "Ko-n Dkm": 1,
  "KO-N DY~": 1,
  "ko-n f0": 1,
  "k-on kac": 1,
  "kon k-ak": 1,
  "kO-n ky~": 1,
  "k-on m3": 1,
  "kon m-e": 1,
  "ko-n mẹ": 1,
  "kote-x": 1,
  "K-u": 1,
  "k-ụ": 1,
  "K-u*'t": 1,
  "kU-+t'": 1,
  "k-uc'": 1,
  "k-uc kut": 1,
  "K-UT": 1,
  "k-ut'": 1,
  "ku-t ch0": 1,
  "ku-t het": 1,
  "K-ut nat": 1,
  "K-uz": 1,
  "K-uz'": 1,
  "K-ứ†": 1,
  "Kứ-†…Çhó": 1,
  "K-ưt'": 1,
  "K-ưt́": 1,
  "k-ứt": 1,
  "kY-nh nguye^T-": 1,
  "kh-ìn": 1,
  "kh-jn`": 1,
  "kho-viIon": 1,
  "l do-g": 1,
  "l t-o": 1,
  "L-`": 1,
  "l-0^n`": 1,
  "l0-^z`": 1,
  "L-0`z": 1,
  "l0-n": 1,
  "l0o-n": 1,
  "l0-x": 1,
  "l-0z": 1,
  "l0-z`": 1,
  "l0z` me-j": 1,
  "l0-zl": 1,
  "l0-zl`": 1,
  "l0-zn": 1,
  "l0-zn`": 1,
  "l0-zz": 1,
  "La Li-em": 1,
  "lA ph-o`": 1,
  "la-m` fo`": 1,
  "li3-m": 1,
  "l-i3'm": 1,
  "lie^M: lolz` m-ek lolz`": 1,
  "li-e'm": 1,
  "LIE-M'": 1,
  "Lie-m I0n ch0": 1,
  "li'-m": 1,
  "lí-m": 1,
  "li-n`": 1,
  "l-jn": 1,
  "lj-n`": 1,
  "L-M": 1,
  "l-O^`n": 1,
  "L-o^lz`": 1,
  "l-o^n": 1,
  "l-o^n`": 1,
  "l-o^z": 1,
  "l-O^z`": 1,
  "lo^z-n`": 1,
  "l-O+i`": 1,
  "LO-0^N`": 1,
  "lo-0n`": 1,
  "lo-iz": 1,
  "l-ol": 1,
  "lO-lz": 1,
  "l-Ön": 1,
  "lo-n'": 1,
  "l-on`": 1,
  "lo-on": 1,
  "loo-n`": 1,
  "lo-z": 1,
  "l-öz": 1,
  "lo-z`": 1,
  "L-ozl": 1,
  "lo-zl`": 1,
  "lo-zn": 1,
  "L-ô`n": 1,
  "lÔ-lz": 1,
  "l-ôñ": 1,
  "L-ôñ̀": 1,
  "L-ồn": 1,
  "lồ-ñ": 1,
  "Lô-ǹ": 1,
  "lô-n`": 1,
  "l-ồnz": 1,
  "l-ồz": 1,
  "lu-`n": 1,
  "Lu-`n": 1,
  "Lu~ d-0g": 1,
  "lu~ re ra-ck:": 1,
  "lu~d-og": 1,
  "Lũ…Dog H-úp…Máu": 1,
  "lua ti-nh": 1,
  "lu-n`": 1,
  "luoj~ tat' va-`o dau` buoj`": 1,
  "lz-0`": 1,
  "lz-0n`": 1,
  "lz-o`": 1,
  "lZ-O`l": 1,
  "lz-ol": 1,
  "lz-ol`": 1,
  "lz-ồn": 1,
  "m€̣ m-Aj`": 1,
  "m-0m~": 1,
  "m-3": 1,
  "m3 ma-i": 1,
  "m-A(t- lOz": 1,
  "ma-u' Io`n": 1,
  "m-au' Ion": 1,
  "ma-u L": 1,
  "m-au l0z": 1,
  "ma-u lol": 1,
  "m-au loz": 1,
  "ma-u non`": 1,
  "M-Ay`": 1,
  "m-e": 1,
  "M-ẹ": 1,
  "M-ẹ̈": 1,
  "m-e chu-ng maj": 1,
  "m-e m-ai": 1,
  "m-e m-aj": 1,
  "me- Ma-j`": 1,
  "me-t loz": 1,
  "m-I": 1,
  "M-ịe": 1,
  "mi-e-": 1,
  "m-je": 1,
  "M-L": 1,
  "m-l": 1,
  "M-L`": 1,
  "m-l`": 1,
  "mo-^m loz": 1,
  "m-õm": 1,
  "Mo-m~": 1,
  "mo-m~ dog lu~ ch0": 1,
  "m-ú†": 1,
  "m-ut": 1,
  "mú-t": 1,
  "m-ut'": 1,
  "m-ut bi0i": 1,
  "mut b-u0j": 1,
  "m-ut ku": 1,
  "m-ut' lz0n`": 1,
  "Ñ-§ü": 1,
  "Ñ-gậm…ßµồ¡": 1,
  "ni-ém": 1,
  "nj-n`": 1,
  "n-o^n`": 1,
  "n-o`n": 1,
  "no-n": 1,
  "n-on^`": 1,
  "no-n`": 1,
  "n-ôn": 1,
  "n-ồn": 1,
  "N-ồñ": 1,
  "Ñ-ồñ": 1,
  "Nồ-n": 1,
  "Ñ-ôǹ": 1,
  "nỒ-z": 1,
  "n-u*ng'": 1,
  "nU-n`": 1,
  "nu-ng*' loz`": 1,
  "nứ-ng": 1,
  "ng-u": 1,
  "n-h0n`": 1,
  "nh-a` may`": 1,
  "n-ho^n`": 1,
  "nh-u cac": 1,
  "N-huc̣…": 1,
  "nh-uk": 1,
  "p-3`": 1,
  "p-à": 1,
  "p-A`": 1,
  "pa` m-ay`": 1,
  "pe-nis": 1,
  "playk-u": 1,
  "pó c-u": 1,
  "po k-u": 1,
  "pó k-u": 1,
  "po ma-y`": 1,
  "p-o\"": 1,
  "p-o`": 1,
  "P-uoi`": 1,
  "pu-ồj": 1,
  "Ph-`o": 1,
  "p-h0`": 1,
  "ph-a^n": 1,
  "ph-an^": 1,
  "ph-ân": 1,
  "ra-ck": 1,
  "R-áçk": 1,
  "r-ai'": 1,
  "ra-pe": 1,
  "re r-ack": 1,
  "rẻ ra-cḱ": 1,
  "s0-ck k0n me": 1,
  "S-elit": 1,
  "s-ip": 1,
  "sk-m": 1,
  "sO-ck": 1,
  "so-cl": 1,
  "ß-µ́": 1,
  "ßµ-ô¡": 1,
  "ßµ-ồ¡": 1,
  "ßµ-ồ¡¯": 1,
  "ßµ-ồ¿": 1,
  "ß-µồi": 1,
  "ß-µồï": 1,
  "ß-µồi¯": 1,
  "ßµ-ôî": 1,
  "ß-µồî": 1,
  "ß-ố": 1,
  "ßu-oi": 1,
  "ßu-oj": 1,
  "ß-uoj`": 1,
  "ßu-om": 1,
  "ß-uồi": 1,
  "ß-ựa": 1,
  "ßư-ớm": 1,
  "su-a?": 1,
  "s-uc vaT": 1,
  "t-bc": 1,
  "t-bs": 1,
  "Tie-n Su": 1,
  "Tu-oi? Io`n": 1,
  "tYnh tru-G`": 1,
  "tha-ng fo": 1,
  "thang p-ho": 1,
  "th-ang` fo": 1,
  "thoi k-en": 1,
  "thủ d-âm": 1,
  "thủ z-âm": 1,
  "thu-? za^m": 1,
  "tr1-nh": 1,
  "tri-nh": 1,
  "trj-nh": 1,
  "t-rlnh": 1,
  "tr-o'": 1,
  "tr-o\"": 1,
  "t-rym": 1,
  "try-nh": 1,
  "v-åi": 1,
  "v-kc": 1,
  "v-kl": 1,
  "v-l": 1,
  "v-ú": 1,
  "tư b-ản đỏ": 1,
  "tub-ando": 1,
  "tu b-an do": 1,
  "tư-bản": 1,
  "xã hội ch-ũ nghĩa": 1,
  "xahoic-hunghia": 1,
  "xã hoich-unghia": 1,
  "sã hội chũ ng-hĩa": 1,
  "xa hội chu-nghia": 1,
  "xahoi ch-ủ nghia": 1,
  "xahoic-hu nghĩa": 1,
  "tư bản ch-ủ nghĩa": 1,
  "tubanchu-nghia": 1,
  "tu ban ch-u nghia": 1,
  "tưbản-chủnghĩa": 1,
  "sã-hộichũnghĩa": 1,
  "xãhội-chũnghĩa": 1,
  "an*ca*c": 1,
  "anc*ac": 1,
  "ăn c*ặc": 1,
  "ăn*cặc": 1,
  "ba*ma*y": 1,
  "bà m*ày": 1,
  "ba m*ày": 1,
  "bà*may": 1,
  "ba*mày": 1,
  "bàm*ày": 1,
  "bac*h*o": 1,
  "ba*may": 1,
  "ban*d*am": 1,
  "ban*ho*a": 1,
  "banda*m": 1,
  "ba*nhoa": 1,
  "bán*hoa": 1,
  "bit*ch": 1,
  "bo*ma*y": 1,
  "bo*may": 1,
  "bon*ch*o": 1,
  "bon*kh*on*nan": 1,
  "bonc*ho": 1,
  "bonk*honnan": 1,
  "bre*ast": 1,
  "buc*ac": 1,
  "bu*ồi": 1,
  "buo*m": 1,
  "b*ướm": 1,
  "c*san": 1,
  "cạ*c": 1,
  "cặ*c": 1,
  "cai*bu*oi": 1,
  "cai*ch*im": 1,
  "cai*c*u": 1,
  "cai*lo*n": 1,
  "caib*uoi": 1,
  "caic*him": 1,
  "ca*icu": 1,
  "cail*on": 1,
  "ca*ve": 1,
  "ch*im": 1,
  "chi*m*to": 1,
  "chi*mto": 1,
  "ch*ó": 1,
  "cho*ch*et": 1,
  "c*ho*kin": 1,
  "cho*chet": 1,
  "chok*in": 1,
  "con*c*ho": 1,
  "c*on*cu": 1,
  "c*on*cu*cac": 1,
  "con*cu*to*tu*ong": 1,
  "c*on*di": 1,
  "con*die*m": 1,
  "con*ph*o": 1,
  "conc*ho": 1,
  "con*cu": 1,
  "con*cucac": 1,
  "concuto*tuong": 1,
  "co*ndi": 1,
  "condie*m": 1,
  "cong*hoa": 1,
  "co*ng*san": 1,
  "cong*san": 1,
  "conl*on": 1,
  "conp*ho": 1,
  "cs*an": 1,
  "c*ụ": 1,
  "cu*ca*c": 1,
  "cu*m*ay": 1,
  "cu*t*o": 1,
  "cuc*ca*c": 1,
  "cuc*c*ut": 1,
  "cu*cac": 1,
  "cucca*c": 1,
  "cuc*cut": 1,
  "cu*ho": 1,
  "cu*may": 1,
  "cu*nt": 1,
  "cuo*ng*dam": 1,
  "cuon*g*hiep": 1,
  "cuon*gdam": 1,
  "cuo*nghiep": 1,
  "c*ứt": 1,
  "cut*o": 1,
  "đ*ái": 1,
  "dâ*m": 1,
  "da*n*chu": 1,
  "dan*chu": 1,
  "da*ng*c*s": 1,
  "da*ng*cong*san": 1,
  "dang*cong*san": 1,
  "da*ng*cs": 1,
  "da*ng*tien*tri": 1,
  "dan*g*tientri": 1,
  "dang*congsan": 1,
  "dang*cs": 1,
  "dang*tien*tri": 1,
  "da*ngtientri": 1,
  "dc*m": 1,
  "đc*m": 1,
  "đ*ĩ": 1,
  "điế*m": 1,
  "di*s*me": 1,
  "di*sme": 1,
  "d*it": 1,
  "dị*t": 1,
  "đí*t": 1,
  "đị*t": 1,
  "d*it*bo": 1,
  "di*t*con*cu": 1,
  "dit*co*n*me": 1,
  "dit*c*oncu": 1,
  "dit*con*me": 1,
  "d*it*cu": 1,
  "dit*cu*m*ay": 1,
  "dit*m*e": 1,
  "dit*o*ng": 1,
  "dit*ba": 1,
  "d*itbo": 1,
  "dit*me": 1,
  "ditm*e": 1,
  "ditm*emay": 1,
  "dito*ng": 1,
  "d*m": 1,
  "đ*m": 1,
  "doco*ncho": 1,
  "do*khon": 1,
  "d*rug": 1,
  "d*ụ": 1,
  "đ*ụ": 1,
  "du*m*a": 1,
  "d*ục": 1,
  "du*ma": 1,
  "du*me": 1,
  "fu*ck": 1,
  "gai*b*an*hoa": 1,
  "gai*die*m": 1,
  "Gaiban*hoa": 1,
  "Gaid*iem": 1,
  "h*am*hiep": 1,
  "Hamh*iep": 1,
  "ha*nh*kinh": 1,
  "Ha*nhkinh": 1,
  "Hiế*p": 1,
  "hiep*da*m": 1,
  "Hiepda*m": 1,
  "ho*chi*mi*nh": 1,
  "hồ*chí*m*inh": 1,
  "ho*chim*inh": 1,
  "hochi*m*inh": 1,
  "Hochi*minh": 1,
  "I*ả": 1,
  "Ỉ*a": 1,
  "K*hốn": 1,
  "kho*n*nan": 1,
  "Kho*nnan": 1,
  "khu*ng*bo": 1,
  "Kh*ungbo": 1,
  "Ki*ep": 1,
  "Ki*ép": 1,
  "kiế*p": 1,
  "la*m*tinh": 1,
  "lam*tinh": 1,
  "lie*m*cac": 1,
  "lie*mcac": 1,
  "lì*n": 1,
  "lo*n": 1,
  "l*òn": 1,
  "lồ*n": 1,
  "lợ*n": 1,
  "lo*n*to": 1,
  "lo*ng*lon": 1,
  "lo*nglon": 1,
  "lo*nto": 1,
  "lu*ch*o": 1,
  "lu*k*hon": 1,
  "luc*ho": 1,
  "luk*hon": 1,
  "mau*k*inh": 1,
  "m*au*lon": 1,
  "mauki*nh": 1,
  "mau*lon": 1,
  "m*ẹ": 1,
  "m*e*kiep": 1,
  "me*m*ay": 1,
  "me*kiep": 1,
  "me*may": 1,
  "mi*e": 1,
  "moha*met": 1,
  "mua*da*m": 1,
  "mua*dam": 1,
  "mu*t*cac": 1,
  "mu*tbuoi": 1,
  "mut*cac": 1,
  "na*ke": 1,
  "ngu*yen*ai*quoc": 1,
  "nguy*en*aiquoc": 1,
  "nguyen*ai*quoc": 1,
  "nguyen*aiquoc": 1,
  "nguyenaiq*uoc": 1,
  "ong*m*ay": 1,
  "ongm*ay": 1,
  "pen*is": 1,
  "ph*ò": 1,
  "pim*p": 1,
  "rap*e": 1,
  "s*h*i*t": 1,
  "se*x": 1,
  "sh*it": 1,
  "sin*h*duc": 1,
  "sin*hduc": 1,
  "sl*ut": 1,
  "so*lo*n": 1,
  "s*olon": 1,
  "su*bo*ma*y": 1,
  "subo*may": 1,
  "th*ang*cho": 1,
  "than*gcho": 1,
  "tie*n*su": 1,
  "tien*su": 1,
  "tinh*du*c": 1,
  "tin*hduc": 1,
  "to*s*u": 1,
  "to*su": 1,
  "v*co*ng": 1,
  "vai*da*i": 1,
  "v*ai*leu": 1,
  "v*ai*lin": 1,
  "va*i*lon": 1,
  "vaida*i": 1,
  "va*ileu": 1,
  "vaili*n": 1,
  "va*ilon": 1,
  "vco*ng": 1,
  "viet*co*ng": 1,
  "vietc*ong": 1,
  "Thà*nh Hồ": 1,
  "Tha*nh Ho": 1,
  "Vua Đi*nh": 1,
  "Vu*a Lê": 1,
  "H*oa Lư": 1,
  "Cố *Đô Huế": 1,
  "1*ồn": 1,
  "1*Ồn": 1,
  "1ồ*N": 1,
  "1*0n": 1,
  "1*0`n": 1,
  "1`0*n": 1,
  "1*o`n": 1,
  "1Ồ*N": 1,
  "*Ba*cHo*": 1,
  "*Bac*Ho*": 1,
  "*Ba*cho*": 1,
  "*b*acHo*": 1,
  "*bAc*Ho*": 1,
  "ba*c*ho": 1,
  "B*ac*ho": 1,
  "b*ac*Ho": 1,
  "Ba*c*Ho": 1,
  "B*ác Hồ": 1,
  "b*ác Hồ": 1,
  "B*ác hồ": 1,
  "bá*c hồ": 1,
  "b*Ác Hồ": 1,
  "bÁ*c hỒ": 1,
  "bá*C Hồ": 1,
  "b4*c Hồ": 1,
  "b4c h*Ồ": 1,
  "b'*4c Hồ": 1,
  "b'4*c hỒ": 1,
  "b4'*c Hồ": 1,
  "b4'*c hỒ": 1,
  "ba*c h0": 1,
  "B*ac h0": 1,
  "bac H*0": 1,
  "B*ac H0": 1,
  "b*itch": 1,
  "BIT*CH": 1,
  "Bi*tch": 1,
  "Bu*oi": 1,
  "bu*oi`": 1,
  "B*uoi`": 1,
  "b*uồi": 1,
  "Bu*ồi": 1,
  "b*u0`i": 1,
  "Bu*0`i": 1,
  "bu*Ồi": 1,
  "Bu*Ồi": 1,
  "congs*an": 1,
  "co*ng san": 1,
  "Cong* san": 1,
  "co*ng San": 1,
  "Con*g San": 1,
  "cộn*g sản": 1,
  "cộn*g Sản": 1,
  "Cộn*g sản": 1,
  "Con*gsan": 1,
  "Con*gSan": 1,
  "cuh*o": 1,
  "Cu*ho": 1,
  "cuH*o": 1,
  "CuH*o": 1,
  "c*uh0": 1,
  "Cuh*0": 1,
  "cu*H0": 1,
  "Cu*H0": 1,
  "Cu*h*o": 1,
  "cU*h*o": 1,
  "cu**Ho": 1,
  "cu*h*O": 1,
  "c*ụ hồ": 1,
  "Cụ h*ồ": 1,
  "cỤ h*ồ": 1,
  "cụ H*ồ": 1,
  "cụ h*Ồ": 1,
  "c*a**c": 1,
  "C*a**c": 1,
  "c*A**c": 1,
  "C*A**c": 1,
  "C*A**C": 1,
  "c4*c": 1,
  "C*4c": 1,
  "C4*C": 1,
  "ca*c*": 1,
  "C*ac*": 1,
  "c*Ac*": 1,
  "C*AC*": 1,
  "că*c*": 1,
  "C*ăc*": 1,
  "cĂ*c*": 1,
  "C*Ăc*": 1,
  "CĂ*C*": 1,
  "c*ặc": 1,
  "C*ặc": 1,
  "c*Ặc": 1,
  "CẶ*c": 1,
  "C*ẶC": 1,
  "cav*e": 1,
  "Ca*ve": 1,
  "cA*ve": 1,
  "CA*VE": 1,
  "c*Ave": 1,
  "C*ứt": 1,
  "c*Ứt": 1,
  "C*ỨT": 1,
  "C*Ứt": 1,
  "d*1t": 1,
  "D1*t": 1,
  "D*1T": 1,
  "d*ai'": 1,
  "Da*i'": 1,
  "dA*i'": 1,
  "D*AI'": 1,
  "d*ái": 1,
  "đá*i": 1,
  "Đ*ái": 1,
  "Đ*ÁI": 1,
  "d*âm": 1,
  "dÂ*m": 1,
  "dam*n": 1,
  "DAM*N": 1,
  "DC*M": 1,
  "ĐC*M": 1,
  "Đc*M": 1,
  "Đc*m": 1,
  "Đ*ĩ": 1,
  "đ*i~": 1,
  "Đ*i~": 1,
  "Đ*Ĩ": 1,
  "Đ*I~": 1,
  "d*i~": 1,
  "D*ĩ": 1,
  "D*I~": 1,
  "d*i*t": 1,
  "D*i*t": 1,
  "d*I*t": 1,
  "D*I*T": 1,
  "đ*i*t": 1,
  "Đ*i*t": 1,
  "Đ*I*T": 1,
  "đ*Ịt": 1,
  "Đ*ịt": 1,
  "Đ*ịT": 1,
  "Đ*ỊT": 1,
  "d*is": 1,
  "D*is": 1,
  "d*iS": 1,
  "đi*s": 1,
  "Đ*is": 1,
  "đi*t": 1,
  "D*it": 1,
  "Đ*it": 1,
  "DI*T": 1,
  "ĐI*T": 1,
  "đi*ếm": 1,
  "Đi*ếm": 1,
  "điẾ*m": 1,
  "Đi*Ếm": 1,
  "ĐiẾ*M": 1,
  "D*m": 1,
  "D*M": 1,
  "Đ*m": 1,
  "Đ*M": 1,
  "dm*m": 1,
  "đm*m": 1,
  "Dm*m": 1,
  "Đm*m": 1,
  "DM*M": 1,
  "ĐM*M": 1,
  "Đ*cm": 1,
  "đC*M": 1,
  "đcm*m": 1,
  "dk*m": 1,
  "đk*m": 1,
  "d*cm": 1,
  "dk*mm": 1,
  "đk*mm": 1,
  "đ*Ụ": 1,
  "Đ*ụ": 1,
  "Đ*Ụ": 1,
  "đ*u*": 1,
  "Đ*u*": 1,
  "Đ*U*": 1,
  "F*uck": 1,
  "FU*CK": 1,
  "f*u**c*k": 1,
  "F*U*C**K": 1,
  "G4m*eMaster": 1,
  "G4me*M4ster": 1,
  "G4me*Ma*ster": 1,
  "G4me*M4s*ter": 1,
  "G4*me*Master": 1,
  "G4m*e*M4ster": 1,
  "Ga*meMaster": 1,
  "Gam*e*Master": 1,
  "[Game]*Master": 1,
  "Game*M*aster": 1,
  "Game[M*aster]": 1,
  "G*M": 1,
  "[G]*M": 1,
  "G*[M]": 1,
  "G**M": 1,
  "Hồ chí m*inh": 1,
  "HỒ c*hí minh": 1,
  "hồ C*hí minh": 1,
  "hồ chí Mi*nh": 1,
  "Hồ ch*í Minh": 1,
  "h*ồ Chí minh": 1,
  "hồ ch*í minh": 1,
  "hochi*minh": 1,
  "HoCh*iMinh": 1,
  "HOCH*IMINH": 1,
  "ho*ch*i*minh": 1,
  "Ho*Ch*i*Minh": 1,
  "ho ch*i minh": 1,
  "Ho C*hi Minh": 1,
  "HO C*HI MINH": 1,
  "hi*ếp": 1,
  "Hi*ếp": 1,
  "HI*ẾP": 1,
  "lo*`n": 1,
  "L*o`n": 1,
  "lo*n`": 1,
  "L*on`": 1,
  "Lồ*n": 1,
  "lô*n": 1,
  "L*ôn": 1,
  "LÔ*N": 1,
  "L*ỒN": 1,
  "l*Ồn": 1,
  "m*k": 1,
  "M*k": 1,
  "M*K": 1,
  "nông đứ*c mạnh": 1,
  "Nông *Đức Mạnh": 1,
  "nongduc*manh": 1,
  "NONG*DUCMANH": 1,
  "PE*NIS": 1,
  "Phạ*m Văn Đồng": 1,
  "phạm vă*n đồng": 1,
  "phamvand*ong": 1,
  "PHAM*VANDONG": 1,
  "Ph*ò": 1,
  "ph*Ò": 1,
  "PH*Ò": 1,
  "p*ho`": 1,
  "Ph*o`": 1,
  "PH*O`": 1,
  "Ra*pe": 1,
  "RA*PE": 1,
  "s*ex": 1,
  "Se*x": 1,
  "SE*X": 1,
  "sh*1t": 1,
  "Sh1*t": 1,
  "SH1*T": 1,
  "Sh*it": 1,
  "SH*IT": 1,
  "tổ*ng bí thư": 1,
  "Tổng B*í Thư": 1,
  "tongb*ithu": 1,
  "tong b*i thu": 1,
  "Vietcon*g": 1,
  "VIETC*ONG": 1,
  "viet c*ong": 1,
  "Vi*et Cong": 1,
  "VIET C*ONG": 1,
  "việt c*ông": 1,
  "Việ*t Cộng": 1,
  "VIỆT C*ỘNG": 1,
  "L*ìn": 1,
  "LÌ*N": 1,
  "li*`n": 1,
  "Li*`n": 1,
  "LI`*N": 1,
  "th*ủ dâm": 1,
  "Thủ Dâ*m": 1,
  "TH*Ủ DÂ*M": 1,
  "!ồ**n": 1,
  "£*j*n`": 1,
  "£*ô`n": 1,
  "£ô*Ñ": 1,
  "£*ồn": 1,
  "£*ồñ": 1,
  "₫*éo": 1,
  "₫*iṭ": 1,
  "₫y*t": 1,
  "y*t*": 1,
  "¶)*¡t": 1,
  "¶)*ị†": 1,
  "¶*ồ*ñ": 1,
  "¶*ơ*Ñ": 1,
  "¶*ồñ": 1,
  "†*¡ñ": 1,
  "†*€̀": 1,
  "†*ổ": 1,
  "1o*n": 1,
  "1*ôn": 1,
  "1ồ*n": 1,
  "a(n c*ac": 1,
  "a*m vat": 1,
  "an b*uoi": 1,
  "an k*ut": 1,
  "an k*uz": 1,
  "a*n loz": 1,
  "an no*^n": 1,
  "äñ*£0ñ": 1,
  "An*Loz": 1,
  "ăn bu*oi": 1,
  "b*µ́": 1,
  "Bµ0*m": 1,
  "bµ*ồi": 1,
  "b*0 cu": 1,
  "b*0 ku": 1,
  "b*3`": 1,
  "b*à": 1,
  "b*a`": 1,
  "bí*m": 1,
  "b*kl": 1,
  "bó c*u": 1,
  "bo k*u": 1,
  "b*ó ku": 1,
  "b*o^'": 1,
  "B*u'": 1,
  "b*u b": 1,
  "b*u' b": 1,
  "bu b*u0j": 1,
  "bu b*uoi": 1,
  "bu b*uoj": 1,
  "bu l*ol": 1,
  "bu' l*ol": 1,
  "bu lo*z": 1,
  "bu' lo*z": 1,
  "bu*0^j": 1,
  "bu*0+m": 1,
  "b*u0i": 1,
  "bu*0j": 1,
  "bu*0j`": 1,
  "bu0*j`": 1,
  "b*u0m": 1,
  "bu*0'm": 1,
  "b*u0z`": 1,
  "Bu*Bu0¡": 1,
  "bub*uoj": 1,
  "bu*o^i": 1,
  "bU*O^J`": 1,
  "bu*o^'m": 1,
  "bu*O^y`": 1,
  "bu*oi^": 1,
  "bu*oj": 1,
  "b*uoj`": 1,
  "bu*om": 1,
  "bu*o'm": 1,
  "bu*ôi": 1,
  "B*uôì": 1,
  "bU*ôj": 1,
  "bU*ồj": 1,
  "bu*ồy": 1,
  "buớ*m": 1,
  "bư*ớm": 1,
  "bư*m": 1,
  "BV*S": 1,
  "by*m": 1,
  "bý*m": 1,
  "c0*n dy~": 1,
  "c0n f*0`": 1,
  "c*0n m3": 1,
  "c0*n me": 1,
  "c0n m*ẹ": 1,
  "c0*n phO": 1,
  "C0nch*0": 1,
  "c0n*g s4n": 1,
  "c4*v3": 1,
  "c4*ve": 1,
  "c*a*c": 1,
  "c*Ac": 1,
  "c*ạc": 1,
  "C*ạ̈c": 1,
  "c*ac*": 1,
  "cai d*is": 1,
  "c*ai' dis": 1,
  "cái d*is": 1,
  "cAi DK*M": 1,
  "c*ai' loz": 1,
  "cailo*z": 1,
  "caj di*s": 1,
  "caj dj*jt me": 1,
  "ca*j DKM": 1,
  "c*aj loz": 1,
  "caj lo*zl": 1,
  "ca*j…Đị†": 1,
  "ca*k": 1,
  "cA*M IồN": 1,
  "ca*v3": 1,
  "că*c": 1,
  "cặ*ç": 1,
  "Ç*ăç": 1,
  "C*ăk": 1,
  "cặ*k": 1,
  "c*ec*": 1,
  "çh*ÿm": 1,
  "C*L": 1,
  "c*ON": 1,
  "Ço*ñ": 1,
  "co*n cac": 1,
  "Çøn Ç*hǿ": 1,
  "c*on ch0": 1,
  "C*on di~": 1,
  "co*n di~": 1,
  "con die*m": 1,
  "co*n fò": 1,
  "cO*n fO`": 1,
  "con I*on`": 1,
  "co*n m3": 1,
  "con m*e": 1,
  "co*n mẹ": 1,
  "cong sa*n": 1,
  "çU*+t'": 1,
  "cu0n*g da^m": 1,
  "c*uc'": 1,
  "cuc g*a`": 1,
  "Ç*ứ†": 1,
  "c*h0'": 1,
  "Ch*0́": 1,
  "CH*0\'\'": 1,
  "ch0 g*hE dis": 1,
  "ch0 Su*a": 1,
  "ch*0*": 1,
  "Ch*0'a": 1,
  "ch*ém": 1,
  "Ch*et": 1,
  "CH*IM": 1,
  "CHI*M": 1,
  "chj*m": 1,
  "ch*o'": 1,
  "chO kO*n bu'": 1,
  "ch*o\"": 1,
  "Ch*ui": 1,
  "ch*uj": 1,
  "ch*uj?": 1,
  "ch*uj~": 1,
  "ch*uYm": 1,
  "C*hửi**": 1,
  "Ch*ym": 1,
  "ch*ym": 1,
  "d*!t": 1,
  "D!*t": 1,
  "D!*TL": 1,
  "D*yt": 1,
  "D*¥¶¯": 1,
  "D†C*M": 1,
  "d*0g": 1,
  "d*1~": 1,
  "d1*t": 1,
  "dá*¡": 1,
  "d*aj": 1,
  "d*áj": 1,
  "da*j'": 1,
  "da*mn": 1,
  "dang ha*ng": 1,
  "dạn*g háng": 1,
  "d*Âm": 1,
  "de*0": 1,
  "d*e0'": 1,
  "de*0\"": 1,
  "d*e0`": 1,
  "de*0~": 1,
  "d*ek": 1,
  "DE*K'": 1,
  "de*o": 1,
  "d*e'o": 1,
  "D*eó": 1,
  "d*éo": 1,
  "de*o'": 1,
  "De*O'": 1,
  "D*EO": 1,
  "de*O' iA?": 1,
  "de*o kut'": 1,
  "d*eo\"": 1,
  "d*et m3": 1,
  "d*Et* mE*": 1,
  "d*ey the'": 1,
  "d*ĩ": 1,
  "D**ĩ": 1,
  "d*i*S": 1,
  "di*S m*e*": 1,
  "D*ï§": 1,
  "d*i†": 1,
  "d*ị†": 1,
  "d*ï†": 1,
  "di*en": 1,
  "D*i*ếm": 1,
  "d*iit": 1,
  "di*s": 1,
  "d*ïs": 1,
  "D*IS'": 1,
  "dis c0n m*e": 1,
  "dis c*0n mje": 1,
  "DIS CO*0N ME": 1,
  "di*s cu": 1,
  "Dis K0*n Me": 1,
  "d*is k*u": 1,
  "di*s m*e": 1,
  "Di*s m*e*": 1,
  "D*is m*e…": 1,
  "Di*s*": 1,
  "d*is*": 1,
  "Di*sd": 1,
  "dis*me": 1,
  "dis*s m3": 1,
  "Dis*s Me": 1,
  "d*isss": 1,
  "d*i't": 1,
  "Dị*t": 1,
  "di*x": 1,
  "di*z": 1,
  "d*z": 1,
  "d*j": 1,
  "d*j~": 1,
  "d*j†": 1,
  "dj*e^'m": 1,
  "dj*E^m'": 1,
  "dj*em": 1,
  "dj*em'": 1,
  "D*jf": 1,
  "D*jit": 1,
  "D*jj~": 1,
  "djj*t": 1,
  "Dj*s": 1,
  "d*jx": 1,
  "D*jz": 1,
  "D*K": 1,
  "d*K*": 1,
  "dK*m": 1,
  "D*lT": 1,
  "do*et*": 1,
  "D*ú": 1,
  "d*u m3": 1,
  "du m*a": 1,
  "du m*á": 1,
  "du m*e maj`": 1,
  "d*u*": 1,
  "d*u* Me*": 1,
  "du` mo*a' an kut'": 1,
  "du*k*": 1,
  "duon*g vat": 1,
  "D*UYT": 1,
  "du*yt": 1,
  "D*Ÿ Ḿ": 1,
  "d*y*t": 1,
  "D*y*t": 1,
  "d*y`n": 1,
  "d*Y~": 1,
  "dy~ de*o' daj traj": 1,
  "d*ys": 1,
  "dyS m*jE": 1,
  "d*yt": 1,
  "dY*t'": 1,
  "dY*t": 1,
  "d*yt'": 1,
  "Dyt B*uoj ": 1,
  "dyt c*0n m3": 1,
  "dỵt c0*n me": 1,
  "dyt cai I0*ng c0ng l0z": 1,
  "dy*t dyt": 1,
  "Dyt K0*an": 1,
  "dYT k*0n m3": 1,
  "d*yt kon me": 1,
  "dyt kon m*e kaj\'\' loz`": 1,
  "dyt k*on me sock": 1,
  "Dy*t ku*": 1,
  "dyt l0*z": 1,
  "dy*t m": 1,
  "D*Yt m3": 1,
  "Dyt m*3 an Kuz": 1,
  "dyt m*e": 1,
  "D*yt Me": 1,
  "dYt m*E nUnG l0zl": 1,
  "dyt m*e thagfo`": 1,
  "dyt *mE*": 1,
  "Dyt *me*": 1,
  "dY*t mJe": 1,
  "Đ*!†": 1,
  "Đ*¡§": 1,
  "Đ*¡†": 1,
  "đ*¡̣†": 1,
  "Đ*¡•t": 1,
  "Đ*¡̣t": 1,
  "đ¥*†": 1,
  "Đ*¥̣†": 1,
  "Đ*¥t": 1,
  "Đ¥̣*T": 1,
  "Đ€́*ø": 1,
  "Đ*µ": 1,
  "đ*µ̣": 1,
  "Đµ̣* Møª́": 1,
  "Đµ́*†": 1,
  "Đ†ç*m": 1,
  "đả*ng": 1,
  "đ*é0": 1,
  "Đe*ó": 1,
  "đ*éo": 1,
  "Đ*ï": 1,
  "Đĩ Đ*ựç": 1,
  "Đ*ị†": 1,
  "đị̈*†": 1,
  "Đ*i†": 1,
  "đi†Çâ*ñAñh": 1,
  "Đi†m*ẹ": 1,
  "đi*ên": 1,
  "Đ*iĩ": 1,
  "Đị*s": 1,
  "Đ*is Mẹ": 1,
  "Đ*it M3*": 1,
  "Đi*t mẹ": 1,
  "Đ*ịt me": 1,
  "Đ*ịt mẹ": 1,
  "Đ*ịt*": 1,
  "Địt* Đ*ỳn": 1,
  "Đ*ịt***": 1,
  "đ*iz": 1,
  "Đ*î†̣": 1,
  "Đị̂*†": 1,
  "Đ*ị̂†…mẹ": 1,
  "Đ*ị̂t": 1,
  "Đ*j̃": 1,
  "đ*J†": 1,
  "đ*jếm": 1,
  "đjế*m ": 1,
  "đj*t": 1,
  "Đ*j̣t": 1,
  "đk*lm": 1,
  "Đk*m": 1,
  "ĐK*M": 1,
  "đl*t": 1,
  "đ*u": 1,
  "Đ*ụ mẹ": 1,
  "Đ*ỹ": 1,
  "Đ*ÿ§": 1,
  "Đy*†": 1,
  "Đ*ÿ†": 1,
  "Đỵ̈*†": 1,
  "Đ*y†": 1,
  "Đỵ† k*ụ": 1,
  "Đ*Ỵ̈† m€̣": 1,
  "Đ*ys…": 1,
  "Đ*yt": 1,
  "Đ*ỴT": 1,
  "Đ*Ÿt": 1,
  "đ*Yt": 1,
  "đ*yṭ mẹ": 1,
  "Đ*yt me*": 1,
  "đy*t*": 1,
  "Đ*yz": 1,
  "f`*O`": 1,
  "ƒµ¢*¶«": 1,
  "Fµ*ck": 1,
  "ƒµ*ck": 1,
  "ƒµ*çk": 1,
  "f*0": 1,
  "ƒ*0": 1,
  "ƒ*0ƒ": 1,
  "f*ho`": 1,
  "f*o": 1,
  "F*ò": 1,
  "f*ö̀": 1,
  "f*ø̀": 1,
  "ƒ*o": 1,
  "ƒ*ò": 1,
  "ƒ*ø̀": 1,
  "f*o`": 1,
  "ƒ*o`": 1,
  "f*oo`": 1,
  "ƒu*c¶«": 1,
  "ƒu*ck": 1,
  "ƒü*çk": 1,
  "Fu*uck": 1,
  "gh*e?": 1,
  "gie? Ra*ch'": 1,
  "ha*m~ Ion": 1,
  "h*am~ loz": 1,
  "ham~ lo*zl": 1,
  "ha*m~ lozn`": 1,
  "ha*mloz": 1,
  "hc*m": 1,
  "hi*3p": 1,
  "hi*3'p": 1,
  "hi*e'p": 1,
  "hie*p'": 1,
  "h*iếp": 1,
  "hiê*p'": 1,
  "hj*ep": 1,
  "H*L`": 1,
  "i*tnh*au": 1,
  "I^0*N": 1,
  "I*0^k`": 1,
  "I*0`n": 1,
  "I*0`n`": 1,
  "I0*n": 1,
  "I*0n`": 1,
  "I*0z": 1,
  "i*ạ": 1,
  "ỉ*a": 1,
  "I*O^`n": 1,
  "I*o^n": 1,
  "I*O^*n": 1,
  "I*o^n`": 1,
  "IO*^n`": 1,
  "I*o^ng": 1,
  "I*o`n": 1,
  "Io*`n": 1,
  "I*on": 1,
  "Io*n`": 1,
  "Io*n` me": 1,
  "Io*n`* Dis": 1,
  "I*oZ": 1,
  "I*oz": 1,
  "I*oz`": 1,
  "Io*z`": 1,
  "Iô*n": 1,
  "I*ồn": 1,
  "Iồ*ñ": 1,
  "I*ồñ": 1,
  "Iô*n`": 1,
  "Iô*ng": 1,
  "ị*t": 1,
  "j*a?": 1,
  "k*0n": 1,
  "k0*n cac": 1,
  "K0*n Ch0": 1,
  "k0n c*h0 an cuc'": 1,
  "k0n m*0e* mAj": 1,
  "k0n m*3": 1,
  "k0n m*e": 1,
  "k0n m*e maj": 1,
  "K3 M*3": 1,
  "k4*v3": 1,
  "k4*ve": 1,
  "kaj d*yt mE": 1,
  "K*aj' dYt* mE": 1,
  "ka*k": 1,
  "k*at ku": 1,
  "ka*v3": 1,
  "ka*ve": 1,
  "k*ăc": 1,
  "k*ặc": 1,
  "k*ặç": 1,
  "k*it'": 1,
  "K*LM": 1,
  "K*on": 1,
  "ko*n DKM": 1,
  "ko*n ch0'": 1,
  "k*on cho'": 1,
  "k*on dj?": 1,
  "Ko*n Dkm": 1,
  "KO*N DY~": 1,
  "ko*n f0": 1,
  "k*on kac": 1,
  "kon k*ak": 1,
  "kO*n ky~": 1,
  "k*on m3": 1,
  "kon m*e": 1,
  "ko*n mẹ": 1,
  "kote*x": 1,
  "K*u": 1,
  "k*ụ": 1,
  "K*u*'t": 1,
  "kU*+t'": 1,
  "k*uc'": 1,
  "k*uc kut": 1,
  "K*UT": 1,
  "k*ut'": 1,
  "ku*t ch0": 1,
  "ku*t het": 1,
  "K*ut nat": 1,
  "K*uz": 1,
  "K*uz'": 1,
  "K*ứ†": 1,
  "Kứ*†…Çhó": 1,
  "K*ưt'": 1,
  "K*ưt́": 1,
  "k*ứt": 1,
  "kY*nh nguye^T*": 1,
  "kh*ìn": 1,
  "kh*jn`": 1,
  "kho*viIon": 1,
  "l do*g": 1,
  "l t*o": 1,
  "L*`": 1,
  "l*0^n`": 1,
  "l0*^z`": 1,
  "L*0`z": 1,
  "l0*n": 1,
  "l0o*n": 1,
  "l0*x": 1,
  "l*0z": 1,
  "l0*z`": 1,
  "l0z` me*j": 1,
  "l0*zl": 1,
  "l0*zl`": 1,
  "l0*zn": 1,
  "l0*zn`": 1,
  "l0*zz": 1,
  "La Li*em": 1,
  "lA ph*o`": 1,
  "la*m` fo`": 1,
  "li3*m": 1,
  "l*i3'm": 1,
  "lie^M: lolz` m*ek lolz`": 1,
  "li*e'm": 1,
  "LIE*M'": 1,
  "Lie*m I0n ch0": 1,
  "li'*m": 1,
  "lí*m": 1,
  "li*n`": 1,
  "l*jn": 1,
  "lj*n`": 1,
  "L*M": 1,
  "l*O^`n": 1,
  "L*o^lz`": 1,
  "l*o^n": 1,
  "l*o^n`": 1,
  "l*o^z": 1,
  "l*O^z`": 1,
  "lo^z*n`": 1,
  "l*O+i`": 1,
  "LO*0^N`": 1,
  "lo*0n`": 1,
  "lo*iz": 1,
  "l*ol": 1,
  "lO*lz": 1,
  "l*Ön": 1,
  "lo*n'": 1,
  "l*on`": 1,
  "lo*on": 1,
  "loo*n`": 1,
  "lo*z": 1,
  "l*öz": 1,
  "lo*z`": 1,
  "L*ozl": 1,
  "lo*zl`": 1,
  "lo*zn": 1,
  "L*ô`n": 1,
  "lÔ*lz": 1,
  "l*ôñ": 1,
  "L*ôñ̀": 1,
  "L*ồn": 1,
  "lồ*ñ": 1,
  "Lô*ǹ": 1,
  "lô*n`": 1,
  "l*ồnz": 1,
  "l*ồz": 1,
  "lu*`n": 1,
  "Lu*`n": 1,
  "Lu~ d*0g": 1,
  "lu~ re ra*ck:": 1,
  "lu~d*og": 1,
  "Lũ…Dog H*úp…Máu": 1,
  "lua ti*nh": 1,
  "lu*n`": 1,
  "luoj~ tat' va*`o dau` buoj`": 1,
  "lz*0`": 1,
  "lz*0n`": 1,
  "lz*o`": 1,
  "lZ*O`l": 1,
  "lz*ol": 1,
  "lz*ol`": 1,
  "lz*ồn": 1,
  "m€̣ m*Aj`": 1,
  "m*0m~": 1,
  "m*3": 1,
  "m3 ma*i": 1,
  "m*A(t* lOz": 1,
  "ma*u' Io`n": 1,
  "m*au' Ion": 1,
  "ma*u L": 1,
  "m*au l0z": 1,
  "ma*u lol": 1,
  "m*au loz": 1,
  "ma*u non`": 1,
  "M*Ay`": 1,
  "m*e": 1,
  "M*ẹ": 1,
  "M*ẹ̈": 1,
  "m*e chu*ng maj": 1,
  "m*e m*ai": 1,
  "m*e m*aj": 1,
  "me* Ma*j`": 1,
  "me*t loz": 1,
  "m*I": 1,
  "M*ịe": 1,
  "mi*e*": 1,
  "m*je": 1,
  "M*L": 1,
  "m*l": 1,
  "M*L`": 1,
  "m*l`": 1,
  "mo*^m loz": 1,
  "m*õm": 1,
  "Mo*m~": 1,
  "mo*m~ dog lu~ ch0": 1,
  "m*ú†": 1,
  "m*ut": 1,
  "mú*t": 1,
  "m*ut'": 1,
  "m*ut bi0i": 1,
  "mut b*u0j": 1,
  "m*ut ku": 1,
  "m*ut' lz0n`": 1,
  "Ñ*§ü": 1,
  "Ñ*gậm…ßµồ¡": 1,
  "ni*ém": 1,
  "nj*n`": 1,
  "n*o^n`": 1,
  "n*o`n": 1,
  "no*n": 1,
  "n*on^`": 1,
  "no*n`": 1,
  "n*ôn": 1,
  "n*ồn": 1,
  "N*ồñ": 1,
  "Ñ*ồñ": 1,
  "Nồ*n": 1,
  "Ñ*ôǹ": 1,
  "nỒ*z": 1,
  "n*u*ng'": 1,
  "nU*n`": 1,
  "nu*ng*' loz`": 1,
  "nứ*ng": 1,
  "ng*u": 1,
  "n*h0n`": 1,
  "nh*a` may`": 1,
  "n*ho^n`": 1,
  "nh*u cac": 1,
  "N*huc̣…": 1,
  "nh*uk": 1,
  "p*3`": 1,
  "p*à": 1,
  "p*A`": 1,
  "pa` m*ay`": 1,
  "pe*nis": 1,
  "playk*u": 1,
  "pó c*u": 1,
  "po k*u": 1,
  "pó k*u": 1,
  "po ma*y`": 1,
  "p*o\"": 1,
  "p*o`": 1,
  "P*uoi`": 1,
  "pu*ồj": 1,
  "Ph*`o": 1,
  "p*h0`": 1,
  "ph*a^n": 1,
  "ph*an^": 1,
  "ph*ân": 1,
  "ra*ck": 1,
  "R*áçk": 1,
  "r*ai'": 1,
  "ra*pe": 1,
  "re r*ack": 1,
  "rẻ ra*cḱ": 1,
  "s0*ck k0n me": 1,
  "S*elit": 1,
  "s*ip": 1,
  "sk*m": 1,
  "sO*ck": 1,
  "so*cl": 1,
  "ß*µ́": 1,
  "ßµ*ô¡": 1,
  "ßµ*ồ¡": 1,
  "ßµ*ồ¡¯": 1,
  "ßµ*ồ¿": 1,
  "ß*µồi": 1,
  "ß*µồï": 1,
  "ß*µồi¯": 1,
  "ßµ*ôî": 1,
  "ß*µồî": 1,
  "ß*ố": 1,
  "ßu*oi": 1,
  "ßu*oj": 1,
  "ß*uoj`": 1,
  "ßu*om": 1,
  "ß*uồi": 1,
  "ß*ựa": 1,
  "ßư*ớm": 1,
  "su*a?": 1,
  "s*uc vaT": 1,
  "t*bc": 1,
  "t*bs": 1,
  "Tie*n Su": 1,
  "Tu*oi? Io`n": 1,
  "tYnh tru*G`": 1,
  "tha*ng fo": 1,
  "thang p*ho": 1,
  "th*ang` fo": 1,
  "thoi k*en": 1,
  "thủ d*âm": 1,
  "thủ z*âm": 1,
  "thu*? za^m": 1,
  "tr1*nh": 1,
  "tri*nh": 1,
  "trj*nh": 1,
  "t*rlnh": 1,
  "tr*o'": 1,
  "tr*o\"": 1,
  "t*rym": 1,
  "try*nh": 1,
  "v*åi": 1,
  "v*kc": 1,
  "v*kl": 1,
  "v*l": 1,
  "v*ú": 1,
  "tư b*ản đỏ": 1,
  "tub*ando": 1,
  "tu b*an do": 1,
  "tư*bản": 1,
  "xã hội ch*ũ nghĩa": 1,
  "xahoic*hunghia": 1,
  "xã hoich*unghia": 1,
  "sã hội chũ ng*hĩa": 1,
  "xa hội chu*nghia": 1,
  "xahoi ch*ủ nghia": 1,
  "xahoic*hu nghĩa": 1,
  "tư bản ch*ủ nghĩa": 1,
  "tubanchu*nghia": 1,
  "tu ban ch*u nghia": 1,
  "tưbản*chủnghĩa": 1,
  "sã*hộichũnghĩa": 1,
  "xãhội*chũnghĩa": 1,
  "nong duc manh": 1,
  "nong ducmanh": 1,
  "nongduc manh": 1,
  "Chính phủ": 1,
  "Chínhphủ": 1,
  "CSVN": 1,
  "le kha phieu": 1,
  "Lê khả phiêu": 1,
  "Lêkhả phiêu": 1,
  "Lê khảphiêu": 1,
  "lekha phieu": 1,
  "le khaphieu": 1,
  "lekhaphieu": 1,
  "VNCH": 1,
  "Trung Cộng-Việt Cộng": 1,
  "trungcong-vietcong": 1,
  "trungcong-viet cong": 1,
  "trung cong-viet cong": 1,
  "trung cong-vietcong": 1,
  "TrungCộng-Việt Cộng": 1,
  "TrungCộng-ViệtCộng": 1,
  "Trung Cộng-ViệtCộng": 1,
  "Phạm Văn Ðồng": 1,
  "PhạmVăn Ðồng": 1,
  "PhạmVănÐồng": 1,
  "Phạm VănÐồng": 1,
  "phamvandong": 1,
  "pham vandong": 1,
  "pham van dong": 1,
  "phamvan dong": 1,
  "VNDCCH": 1,
  "Trung Cộng": 1,
  "TrungCộng": 1,
  "trungcong": 1,
  "trung cong": 1,
  "Ðại Nam": 1,
  "ÐạiNam": 1,
  "DaiNam": 1,
  "Dai Nam": 1,
  "chính trị": 1,
  "chinh tri": 1,
  "Nguyễn Huệ": 1,
  "Quang Trung": 1,
  "Hai Bà Trưng": 1,
  "Nguyen Hue": 1,
  "Hai Ba Trung": 1,
  "Nguyễn Minh Triết": 1,
  "Nguyen Minh Triet": 1,
  "Nguyễn Tấn Dũng": 1,
  "Nguyen Tan Dung": 1,
  "quốc hội": 1,
  "quoc hoi": 1,
  "bộ trính trị": 1,
  "bo trinh tri": 1,
  "đảng": 1,
  "Đảng Cộng sản Việt Nam": 1,
  "dang cong san Viet Nam": 1,
  "Nguyễn Thị Doan": 1,
  "mat tran to quoc Viet Nam": 1,
  "mặt trận tổ quốc Việt Nam": 1,
  "khủng bố": 1,
  "Nguyen Thai Hoc": 1,
  "Nguyễn Thái Học": 1,
  "Cần Lao": 1,
  "Can lao": 1,
  "Ngô Đình Diệm": 1,
  "Ngo Dinh Diem": 1,
  "ông Hồ": 1,
  "Hồ chủ tịch": 1,
  "Ho chu tich": 1,
  "Việt tân": 1,
  "Viet tan": 1,
  "phản động": 1,
  "phan dong": 1,
  "Hitler": 1,
  "Stalin": 1,
  "Bach Dang Giang": 1,
  "Bạch Đằng Giang": 1,
  "CHXHCN": 1,
  "cách mạng mầu": 1,
  "cach mang mau": 1,
  "Đảng thăng tiến": 1,
  "khoi 8406": 1,
  "Khối 8406": 1,
  "Đảng dân chủ XXI": 1,
  "dang dan chu XXI": 1,
  "Bô-xit": 1,
  "bo-xit": 1,
  "bauxite": 1,
  "phản quốc": 1,
  "phan quoc": 1
};